// Downloadable PDF twins of selected in-tool graphics.
//
// Keith, 2026-07-30: "for each and every graphic we use that we developed, can
// we allow users to download the PDF onto their local machine? ... That way our
// graphics have even more value to the end users."
//
// NOT one per SVG, and that was Keith's call. He reviewed all 125 graphics in
// `assets/tool-graphics/` and picked four, on the grounds that "some probably are
// not valuable enough for the PDF level of extra care." Bundling all of them
// would have added roughly 18 MB to every platform; these four add 0.6 MB.
//
// WHY BUNDLED RATHER THAN FETCHED. This is a field tool. The moment somebody
// needs a battery chart is the moment they are standing in a plant room with no
// signal, so the file has to already be on the device.
//
// The PDFs are generated by `Team Knowledge/scripts/svg-to-pdf.py` in the myPKA
// repo: headless Chrome, one page, page sized to the artwork's own viewBox so
// there is no margin and no letterbox. Text is outlined rather than embedded for
// faces Chrome cannot embed, which prints identically anywhere and only loses
// text selection.
//
// ADDING ONE: drop the PDF in `assets/tool-graphics-pdf/<asset-name>.pdf` using
// the SAME stem as the SVG, then add the pair below. The stem match is the whole
// contract; nothing scans the manifest at runtime.
library;

/// Maps an in-tool graphic's asset name to the human title used for the
/// downloaded filename.
///
/// The key is the SVG asset name (the same string passed to `LargeGraphic`), so
/// a caller that can draw the graphic can ask about its PDF without knowing any
/// paths. The value is a plain-English title; `pdfDownloadFilename` slugifies it
/// into `WLAN-Pros-<Title>.pdf`.
abstract final class GraphicPdfs {
  static const String _dir = 'assets/tool-graphics-pdf';

  /// Every graphic with a downloadable PDF, and the title its file carries.
  ///
  /// Keep the titles readable: they become the filename a user sees in their
  /// Files app or Downloads folder, and "battery-code-exploded.pdf" is a worse
  /// thing to find six months later than "WLAN-Pros-Battery-Code-Explained.pdf".
  static const Map<String, String> _titles = <String, String>{
    'battery-code-exploded': 'Battery Code Explained',
    'battery-size-ladder': 'Battery Size Ladder',
    'fiber-two-color-systems': 'Fiber Two Color Systems',
    'mac-bit-field': 'MAC Address Bit Fields',
  };

  /// True when [assetName] has a downloadable PDF.
  ///
  /// Callers use this to decide whether to render a download affordance at all.
  /// A control that appears and then fails is worse than one that never appears.
  static bool has(String assetName) => _titles.containsKey(assetName);

  /// Bundle path for [assetName]'s PDF. Null when there is none.
  static String? path(String assetName) =>
      has(assetName) ? '$_dir/$assetName.pdf' : null;

  /// Human title for [assetName], used to build the download filename.
  static String? title(String assetName) => _titles[assetName];

  /// Every asset name that has a PDF. Exposed so a test can assert that each
  /// declared entry actually exists in the bundle, which is the failure this
  /// class cannot detect on its own.
  static Iterable<String> get assetNames => _titles.keys;
}
