// SSID Airtime — DIFFERENTIAL test against Jonathan Finney's own JavaScript.
//
// WHY THIS SHAPE. `ssid_airtime.dart` is a PORT. Hand-written expectations would
// only prove the port matches what the porter believed the source did, which is
// exactly the failure mode a port has. So the fixture is generated by running
// Finney's own functions, lifted verbatim from his published HTML (VERSION 1.0,
// VDATE 29 August 2026), over a swept parameter space in Node. Our Dart must
// reproduce every one of his numbers.
//
// Fixture: test/fixtures/fin_ssid_airtime_cases.json — 3,987 cases, stratified
// from a 36,864-case sweep. Every HR/DSSS rate and the CCK/OFDM seam are kept in
// full, because that boundary is where a port breaks. Regenerate with the
// harness recorded in the session log if his source ever changes.
//
// TOLERANCE. 1e-9 relative. These are the same IEEE-754 doubles doing the same
// operations in the same order, so agreement should be near-exact; anything
// looser would hide a real divergence.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wlan_pros_toolbox/services/rf/ssid_airtime.dart';

WifiAmendment _amendOf(String s) => switch (s) {
      'ac' => WifiAmendment.ac,
      'ax' => WifiAmendment.ax,
      'be' => WifiAmendment.be,
      _ => throw ArgumentError('unknown amendment $s'),
    };

/// Relative comparison that also handles the exact-zero case.
void _expectClose(double actual, double expected, String what) {
  if (expected == 0) {
    expect(actual.abs() < 1e-9, isTrue,
        reason: '$what: expected 0, got $actual');
    return;
  }
  final double rel = (actual - expected).abs() / expected.abs();
  expect(rel < 1e-9, isTrue,
      reason: '$what: expected $expected, got $actual (rel $rel)');
}

void main() {
  group('SSID Airtime — port fidelity against the upstream JavaScript', () {
    late List<dynamic> cases;

    setUpAll(() {
      final File f = File('test/fixtures/fin_ssid_airtime_cases.json');
      expect(f.existsSync(), isTrue,
          reason: 'reference fixture missing — the port cannot be validated');
      cases = jsonDecode(f.readAsStringSync()) as List<dynamic>;
    });

    test('the fixture is present and substantial', () {
      expect(cases.length, greaterThan(3000));
    });

    test('every swept case reproduces Finney\'s numbers exactly', () {
      int checked = 0;
      for (final dynamic raw in cases) {
        final Map<String, dynamic> c = raw as Map<String, dynamic>;

        final SsidAirtimeShared shared = SsidAirtimeShared(
          countContention: c['contention'] as bool,
          countProbes: c['probes'] as bool,
          wildcardPercent: (c['wildcard'] as num).toDouble(),
          amendment: _amendOf(c['amend'] as String),
          mlLinks: (c['mlLinks'] as num).toInt(),
          mlBytes: 40,
        );

        final SsidAirtimeBand band = SsidAirtimeBand(
          name: 'case ${c['id']}',
          ssids: (c['ssids'] as num).toInt(),
          mbssid: c['mbssid'] as bool,
          rate: (c['rate'] as num).toDouble(),
          coChannelAps: (c['co'] as num).toInt(),
          clients: 25,
          probesPerMinute: 6,
          activeScanning: true,
          noCck: c['noCck'] as bool,
          beaconIntervalTu: (c['tu'] as num).toDouble(),
        );

        final SsidAirtimeResult r =
            SsidAirtimeCalculator(shared).compute(band);
        final String id = 'case ${c['id']} '
            '(${c['amend']}, rate ${c['rate']}, ssids ${c['ssids']}, '
            'mbssid ${c['mbssid']}, noCck ${c['noCck']}, '
            'contention ${c['contention']}, probes ${c['probes']})';

        _expectClose(r.beaconPercent, (c['bPct'] as num).toDouble(), '$id beaconPercent');
        _expectClose(r.probePercent, (c['pPct'] as num).toDouble(), '$id probePercent');
        _expectClose(r.marginalPercent, (c['marg'] as num).toDouble(), '$id marginalPercent');
        _expectClose(r.longestTxopUs, (c['txop'] as num).toDouble(), '$id longestTxopUs');
        _expectClose(r.beaconSizeBytes, (c['size'] as num).toDouble(), '$id beaconSizeBytes');
        _expectClose(r.perApUs, (c['perAp'] as num).toDouble(), '$id perApUs');
        checked++;
      }
      expect(checked, cases.length);
    });
  });

  group('SSID Airtime — the properties the model is FOR', () {
    const SsidAirtimeShared occupancy = SsidAirtimeShared();

    test('1 TU is 1024 us, not 1000 — the classic amateur error', () {
      // One SSID, one AP, beacon at 6 Mbps, 100 TU. beaconPercent must be
      // frameUs/102400, so a 1000-us TU would inflate it by 2.4%.
      const SsidAirtimeBand b = SsidAirtimeBand(name: '5', ssids: 1, coChannelAps: 1);
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double frame = calc.frameUs(400, 6);
      final SsidAirtimeResult r = calc.compute(b);
      _expectClose(r.beaconPercent, 100 * frame / (100 * 1024), 'TU basis');
    });

    test('11 Mbps uses the DSSS formula, NOT the OFDM one', () {
      // This is the defect Pax found in the 2026-08-21 build and Finney fixed.
      // Guard it so a future refactor cannot reintroduce it.
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double at11 = calc.frameUs(400, 11);
      // DSSS: 192 us long preamble + (8*400)/11.
      _expectClose(at11, 192 + (8 * 400) / 11, '11 Mbps is DSSS');
      // And it must NOT equal the OFDM computation for the same rate.
      final double asOfdm = 20 + (((22 + 8 * 400) / (11 * 4)).ceil()) * 4;
      expect((at11 - asOfdm).abs() > 1, isTrue,
          reason: '11 Mbps must not be computed as OFDM');
    });

    test('OFDM airtime quantises to whole 4 us symbols', () {
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      // Sweep byte counts; every result minus the 20 us preamble is a multiple of 4.
      for (int bytes = 100; bytes <= 500; bytes++) {
        final double us = calc.frameUs(bytes.toDouble(), 6) - 20;
        expect(us % 4, 0, reason: '$bytes bytes at 6 Mbps did not land on a symbol');
      }
    });

    test('MBSSID is cheaper than separate beacons, and the gap widens', () {
      const SsidAirtimeBand legacy = SsidAirtimeBand(name: '6', ssids: 8, mbssid: false);
      const SsidAirtimeBand mb = SsidAirtimeBand(name: '6', ssids: 8, mbssid: true);
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double a = calc.compute(legacy).beaconPercent;
      final double b = calc.compute(mb).beaconPercent;
      expect(b, lessThan(a));

      // At 16 SSIDs the ratio must be more favourable still.
      final double a16 = calc.compute(legacy.copyWith(ssids: 16)).beaconPercent;
      final double b16 = calc.compute(mb.copyWith(ssids: 16)).beaconPercent;
      expect(b16 / a16, lessThan(b / a));
    });

    test('beacon airtime scales linearly with co-channel APs', () {
      const SsidAirtimeBand one = SsidAirtimeBand(name: '5', coChannelAps: 1);
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double a = calc.compute(one).beaconPercent;
      final double d = calc.compute(one.copyWith(coChannelAps: 4)).beaconPercent;
      _expectClose(d, a * 4, 'airtime is a CHANNEL property');
    });

    test('5 and 6 GHz coerce a CCK rate to 6 Mbps', () {
      const SsidAirtimeBand ghz5 = SsidAirtimeBand(name: '5', rate: 11, noCck: true);
      const SsidAirtimeBand ghz24 = SsidAirtimeBand(name: '2.4', rate: 11, noCck: false);
      expect(ghz5.effectiveRate(occupancy), 6);
      expect(ghz24.effectiveRate(occupancy), 11);
    });

    test('the marginal SSID costs more at a lower basic rate', () {
      const SsidAirtimeBand fast = SsidAirtimeBand(name: '2.4', rate: 24, ssids: 4);
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double atSix = calc.compute(fast.copyWith(rate: 6)).marginalPercent;
      final double at24 = calc.compute(fast).marginalPercent;
      expect(atSix, greaterThan(at24));
    });

    test('occupancy is the default, and contention only ever adds', () {
      const SsidAirtimeBand b = SsidAirtimeBand(name: '2.4', rate: 6, ssids: 8);
      final double occ = const SsidAirtimeCalculator(occupancy).compute(b).total;
      final double cont = SsidAirtimeCalculator(
        occupancy.copyWith(countContention: true),
      ).compute(b).total;
      expect(cont, greaterThan(occ));
      expect(const SsidAirtimeCalculator(occupancy).accessUs(6), 0);
    });

    test('probes are off by default and scale with the wildcard share', () {
      const SsidAirtimeBand b = SsidAirtimeBand(name: '2.4', ssids: 8);
      expect(const SsidAirtimeCalculator(occupancy).compute(b).probePercent, 0);

      final double directed = SsidAirtimeCalculator(
        occupancy.copyWith(countProbes: true, wildcardPercent: 0),
      ).compute(b).probePercent;
      final double wildcard = SsidAirtimeCalculator(
        occupancy.copyWith(countProbes: true, wildcardPercent: 100),
      ).compute(b).probePercent;
      // A wildcard probe is answered by all 8 BSSs; a directed one by one.
      expect(wildcard, greaterThan(directed));
    });

    test('802.11be multi-link adds beacon bytes, and only under be', () {
      const SsidAirtimeBand b = SsidAirtimeBand(name: '6', ssids: 1);
      final double axLinks3 = SsidAirtimeCalculator(
        occupancy.copyWith(amendment: WifiAmendment.ax, mlLinks: 3),
      ).compute(b).beaconSizeBytes;
      final double axLinks1 = SsidAirtimeCalculator(
        occupancy.copyWith(amendment: WifiAmendment.ax, mlLinks: 1),
      ).compute(b).beaconSizeBytes;
      expect(axLinks3, axLinks1, reason: 'multi-link must not apply under ax');

      final double beLinks3 = SsidAirtimeCalculator(
        occupancy.copyWith(amendment: WifiAmendment.be, mlLinks: 3),
      ).compute(b).beaconSizeBytes;
      final double beLinks1 = SsidAirtimeCalculator(
        occupancy.copyWith(amendment: WifiAmendment.be, mlLinks: 1),
      ).compute(b).beaconSizeBytes;
      _expectClose(beLinks3 - beLinks1, 2 * 40, 'two extra links at 40 bytes each');
    });

    test('48 Mbps is offered as a basic rate — our one addition upstream lacks', () {
      expect(kBasicRates.contains(48), isTrue);
      // And it must compute as OFDM, landing between 36 and 54.
      final SsidAirtimeCalculator calc = SsidAirtimeCalculator(occupancy);
      final double at36 = calc.frameUs(400, 36);
      final double at48 = calc.frameUs(400, 48);
      final double at54 = calc.frameUs(400, 54);
      expect(at48, lessThan(at36));
      expect(at48, greaterThan(at54));
    });

    test('severity thresholds match the upstream bands', () {
      SsidAirtimeResult at(double total) => SsidAirtimeResult(
            beaconPercent: total,
            probePercent: 0,
            marginalPercent: 0,
            longestTxopUs: 0,
            beaconSizeBytes: 0,
            perApUs: 0,
          );
      expect(at(4.9).severity, AirtimeSeverity.healthy);
      expect(at(5).severity, AirtimeSeverity.busy);
      expect(at(14.9).severity, AirtimeSeverity.busy);
      expect(at(15).severity, AirtimeSeverity.congested);
      expect(at(100).severity, AirtimeSeverity.congested);
      expect(at(100.1).severity, AirtimeSeverity.oversubscribed);
    });
  });
}
