// ═══════════════════════════════════════════════════════════════════════════
// REFERENCE-VECTOR VERIFICATION — PART A (RF / PHYSICS)
//
// Every expected value in this file is transcribed from
//   Deliverables/2026-07-11-calculator-verification/REFERENCE-VECTORS.md
// which was derived from ITU-R P.525-4, ITU-R P.530-18, ITU-R P.838-3,
// IEEE 802.3bt (Ethernet Alliance whitepaper), IEEE 802.11-2020, the Times
// Microwave LMR-400 datasheet, and closed-form derivations from SI-exact
// constants — BY AN AUTHOR WHO NEVER READ THIS CODEBASE.
//
// This is deliberately unlike the pre-existing calculator tests, whose
// expected values were generated by running this code (and which therefore
// prove the port is faithful, not that it is correct).
//
// ┌──────────────────────────────────────────────────────────────────────────┐
// │ IF A TEST IN THIS FILE FAILS, THAT IS THE DELIVERABLE.                   │
// │ Do NOT change an expected value. Do NOT widen a tolerance. Do NOT patch  │
// │ lib/ to make it green. A disagreement between a vector and the code      │
// │ means one of the two is wrong and we do not yet know which.              │
// └──────────────────────────────────────────────────────────────────────────┘
//
// Groups tagged [FAILING] were red on the verification run of 2026-07-11 and
// are left red on purpose. Groups tagged [NOT RUNNABLE] hold vectors the app
// has no API for; they are `skip`ped with the reason, not deleted.
// ═══════════════════════════════════════════════════════════════════════════

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:wlan_pros_toolbox/data/channel_frequency_data.dart';
import 'package:wlan_pros_toolbox/data/unit_conversion.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/antenna_length_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/cable_loss_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/downtilt_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/earth_curvature_screen.dart'
    as ec;
import 'package:wlan_pros_toolbox/screens/tools/calculators/eirp_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/fresnel_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/fspl_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/link_budget_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/metric_conversion_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/noise_floor_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/poe_budget_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/ptp_link_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/rain_fade_screen.dart'
    as rf;
import 'package:wlan_pros_toolbox/screens/tools/calculators/throughput_calc_screen.dart';
import 'package:wlan_pros_toolbox/screens/tools/calculators/wavelength_screen.dart';
import 'package:wlan_pros_toolbox/theme/app_theme.dart';

import 'reference_vector_expect.dart';

// ── Thin adapters: drive the REAL app functions the way the REAL screens do ──

/// FSPL exactly as the screen computes it: raw field values + unit toggles →
/// the screen's own normalizers → the screen's own `fsplDb`.
double appFspl(double freq, FreqUnit fu, double dist, DistUnit du) =>
    FsplScreen.fsplDb(
      FsplScreen.freqToGHz(freq, fu),
      FsplScreen.distToKm(dist, du),
    );

Unit _unit(UnitCategory c, String id) =>
    UnitConversion.unitsFor(c).firstWhere((Unit u) => u.id == id);

/// dBm → mW through the app's Unit Converter model.
double appDbmToMw(double dbm) => UnitConversion.convert(
  dbm,
  UnitCategory.power,
  _unit(UnitCategory.power, 'dbm'),
  _unit(UnitCategory.power, 'mw'),
);

/// mW → dBm through the app's Unit Converter model.
double appMwToDbm(double mw) => UnitConversion.convert(
  mw,
  UnitCategory.power,
  _unit(UnitCategory.power, 'mw'),
  _unit(UnitCategory.power, 'dbm'),
);

void main() {
  // ═════════════════════════════════════════════════════════════════════════
  // §A1 — FREE SPACE PATH LOSS                     (Pax trap #3: the constant)
  //
  // The app's fsplDb() takes (GHz, km) and adds 92.45. The 32.4478/(-27.5522)
  // landmine can only fire through the unit normalizers, so every vector below
  // is driven through freqToGHz()/distToKm() — not by calling fsplDb() with
  // hand-normalized numbers, which would test nothing.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A1 FSPL — ITU-R P.525-4', () {
    test('A1-1  f=2400 MHz, d=1 km', () {
      expectVector(
        id: 'A1-1',
        tool: 'FSPL',
        input: 'f = 2400 MHz, d = 1 km',
        expected: 100.0520,
        actual: appFspl(2400, FreqUnit.mhz, 1, DistUnit.km),
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    test('A1-2  f=5000 MHz, d=0.1 km', () {
      expectVector(
        id: 'A1-2',
        tool: 'FSPL',
        input: 'f = 5000 MHz, d = 0.1 km (100 m)',
        expected: 86.4272,
        actual: appFspl(5000, FreqUnit.mhz, 0.1, DistUnit.km),
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    test('A1-3  f=6000 MHz, d=10 m', () {
      expectVector(
        id: 'A1-3',
        tool: 'FSPL',
        input: 'f = 6000 MHz, d = 10 m',
        expected: 68.0108,
        actual: appFspl(6000, FreqUnit.mhz, 10, DistUnit.m),
        tolerance: 0.05,
        unit: 'dB',
        trap: 'metres + MHz — the (m, MHz) path is 60 dB wrong if the '
            'normalizer is skipped',
      );
    });

    test('A1-4  f=2400 MHz, d=1 m  [the ~40 dB sanity anchor]', () {
      expectVector(
        id: 'A1-4',
        tool: 'FSPL',
        input: 'f = 2400 MHz, d = 1 m',
        expected: 40.0520,
        actual: appFspl(2400, FreqUnit.mhz, 1, DistUnit.m),
        tolerance: 0.05,
        unit: 'dB',
        trap: 'every RF engineer knows FSPL@1 m, 2.4 GHz ≈ 40 dB',
      );
    });

    test('A1-5  f=5800 MHz, d=5 km', () {
      expectVector(
        id: 'A1-5',
        tool: 'FSPL',
        input: 'f = 5800 MHz, d = 5 km',
        expected: 121.6957,
        actual: appFspl(5800, FreqUnit.mhz, 5, DistUnit.km),
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    // The unit paths, explicitly. Same physics, every input encoding the
    // screen offers. A wrong-unit function passes ONE of these and fails the
    // rest — which is exactly the failure a naive spot-check misses.
    test('A1-1/A1-4 unit paths — GHz, km, m and mi must all agree', () {
      expectVector(
        id: 'A1-1 (GHz+km path)',
        tool: 'FSPL',
        input: 'f = 2.4 GHz, d = 1 km',
        expected: 100.0520,
        actual: appFspl(2.4, FreqUnit.ghz, 1, DistUnit.km),
        tolerance: 0.05,
        unit: 'dB',
      );
      expectVector(
        id: 'A1-1 (mi path)',
        tool: 'FSPL',
        input: 'f = 2400 MHz, d = 0.621371 mi (= 1 km)',
        expected: 100.0520,
        actual: appFspl(2400, FreqUnit.mhz, 0.621371, DistUnit.mi),
        tolerance: 0.05,
        unit: 'dB',
      );
      expectVector(
        id: 'A1-3 (GHz+m path)',
        tool: 'FSPL',
        input: 'f = 6 GHz, d = 10 m',
        expected: 68.0108,
        actual: appFspl(6, FreqUnit.ghz, 10, DistUnit.m),
        tolerance: 0.05,
        unit: 'dB',
      );
      expectVector(
        id: 'A1-4 (GHz+km path)',
        tool: 'FSPL',
        input: 'f = 2.4 GHz, d = 0.001 km (= 1 m)',
        expected: 40.0520,
        actual: appFspl(2.4, FreqUnit.ghz, 0.001, DistUnit.km),
        tolerance: 0.05,
        unit: 'dB',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A2 — EIRP
  // The app exposes ONE loss field, so cable + connector losses are summed by
  // the user. The vectors' separate cable/connector terms are summed here.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A2 EIRP — IEEE Std 145-2013', () {
    test('A2-1  20 dBm, 3.0 dB cable + 0.5 dB connectors, 9 dBi', () {
      final double e = EirpScreen.eirpDbm(
        power: 20,
        unit: EirpPowerUnit.dBm,
        lossDb: 3.5, // 3.0 cable + 0.5 connectors — app has one loss field
        gainDbi: 9,
      )!;
      expectVector(
        id: 'A2-1',
        tool: 'EIRP',
        input: 'Ptx = 20 dBm, loss = 3.5 dB (3.0 cable + 0.5 conn), G = 9 dBi',
        expected: 25.5,
        actual: e,
        tolerance: 0.01,
        unit: 'dBm',
      );
      expectVector(
        id: 'A2-1 (mW)',
        tool: 'EIRP',
        input: 'EIRP = 25.5 dBm → mW',
        expected: 354.81,
        actual: EirpScreen.eirpWatts(e) * 1000,
        tolerance: 0.05,
        unit: 'mW',
      );
    });

    test('A2-2  30 dBm (1 W), 0 dB, 6 dBi', () {
      final double e = EirpScreen.eirpDbm(
        power: 30,
        unit: EirpPowerUnit.dBm,
        lossDb: 0,
        gainDbi: 6,
      )!;
      expectVector(
        id: 'A2-2',
        tool: 'EIRP',
        input: 'Ptx = 30 dBm, loss = 0 dB, G = 6 dBi',
        expected: 36.0,
        actual: e,
        tolerance: 0.01,
        unit: 'dBm',
      );
      expectVector(
        id: 'A2-2 (W)',
        tool: 'EIRP',
        input: 'EIRP = 36 dBm → W',
        expected: 3.981,
        actual: EirpScreen.eirpWatts(e),
        tolerance: 0.001,
        unit: 'W',
      );
    });

    test('A2-3  23 dBm, 1.5 dB, 5 dBd (= 7.15 dBi)  [the dBd trap]', () {
      // The app has NO dBd input — the gain field is labelled dBi. That is the
      // correct design per the vector; the dBd→dBi conversion is done here.
      expectVector(
        id: 'A2-3',
        tool: 'EIRP',
        input: 'Ptx = 23 dBm, loss = 1.5 dB, G = 5 dBd = 7.15 dBi',
        expected: 28.65,
        actual: EirpScreen.eirpDbm(
          power: 23,
          unit: EirpPowerUnit.dBm,
          lossDb: 1.5,
          gainDbi: 7.15,
        )!,
        tolerance: 0.01,
        unit: 'dBm',
        trap: 'a bare "gain" field invites the silent 2.15 dB dBd/dBi error',
      );
    });

    test('EIRP power-unit paths — W and mW (B5-9 / B5-6 traps)', () {
      expectVector(
        id: 'B5-9 (via EIRP W path)',
        tool: 'EIRP',
        input: 'Ptx = 1 W, loss = 0, G = 0',
        expected: 30.0,
        actual: EirpScreen.eirpDbm(
          power: 1,
          unit: EirpPowerUnit.w,
          lossDb: 0,
          gainDbi: 0,
        )!,
        tolerance: 0.0001,
        unit: 'dBm',
        trap: 'watts into a mW-expecting 10·log10 returns 0 dBm — 30 dB out',
      );
      expectVector(
        id: 'B5-6 (via EIRP mW path)',
        tool: 'EIRP',
        input: 'Ptx = 100 mW, loss = 0, G = 0',
        expected: 20.0,
        actual: EirpScreen.eirpDbm(
          power: 100,
          unit: EirpPowerUnit.mW,
          lossDb: 0,
          gainDbi: 0,
        )!,
        tolerance: 0.0001,
        unit: 'dBm',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A3 — LINK BUDGET / FADE MARGIN
  // Path loss is an INPUT on this screen, so the chain is driven end-to-end:
  // the app's own FSPL feeds the app's own link budget.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A3 Link budget — the app FSPL feeds the app link budget', () {
    test('A3-1  Prx over a 5 km / 5800 MHz link', () {
      expectVector(
        id: 'A3-1',
        tool: 'Link Budget',
        input: 'Tx 20 dBm; tx cable 2 dB; tx ant 20 dBi; d 5 km; f 5800 MHz; '
            'rx ant 20 dBi; rx cable 2 dB',
        expected: -65.696,
        actual: LinkBudgetScreen.receivedDbm(
          txPowerDbm: 20,
          txGain: 20,
          txLoss: 2,
          pathLoss: appFspl(5800, FreqUnit.mhz, 5, DistUnit.km),
          rxLoss: 2,
          rxGain: 20,
          misc: 0,
        ),
        tolerance: 0.05,
        unit: 'dBm',
      );
    });

    test('A3-2  fade margin vs −80 dBm sensitivity', () {
      final double prx = LinkBudgetScreen.receivedDbm(
        txPowerDbm: 20,
        txGain: 20,
        txLoss: 2,
        pathLoss: appFspl(5800, FreqUnit.mhz, 5, DistUnit.km),
        rxLoss: 2,
        rxGain: 20,
        misc: 0,
      );
      expectVector(
        id: 'A3-2',
        tool: 'Link Budget',
        input: 'A3-1 with RxSensitivity = −80 dBm',
        expected: 14.304,
        actual: LinkBudgetScreen.linkMarginDb(prx, -80),
        tolerance: 0.05,
        unit: 'dB',
        trap: 'sign flip on a negative sensitivity yields −15 and a false FAIL',
      );
    });

    test('A3-3  Prx over a 20 m / 5180 MHz indoor hop', () {
      expectVector(
        id: 'A3-3',
        tool: 'Link Budget',
        input: 'Tx 23 dBm; tx cable 0; tx ant 4 dBi; d 20 m; f 5180 MHz; '
            'rx ant 0 dBi; rx cable 0',
        expected: -45.727,
        actual: LinkBudgetScreen.receivedDbm(
          txPowerDbm: 23,
          txGain: 4,
          txLoss: 0,
          pathLoss: appFspl(5180, FreqUnit.mhz, 20, DistUnit.m),
          rxLoss: 0,
          rxGain: 0,
          misc: 0,
        ),
        tolerance: 0.05,
        unit: 'dBm',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A4 — FRESNEL ZONE                    🟥 Pax trap #1 — HIGHEST PRIORITY
  //
  // The 8.657 constant is 17.31452/2 and is valid ONLY in the midpoint form
  // 8.657·sqrt(D/f). Paired with the d1·d2/(f·D) argument it halves every
  // radius and every clearance verdict becomes dangerously optimistic.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A4 Fresnel — ITU-R P.530-18 §2.2.2  [trap #1: the 8.657 halving]',
      () {
    test('A4-1  d1 = d2 = 5 km, f = 5.0 GHz', () {
      final FresnelResult r = FresnelScreen.compute(
        freqGHz: 5.0,
        totalMeters: 10000,
      )!;
      expectVector(
        id: 'A4-1',
        tool: 'Fresnel',
        input: 'd1 = d2 = 5 km (D = 10 km), f = 5.0 GHz',
        expected: 12.2433,
        actual: r.radiusMid,
        tolerance: 0.02,
        unit: 'm',
        trap: 'the 8.657 bug returns 6.12 m here — half',
      );
      expectVector(
        id: 'A4-1 (60%)',
        tool: 'Fresnel',
        input: 'as A4-1, 60% clearance',
        expected: 7.3460,
        actual: r.clearanceMid,
        tolerance: 0.02,
        unit: 'm',
      );
      expectNotTheBug(
        id: 'A4-1 [8.657 SENTINEL]',
        tool: 'Fresnel',
        input: 'd1 = d2 = 5 km, f = 5.0 GHz',
        actual: r.radiusMid,
        bugValue: 6.1217, // what 8.657·sqrt(d1·d2/(f·D)) would have returned
        tolerance: 0.02,
        bugName: '8.657 paired with the d1·d2/(f·D) argument — every Fresnel '
            'radius halved, every clearance verdict optimistic',
        unit: 'm',
      );
    });

    test('A4-2  d1 = d2 = 0.5 km, f = 2.4 GHz', () {
      final FresnelResult r = FresnelScreen.compute(
        freqGHz: 2.4,
        totalMeters: 1000,
      )!;
      expectVector(
        id: 'A4-2',
        tool: 'Fresnel',
        input: 'd1 = d2 = 0.5 km (D = 1 km), f = 2.4 GHz',
        expected: 5.5882,
        actual: r.radiusMid,
        tolerance: 0.02,
        unit: 'm',
      );
      expectVector(
        id: 'A4-2 (60%)',
        tool: 'Fresnel',
        input: 'as A4-2, 60% clearance',
        expected: 3.3529,
        actual: r.clearanceMid,
        tolerance: 0.02,
        unit: 'm',
      );
    });

    test('A4-3  ASYMMETRIC: d1 = 2 km, d2 = 8 km, f = 5.8 GHz', () {
      // Deliberately off-midpoint: catches code that silently assumes d1 = d2.
      final FresnelResult r = FresnelScreen.compute(
        freqGHz: 5.8,
        totalMeters: 10000,
        pointFromTxMeters: 2000,
      )!;
      expectVector(
        id: 'A4-3',
        tool: 'Fresnel',
        input: 'd1 = 2 km, d2 = 8 km (D = 10 km), f = 5.8 GHz',
        expected: 9.0940,
        actual: r.radiusAtPoint!,
        tolerance: 0.02,
        unit: 'm',
        trap: 'asymmetric on purpose — catches a hardcoded midpoint',
      );
      expectVector(
        id: 'A4-3 (60%)',
        tool: 'Fresnel',
        input: 'as A4-3, 60% clearance',
        expected: 5.4564,
        actual: r.clearanceAtPoint!,
        tolerance: 0.02,
        unit: 'm',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A5 — CABLE LOSS                                             [FAILING]
  //
  // The vectors come from the Times Microwave LMR-400 datasheet fit
  //   dB/100ft = 0.122290·√f_MHz + 0.000260·f_MHz
  // which reproduces the manufacturer's own published table (6.8 @ 2500 MHz,
  // 10.8 @ 5800 MHz). The app instead ships a hand-entered knot table.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A5 Cable loss — Times Microwave LMR-400 datasheet  [FAILING]', () {
    test('A5-1  LMR-400 @ 2500 MHz — datasheet says 6.8 dB/100ft', () {
      expectVector(
        id: 'A5-1',
        tool: 'Cable Loss',
        input: 'LMR-400, f = 2500 MHz',
        expected: 6.7645,
        actual: CableLossScreen.cableLossPer100ft('LMR-400', 2500)!,
        tolerance: 0.05,
        unit: 'dB/100ft',
        trap: 'Times Microwave publishes 6.8 dB/100ft at this frequency',
      );
    });

    test('A5-2  LMR-400 @ 5800 MHz — datasheet says 10.8 dB/100ft', () {
      expectVector(
        id: 'A5-2',
        tool: 'Cable Loss',
        input: 'LMR-400, f = 5800 MHz',
        expected: 10.8213,
        actual: CableLossScreen.cableLossPer100ft('LMR-400', 5800)!,
        tolerance: 0.05,
        unit: 'dB/100ft',
        trap: 'Times Microwave publishes 10.8 dB/100ft at this frequency',
      );
    });

    test('A5-3  LMR-400, 2400 MHz, 50 ft', () {
      expectVector(
        id: 'A5-3',
        tool: 'Cable Loss',
        input: 'LMR-400, f = 2400 MHz, length = 50 ft',
        expected: 3.3075,
        actual: CableLossScreen.totalLossDb(
          CableLossScreen.cableLossPer100ft('LMR-400', 2400)!,
          CableLossScreen.lengthToFeet(50, CableLengthUnit.ft),
        ),
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    test('A5-4  LMR-400, 2400 MHz, 10 m  [the ft/m path]', () {
      expectVector(
        id: 'A5-4',
        tool: 'Cable Loss',
        input: 'LMR-400, f = 2400 MHz, length = 10 m (32.808 ft)',
        expected: 2.1704,
        actual: CableLossScreen.totalLossDb(
          CableLossScreen.cableLossPer100ft('LMR-400', 2400)!,
          CableLossScreen.lengthToFeet(10, CableLengthUnit.m),
        ),
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    test('A5 frequency unit path — 2.4 GHz must equal 2400 MHz', () {
      expect(
        CableLossScreen.freqToMHz(2.4, CableFreqUnit.ghz),
        closeTo(2400, 1e-9),
        reason: 'GHz→MHz normalizer',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A7 — NOISE FLOOR (kTB)
  // Vectors are stated at T = 290 K. The app takes °C, so 290 K = 16.85 °C.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A7 Noise floor — kTB at 290 K', () {
    const double t290 = 290.0 - 273.15; // = 16.85 °C

    void bw(String id, double mhz, double expected) {
      test('$id  ${mhz.toStringAsFixed(0)} MHz, NF = 0', () {
        expectVector(
          id: id,
          tool: 'Noise Floor',
          input: 'B = ${mhz.toStringAsFixed(0)} MHz, T = 290 K, NF = 0 dB',
          expected: expected,
          actual: NoiseFloorScreen.thermalDbm(mhz, t290),
          tolerance: 0.1,
          unit: 'dBm',
          trap: 'B in MHz instead of Hz = 60 dB error',
        );
      });
    }

    bw('A7-1', 20, -100.965);
    bw('A7-2', 40, -97.954);
    bw('A7-3', 80, -94.944);
    bw('A7-4', 160, -91.934);
    bw('A7-5', 320, -88.924);

    test('A7-6  20 MHz, NF = 6 dB', () {
      expectVector(
        id: 'A7-6',
        tool: 'Noise Floor',
        input: 'B = 20 MHz, T = 290 K, NF = 6 dB',
        expected: -94.965,
        actual: NoiseFloorScreen.rxFloorDbm(20, t290, 6),
        tolerance: 0.1,
        unit: 'dBm',
        trap: 'noise figure ADDS in dB, it does not multiply',
      );
    });

    test('A7-7  1 Hz — the −173.975 dBm/Hz anchor', () {
      expectVector(
        id: 'A7-7',
        tool: 'Noise Floor',
        input: 'B = 1 Hz (1e-6 MHz), T = 290 K, NF = 0 dB',
        expected: -173.975,
        actual: NoiseFloorScreen.thermalDbm(1e-6, t290),
        tolerance: 0.1,
        unit: 'dBm',
      );
    });

    test('A7-1 via the "rule of thumb" row (hardcoded −174)', () {
      expectVector(
        id: 'A7-1 (rule of thumb)',
        tool: 'Noise Floor',
        input: 'B = 20 MHz, rule-of-thumb row',
        expected: -100.965,
        actual: NoiseFloorScreen.ruleOfThumbDbm(20),
        tolerance: 0.1,
        unit: 'dBm',
      );
    });

    test('A7-1 at the app\'s DEFAULT temperature (20 °C, not 290 K)', () {
      // The screen defaults a blank temperature field to 20 °C = 293.15 K,
      // not the 290 K convention the vectors use. Does it still land inside
      // the vector's ±0.1 dB?
      expectVector(
        id: 'A7-1 (app default 20 °C)',
        tool: 'Noise Floor',
        input: 'B = 20 MHz, T = app default ${NoiseFloorScreen.defaultTempC} °C',
        expected: -100.965,
        actual: NoiseFloorScreen.thermalDbm(20, NoiseFloorScreen.defaultTempC),
        tolerance: 0.1,
        unit: 'dBm',
        trap: 'the app defaults to 293.15 K; the standard convention is 290 K',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A8 — WAVELENGTH
  // The app's Wavelength screen uses c = 300 (i.e. 3e8 m/s), not 299.792458.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A8 Wavelength — λ = c/f, c = 299 792 458 m/s', () {
    void wl(String id, double mhz, double expected, {String note = ''}) {
      test('$id  f = ${mhz.toStringAsFixed(0)} MHz', () {
        expectVector(
          id: id,
          tool: 'Wavelength',
          input: 'f = ${mhz.toStringAsFixed(0)} MHz',
          expected: expected,
          actual: WavelengthScreen.wavelengthMeters(mhz),
          tolerance: 0.0001,
          unit: 'm',
          trap: note,
        );
      });
    }

    wl('A8-1', 2400, 0.1249135);
    wl('A8-2', 2437, 0.1230170, note: '2.4 GHz ch 6 centre');
    wl('A8-3', 5180, 0.0578750, note: '5 GHz ch 36 centre');
    wl('A8-4', 5955, 0.0503430, note: '6 GHz ch 1 centre');

    test('A8-5  f = 1 GHz  [the c = 3e8 fingerprint]', () {
      expectVector(
        id: 'A8-5',
        tool: 'Wavelength',
        input: 'f = 1 GHz (via the GHz unit toggle)',
        expected: 0.2997925,
        actual: WavelengthScreen.wavelengthMeters(
          WavelengthScreen.freqToMHz(1, WlFreqUnit.ghz),
        ),
        tolerance: 0.0001,
        unit: 'm',
        trap: 'if the app returns exactly 0.3 m it hardcoded c = 3e8 '
            '(0.07% high — immaterial in practice, but a fingerprint)',
      );
    });

    test('A8-1 in cm', () {
      expectVector(
        id: 'A8-1 (cm)',
        tool: 'Wavelength',
        input: 'f = 2400 MHz → cm',
        expected: 12.4914,
        actual: WavelengthScreen.wavelengthCm(2400),
        tolerance: 0.01,
        unit: 'cm',
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A9 — ANTENNA ELEMENT LENGTH
  // The Antenna Length screen uses c = 299.792458 (unlike the Wavelength
  // screen's 300). Free-space vectors A9-1..3 are EXACT; A9-4..6 apply the
  // 0.95 convention, which is a convention and not a constant (see the
  // honesty audit in the report).
  // ═════════════════════════════════════════════════════════════════════════
  group('§A9 Antenna length', () {
    test('A9-1  2400 MHz, λ/4, no correction', () {
      expectVector(
        id: 'A9-1',
        tool: 'Antenna Length',
        input: 'f = 2400 MHz, λ/4, VF = 1.0 (no correction)',
        expected: 3.1228,
        actual:
            AntennaLengthScreen.quarterWaveMeters(
              AntennaLengthScreen.wavelengthMeters(2400),
              1.0,
            ) *
            100,
        tolerance: 0.001,
        unit: 'cm',
      );
    });

    test('A9-2  2400 MHz, λ/2, no correction', () {
      expectVector(
        id: 'A9-2',
        tool: 'Antenna Length',
        input: 'f = 2400 MHz, λ/2, VF = 1.0',
        expected: 6.2457,
        actual:
            AntennaLengthScreen.halfWaveDipoleMeters(
              AntennaLengthScreen.wavelengthMeters(2400),
              1.0,
            ) *
            100,
        tolerance: 0.001,
        unit: 'cm',
      );
    });

    test('A9-3  2437 MHz, λ/4, no correction', () {
      expectVector(
        id: 'A9-3',
        tool: 'Antenna Length',
        input: 'f = 2437 MHz (ch 6 centre), λ/4, VF = 1.0',
        expected: 3.0754,
        actual:
            AntennaLengthScreen.quarterWaveMeters(
              AntennaLengthScreen.wavelengthMeters(2437),
              1.0,
            ) *
            100,
        tolerance: 0.001,
        unit: 'cm',
      );
    });

    test('A9-4  2400 MHz, λ/4 × 0.95', () {
      expectVector(
        id: 'A9-4',
        tool: 'Antenna Length',
        input: 'f = 2400 MHz, λ/4, VF = 0.95 (the app\'s prefilled default)',
        expected: 2.9667,
        actual:
            AntennaLengthScreen.quarterWaveMeters(
              AntennaLengthScreen.wavelengthMeters(2400),
              0.95,
            ) *
            100,
        tolerance: 0.01,
        unit: 'cm',
      );
    });

    test('A9-5  2400 MHz, λ/2 × 0.95', () {
      expectVector(
        id: 'A9-5',
        tool: 'Antenna Length',
        input: 'f = 2400 MHz, λ/2, VF = 0.95',
        expected: 5.9334,
        actual:
            AntennaLengthScreen.halfWaveDipoleMeters(
              AntennaLengthScreen.wavelengthMeters(2400),
              0.95,
            ) *
            100,
        tolerance: 0.01,
        unit: 'cm',
      );
    });

    test('A9-6  468/f must agree with 0.95 × λ/2 to within 0.02 cm', () {
      final double ruleCm =
          AntennaLengthScreen.feetToMeters(
            AntennaLengthScreen.dipoleRuleOfThumbFeet(2400),
          ) *
          100;
      expectVector(
        id: 'A9-6',
        tool: 'Antenna Length',
        input: '468 / 2400 MHz → cm',
        expected: 5.9436,
        actual: ruleCm,
        tolerance: 0.01,
        unit: 'cm',
      );
      // The consistency proof: 468/f and 0.95·λ/2 are the same rule.
      final double vfCm =
          AntennaLengthScreen.halfWaveDipoleMeters(
            AntennaLengthScreen.wavelengthMeters(2400),
            0.95,
          ) *
          100;
      expect(
        (ruleCm - vfCm).abs(),
        lessThan(0.02),
        reason: 'A9-6: 468/f (${ruleCm.toStringAsFixed(4)} cm) and 0.95×λ/2 '
            '(${vfCm.toStringAsFixed(4)} cm) must be the same rule wearing '
            'different clothes (within 0.02 cm)',
      );
    });

    test('A9 input routing — GHz path and wavelength-mode inversion', () {
      // Extracted from the screen's private State getters so the mode/unit
      // routing is testable. 2.4 GHz must resolve to the same 2400 MHz.
      expectVector(
        id: 'A9-1 (GHz input path)',
        tool: 'Antenna Length',
        input: 'value = 2.4, unit = GHz, frequency mode',
        expected: 2400,
        actual: AntennaLengthScreen.resolveFreqMHz(
          value: 2.4,
          wavelengthMode: false,
          freqUnit: AntennaFreqUnit.ghz,
        )!,
        tolerance: 1e-9,
        unit: 'MHz',
      );
      // Wavelength mode: feeding back λ(2400 MHz) must return 2400 MHz.
      expectVector(
        id: 'A9-1 (wavelength-mode round trip)',
        tool: 'Antenna Length',
        input: 'value = λ(2400 MHz) = 0.1249135 m, wavelength mode',
        expected: 2400,
        actual: AntennaLengthScreen.resolveFreqMHz(
          value: AntennaLengthScreen.wavelengthMeters(2400),
          wavelengthMode: true,
          freqUnit: AntennaFreqUnit.mhz,
        )!,
        tolerance: 1e-6,
        unit: 'MHz',
      );
      // The VF gate: (0, 1] only.
      expect(AntennaLengthScreen.resolveVf(0.95), 0.95);
      expect(AntennaLengthScreen.resolveVf(1.0), 1.0);
      expect(AntennaLengthScreen.resolveVf(1.01), isNull);
      expect(AntennaLengthScreen.resolveVf(0), isNull);
      expect(AntennaLengthScreen.resolveVf(null), isNull);
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A10 — DOWNTILT
  // The app computes atan(height / coverage). It has NO client-height field,
  // so the height input must already be Δh. Vectors are fed Δh accordingly.
  // The app has no angle→radius inverse, so A10-3/A10-4 are asserted in the
  // forward direction using the vectors' own numbers (same equation).
  // ═════════════════════════════════════════════════════════════════════════
  group('§A10 Downtilt — geometric (boresight) convention', () {
    test('A10-1  h_AP 8 m, h_client 1.5 m, r 20 m  (Δh = 6.5)', () {
      expectVector(
        id: 'A10-1',
        tool: 'Downtilt',
        input: 'Δh = 6.5 m (8 − 1.5), r = 20 m',
        expected: 18.0041,
        actual: DowntiltScreen.downtiltDeg(6.5, 20),
        tolerance: 0.01,
        unit: '°',
        trap: 'the app has no client-height field — using h_AP (8 m) instead '
            'of Δh over-tilts to 21.80°',
      );
    });

    test('A10-2  h_AP 10 m, h_client 0, r 30 m', () {
      expectVector(
        id: 'A10-2',
        tool: 'Downtilt',
        input: 'Δh = 10 m, r = 30 m',
        expected: 18.4349,
        actual: DowntiltScreen.downtiltDeg(10, 30),
        tolerance: 0.01,
        unit: '°',
      );
    });

    test('A10-3  Δh 6.5 m, r 36.865 m → 10°  [inverted: app has no r() API]',
        () {
      expectVector(
        id: 'A10-3 (inverted)',
        tool: 'Downtilt',
        input: 'Δh = 6.5 m, r = 36.865 m (the vector\'s own radius)',
        expected: 10.0,
        actual: DowntiltScreen.downtiltDeg(6.5, 36.865),
        tolerance: 0.01,
        unit: '°',
      );
    });

    test('A10-4  Δh 3 m, r 3 m → 45°  [the degrees/radians catcher]', () {
      expectVector(
        id: 'A10-4 (inverted)',
        tool: 'Downtilt',
        input: 'Δh = 3 m, r = 3 m',
        expected: 45.0,
        actual: DowntiltScreen.downtiltDeg(3, 3),
        tolerance: 0.001,
        unit: '°',
        trap: 'a missing rad→deg conversion returns 0.7854 here',
      );
    });

    test('A10 unit paths — ft and km normalizers', () {
      expect(
        DowntiltScreen.heightToMeters(1, HeightUnit.ft),
        closeTo(0.3048, 1e-12),
        reason: '1 ft = 0.3048 m exactly (NIST SP 811)',
      );
      expect(
        DowntiltScreen.coverageToMeters(1, CoverageUnit.km),
        closeTo(1000, 1e-9),
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A11 — EARTH CURVATURE / BULGE
  // The app implements the MIDPOINT form only: h = D²·1000 / (8·R·k).
  // It has no d1/d2 input, so the off-centre vector A11-4 is NOT RUNNABLE.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A11 Earth bulge — ITU-R P.530-18', () {
    test('A11-1  D = 10 km, k = 4/3', () {
      expectVector(
        id: 'A11-1',
        tool: 'Earth Curvature',
        input: 'd1 = d2 = 5 km (D = 10 km), k = 4/3',
        expected: 1.4706,
        actual: ec.EarthCurvatureScreen.bulgeMeters(
          10,
          ec.KFactor.fourThirds.value,
        ),
        tolerance: pctTol(1.4706, 0.5),
        unit: 'm',
      );
    });

    test('A11-2  D = 50 km, k = 4/3', () {
      expectVector(
        id: 'A11-2',
        tool: 'Earth Curvature',
        input: 'd1 = d2 = 25 km (D = 50 km), k = 4/3',
        expected: 36.765,
        actual: ec.EarthCurvatureScreen.bulgeMeters(
          50,
          ec.KFactor.fourThirds.value,
        ),
        tolerance: pctTol(36.765, 0.5),
        unit: 'm',
      );
    });

    test('A11-3  D = 50 km, k = 1 (true earth)  [the k-factor test]', () {
      expectVector(
        id: 'A11-3',
        tool: 'Earth Curvature',
        input: 'd1 = d2 = 25 km (D = 50 km), k = 1.0',
        expected: 49.020,
        actual: ec.EarthCurvatureScreen.bulgeMeters(
          50,
          ec.KFactor.geometric.value,
        ),
        tolerance: pctTol(49.020, 0.5),
        unit: 'm',
        trap: 'if this equals A11-2 the tool is ignoring k entirely',
      );
    });

    test('A11-2 vs A11-3 — k must actually change the answer', () {
      final double k43 = ec.EarthCurvatureScreen.bulgeMeters(
        50,
        ec.KFactor.fourThirds.value,
      );
      final double k1 = ec.EarthCurvatureScreen.bulgeMeters(
        50,
        ec.KFactor.geometric.value,
      );
      expect(
        k1 / k43,
        closeTo(4 / 3, 0.01),
        reason: 'A11-2/A11-3: bulge(k=1)/bulge(k=4/3) must be 4/3. Got '
            '${(k1 / k43).toStringAsFixed(4)}. If this is 1.0 the tool '
            'ignores k and mis-predicts every long path by 33%.',
      );
    });

    test('A11-4  d1 = 10 km, d2 = 40 km, D = 50 km, k = 4/3 → 23.529 m', () {
      // Left here on purpose so the vector is visible in the suite.
    }, skip: 'NOT RUNNABLE — Earth Curvature has no d1/d2 input. It computes '
        'bulge at the MIDPOINT only (bulgeMeters(distKm, k)). For D = 50 km it '
        'returns the midpoint bulge (~36.8 m) regardless of where the obstacle '
        'actually is; the vector\'s off-centre answer is 23.529 m. The app '
        'cannot express this question. Reported as a coverage gap, not a bug.');
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A12 — ITU RAIN FADE                                          [FAILING]
  //
  // The vectors carry ITU-R P.838-3 (2005) Table 5 coefficients. The table
  // comparison below localizes the disagreement precisely.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A12 Rain fade — ITU-R P.838-3  [FAILING]', () {
    test('A12-1  5 GHz, H pol, R = 50 mm/h', () {
      expectVector(
        id: 'A12-1',
        tool: 'Rain Fade',
        input: 'f = 5 GHz, horizontal, R = 50 mm/h',
        expected: 0.16513,
        actual: rf.RainFadeScreen.specificAttenuation(
          5,
          50,
          rf.Polarization.horizontal,
        ),
        tolerance: pctTol(0.16513, 0.5),
        unit: 'dB/km',
      );
    });

    test('A12-2  6 GHz, H pol, R = 50 mm/h', () {
      expectVector(
        id: 'A12-2',
        tool: 'Rain Fade',
        input: 'f = 6 GHz, horizontal, R = 50 mm/h',
        expected: 0.35475,
        actual: rf.RainFadeScreen.specificAttenuation(
          6,
          50,
          rf.Polarization.horizontal,
        ),
        tolerance: pctTol(0.35475, 0.5),
        unit: 'dB/km',
      );
    });

    test('A12-3  10 GHz, H pol, R = 50 mm/h', () {
      expectVector(
        id: 'A12-3',
        tool: 'Rain Fade',
        input: 'f = 10 GHz, horizontal, R = 50 mm/h',
        expected: 1.66363,
        actual: rf.RainFadeScreen.specificAttenuation(
          10,
          50,
          rf.Polarization.horizontal,
        ),
        tolerance: pctTol(1.66363, 0.5),
        unit: 'dB/km',
      );
    });

    test('A12-4  20 GHz, H pol, R = 25 mm/h', () {
      expectVector(
        id: 'A12-4',
        tool: 'Rain Fade',
        input: 'f = 20 GHz, horizontal, R = 25 mm/h',
        expected: 2.75077,
        actual: rf.RainFadeScreen.specificAttenuation(
          20,
          25,
          rf.Polarization.horizontal,
        ),
        tolerance: pctTol(2.75077, 0.5),
        unit: 'dB/km',
      );
    });

    test('A12-6  10 GHz, V pol, R = 50 mm/h', () {
      expectVector(
        id: 'A12-6',
        tool: 'Rain Fade',
        input: 'f = 10 GHz, vertical, R = 50 mm/h',
        expected: 1.51306,
        actual: rf.RainFadeScreen.specificAttenuation(
          10,
          50,
          rf.Polarization.vertical,
        ),
        tolerance: pctTol(1.51306, 0.5),
        unit: 'dB/km',
      );
    });

    test('A12-5  10 GHz, CIRCULAR pol (τ = 45°), R = 50 mm/h → 1.59736 dB/km',
        () {
      // Left here on purpose so the vector is visible in the suite.
    }, skip: 'NOT RUNNABLE — the app\'s Polarization enum is {horizontal, '
        'vertical} only. ITU-R P.838-3 eqs. (4)/(5) give circular via τ = 45° '
        '(k = (kH+kV)/2). The app cannot express circular polarization.');

    // ── Localize the failure: compare the app's coefficient table directly
    //    against ITU-R P.838-3 Table 5 as transcribed in REFERENCE-VECTORS.md.
    //    Only the frequencies present in BOTH tables are compared.
    test('A12 COEFFICIENT TABLE vs ITU-R P.838-3 Table 5', () {
      // f, kH, alphaH, kV, alphaV — verbatim from REFERENCE-VECTORS.md §A12.
      const List<List<double>> p838_3 = <List<double>>[
        <double>[2, 0.0000847, 1.0664, 0.0000998, 0.9490],
        <double>[6, 0.0007056, 1.5900, 0.0004878, 1.5728],
        <double>[10, 0.01217, 1.2571, 0.01129, 1.2156],
        <double>[15, 0.04481, 1.1233, 0.05008, 1.0440],
        <double>[20, 0.09164, 1.0568, 0.09611, 0.9847],
        <double>[30, 0.2403, 0.9485, 0.2291, 0.9129],
        <double>[40, 0.4431, 0.8673, 0.4274, 0.8421],
      ];

      // Accumulate EVERY mismatch and report the whole table at once. A
      // measurement task wants the full picture, not the first tripwire.
      final List<String> rows = <String>[];
      int mismatches = 0;

      void cmp(String f, String coeff, double expected, double actual) {
        final double delta = actual - expected;
        final double pc = delta / expected.abs() * 100;
        final bool ok = delta.abs() <= pctTol(expected, 0.5);
        if (!ok) mismatches++;
        rows.add(
          '  ${ok ? 'ok  ' : 'FAIL'}  ${f.padLeft(3)} GHz  ${coeff.padRight(4)}'
          '  P.838-3: ${expected.toString().padRight(11)}'
          '  app: ${actual.toStringAsPrecision(5).padRight(11)}'
          '  ${pc >= 0 ? '+' : ''}${pc.toStringAsFixed(1)}%',
        );
      }

      for (final List<double> row in p838_3) {
        final double f = row[0];
        // Destructure the app's records, exactly as the app's own code does.
        final (double kH, double alphaH) = rf.RainFadeScreen.interpolateITU(
          f,
          rf.Polarization.horizontal,
        );
        final (double kV, double alphaV) = rf.RainFadeScreen.interpolateITU(
          f,
          rf.Polarization.vertical,
        );
        final String fs = f.toStringAsFixed(0);
        cmp(fs, 'k_H', row[1], kH);
        cmp(fs, 'a_H', row[2], alphaH);
        cmp(fs, 'k_V', row[3], kV);
        cmp(fs, 'a_V', row[4], alphaV);
      }

      expect(
        mismatches,
        0,
        reason: <String>[
          '',
          '─────────────────────────────────────────────────────────────────',
          'REFERENCE VECTOR A12-T — Rain Fade coefficient table',
          'The app\'s `ituRain` table vs ITU-R P.838-3 (2005) Table 5, at the '
              '7 frequencies present in both.',
          'Tolerance ±0.5% of the Recommendation\'s value.',
          '',
          ...rows,
          '',
          '  $mismatches of ${rows.length} coefficients disagree.',
          '',
          '  The app\'s header comment and the tool title both say '
              '"ITU-R P.838-3".',
          '  The expected column is GROUND TRUTH. Do not edit it. Report the '
              'disagreement.',
          '─────────────────────────────────────────────────────────────────',
          '',
        ].join('\n'),
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A13 — POINT-TO-POINT (composite integration test)
  // ═════════════════════════════════════════════════════════════════════════
  group('§A13 PtP link — the 9-step integration vector', () {
    PtpResult run() => PtpLinkScreen.linkBudget(
      freqGHz: 5.8,
      distKm: 5,
      txPow: 20,
      txGain: 23,
      rxGain: 23,
      txLoss: 2.5, // 2 dB cable + 0.5 dB connectors
      rxLoss: 2.5,
      rainRateMmHr: 0,
      pol: PtpPolarization.horizontal,
      rxSens: -78,
      requiredMargin: 10,
    );

    test('A13 EIRP = 40.5 dBm', () {
      expectVector(
        id: 'A13 (EIRP)',
        tool: 'PtP Link',
        input: '20 dBm − 2.5 dB + 23 dBi',
        expected: 40.5,
        actual: run().eirp,
        tolerance: 0.05,
        unit: 'dBm',
      );
    });

    test('A13 FSPL = 121.6957 dB', () {
      expectVector(
        id: 'A13 (FSPL)',
        tool: 'PtP Link',
        input: 'f = 5.8 GHz, d = 5 km',
        expected: 121.6957,
        actual: run().fspl,
        tolerance: 0.05,
        unit: 'dB',
      );
    });

    test('A13 Prx = −60.6957 dBm', () {
      expectVector(
        id: 'A13 (Prx)',
        tool: 'PtP Link',
        input: 'EIRP 40.5 − FSPL + 23 dBi − 2.5 dB',
        expected: -60.6957,
        actual: run().rxLevel,
        tolerance: 0.05,
        unit: 'dBm',
      );
    });

    test('A13 fade margin = 17.3043 dB, verdict PASS', () {
      final PtpResult r = run();
      expectVector(
        id: 'A13 (margin)',
        tool: 'PtP Link',
        input: 'Prx − (−78 dBm)',
        expected: 17.3043,
        actual: r.margin,
        tolerance: 0.05,
        unit: 'dB',
      );
      expect(
        PtpLinkScreen.verdictFor(r.margin, 10),
        PtpVerdict.pass,
        reason: 'A13: 17.3 dB margin against a 10 dB requirement is a PASS',
      );
    });

    test('A13 F1 at the obstacle (d1 = 2 km, d2 = 3 km) = 7.8757 m', () {
      // 🟥 The number most likely to be wrong. The 8.657 bug returns 3.938 m.
      final double f1 = FresnelScreen.firstZoneRadius(
        freqGHz: 5.8,
        d1Meters: 2000,
        d2Meters: 3000,
      );
      expectVector(
        id: 'A13 (F1)',
        tool: 'Fresnel (via PtP scenario)',
        input: 'f = 5.8 GHz, d1 = 2 km, d2 = 3 km',
        expected: 7.8757,
        actual: f1,
        tolerance: 0.02,
        unit: 'm',
      );
      expectVector(
        id: 'A13 (60% F1)',
        tool: 'Fresnel (via PtP scenario)',
        input: '0.6 × F1',
        expected: 4.7254,
        actual: f1 * 0.6,
        tolerance: 0.02,
        unit: 'm',
      );
      expectNotTheBug(
        id: 'A13 [8.657 SENTINEL]',
        tool: 'Fresnel (via PtP scenario)',
        input: 'f = 5.8 GHz, d1 = 2 km, d2 = 3 km',
        actual: f1,
        bugValue: 3.938,
        tolerance: 0.02,
        bugName: 'would declare 2.36 m of clearance sufficient when 4.73 m is '
            'required',
        unit: 'm',
      );
    });

    test('A13 earth bulge at the obstacle = 0.3529 m, required clearance '
        '= 5.0783 m', () {
      // Left here on purpose so the vector is visible in the suite.
    }, skip: 'NOT RUNNABLE — two separate gaps. (1) Earth Curvature is '
        'midpoint-only, so the bulge at d1 = 2 km / d2 = 3 km cannot be asked. '
        '(2) PtpLinkScreen.linkBudget returns {eirp, fspl, rainFade, rxLevel, '
        'margin, pass} — it computes NO Fresnel and NO earth bulge, so the '
        'composite "required clearance above obstacle" the vector calls for is '
        'not produced anywhere in the app. This is Pax\'s "half-link tool" '
        'failure mode. Reported as a coverage gap, not a math bug.');
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A14 — THROUGHPUT / PHY RATE               (Pax trap #4: N_SD 242 vs 234)
  // ═════════════════════════════════════════════════════════════════════════
  group('§A14 PHY rate — IEEE 802.11  [trap #4: N_SD = 234, not 242]', () {
    void phy(
      String id,
      WifiStd std,
      int bw,
      int mcs,
      int ss,
      String gi,
      double expected,
      double tol,
    ) {
      test('$id  ${std.name.toUpperCase()} MCS$mcs, $bw MHz, $ss SS, $gi µs GI',
          () {
        expectVector(
          id: id,
          tool: 'Throughput (PHY rate)',
          input: '${std.name.toUpperCase()} MCS$mcs, $bw MHz, $ss SS, $gi µs GI',
          expected: expected,
          actual: ThroughputCalcScreen.phyRateMbps(
            std: std,
            bandwidthMHz: bw,
            mcs: mcs,
            streams: ss,
            giKey: gi,
          )!,
          tolerance: tol,
          unit: 'Mb/s',
        );
      });
    }

    phy('A14-1', WifiStd.ht, 20, 7, 1, '0.8', 65.0, 0.1);
    phy('A14-2', WifiStd.ht, 20, 7, 1, '0.4', 72.2, 0.1);
    phy('A14-3', WifiStd.vht, 80, 9, 1, '0.8', 390.0, 0.1);
    phy('A14-4', WifiStd.vht, 80, 9, 1, '0.4', 433.3, 0.1);
    phy('A14-5', WifiStd.he, 20, 11, 1, '0.8', 143.4, 0.1);
    phy('A14-6', WifiStd.he, 40, 11, 1, '0.8', 286.8, 0.1);
    phy('A14-7', WifiStd.he, 160, 11, 8, '0.8', 9607.8, 1.0);
    phy('A14-8', WifiStd.he, 20, 0, 1, '3.2', 7.3, 0.1);
    phy('A14-9', WifiStd.eht, 320, 13, 8, '0.8', 23058.8, 2.0);

    test('802.11ac canonical maximum — VHT MCS9, 160 MHz, 8 SS, 0.4 µs', () {
      expectVector(
        id: 'A14 (11ac max)',
        tool: 'Throughput (PHY rate)',
        input: 'VHT MCS9, 160 MHz, 8 SS, 0.4 µs GI',
        expected: 6933.3,
        actual: ThroughputCalcScreen.phyRateMbps(
          std: WifiStd.vht,
          bandwidthMHz: 160,
          mcs: 9,
          streams: 8,
          giKey: '0.4',
        )!,
        tolerance: 1.0,
        unit: 'Mb/s',
      );
    });

    test('N_SD table vs IEEE 802.11 Clause 27  [the 242/234 trap]', () {
      // HE/EHT: RU-242 has 242 TONES but only 234 DATA subcarriers.
      // The rate formula uses 234. A developer who reads "the 20 MHz RU has
      // 242 subcarriers" and plugs in 242 over-reports every HE rate by 3.4%.
      const Map<int, int> heExpected = <int, int>{
        20: 234,
        40: 468,
        80: 980,
        160: 1960,
      };
      heExpected.forEach((int bw, int nsd) {
        expectVectorInt(
          id: 'A14-NSD HE $bw MHz',
          tool: 'Throughput N_SD table',
          input: 'HE, $bw MHz',
          expected: nsd,
          actual: ThroughputCalcScreen.nsd[WifiStd.he]![bw],
        );
      });
      expectVectorInt(
        id: 'A14-NSD EHT 320 MHz',
        tool: 'Throughput N_SD table',
        input: 'EHT, 320 MHz',
        expected: 3920,
        actual: ThroughputCalcScreen.nsd[WifiStd.eht]![320],
      );
      const Map<int, int> vhtExpected = <int, int>{
        20: 52,
        40: 108,
        80: 234,
        160: 468,
      };
      vhtExpected.forEach((int bw, int nsd) {
        expectVectorInt(
          id: 'A14-NSD VHT $bw MHz',
          tool: 'Throughput N_SD table',
          input: 'VHT, $bw MHz',
          expected: nsd,
          actual: ThroughputCalcScreen.nsd[WifiStd.vht]![bw],
        );
      });
      // The trap sentinel — capable of failing, unlike expect(242, equals(242)).
      expect(
        ThroughputCalcScreen.nsd[WifiStd.he]![20],
        isNot(242),
        reason: 'TRAP #4: HE 20 MHz N_SD must be 234 (data subcarriers), not '
            '242 (total tones in RU-242 = 234 data + 8 pilot). 242 over-reports '
            'every HE rate by 3.4%.',
      );
    });

    test('reclamp is pure and never yields an invalid combination', () {
      // Extracted from _onStdChanged so the dependent-option logic is testable.
      // No reference vector covers the reclamp; this is a property check.
      for (final WifiStd from in WifiStd.values) {
        for (final WifiStd to in WifiStd.values) {
          for (final int bw in ThroughputCalcScreen.bandwidths[from]!) {
            for (final String gi in ThroughputCalcScreen.giKeys[from]!) {
              final ThroughputOptions o = ThroughputCalcScreen.reclampFor(
                std: to,
                bandwidthMHz: bw,
                mcs: ThroughputCalcScreen.maxMcs[from]!,
                streams: ThroughputCalcScreen.maxStreams[from]!,
                giKey: gi,
              );
              expect(
                ThroughputCalcScreen.phyRateMbps(
                  std: to,
                  bandwidthMHz: o.bandwidthMHz,
                  mcs: o.mcs,
                  streams: o.streams,
                  giKey: o.giKey,
                ),
                isNotNull,
                reason: 'reclamp ${from.name} → ${to.name} (bw $bw, gi $gi) '
                    'produced an invalid combination: $o',
              );
            }
          }
        }
      }
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A16 — PoE BUDGET                             🟥 Pax trap #2
  //
  // The app's PoE Budget is a generic Σ(watts × qty) against a user-entered
  // switch budget. It ships NO IEEE class table and NO cable-loss term — so
  // the double-count bug is structurally impossible, and so is any guardrail.
  // The A16-6 pair below is the finding.
  // ═════════════════════════════════════════════════════════════════════════
  group('§A16 PoE budget — IEEE 802.3bt  [trap #2: PSE-side vs PD-side watts]',
      () {
    test('A16-6  370 W switch, 12 × Class-4 APs at the PSE-side 30 W', () {
      final PoeBudgetResult r = PoeBudgetScreen.compute(370, <PoeDeviceRow>[
        const PoeDeviceRow(30.0, 12),
      ])!;
      expectVector(
        id: 'A16-6',
        tool: 'PoE Budget',
        input: '370 W budget, 12 × Class-4 AP @ 30.0 W (PSE min output)',
        expected: 360.0,
        actual: r.total,
        tolerance: 0.1,
        unit: 'W',
        trap: 'a switch PoE budget is spent in PSE-side watts, not PD-side',
      );
      expectVector(
        id: 'A16-6 (remaining)',
        tool: 'PoE Budget',
        input: '370 − 360',
        expected: 10.0,
        actual: r.remaining,
        tolerance: 0.1,
        unit: 'W',
      );
      expect(
        r.verdict,
        isNot(PoeVerdict.over),
        reason: 'A16-6: 360 W ≤ 370 W — the install fits, but only just',
      );
    });

    test('A16-6b  [DESIGN GAP CHARACTERIZATION] the same 12 APs entered at the '
        'PD-side 25.5 W', () {
      // This assertion documents the gap rather than proving correctness: the
      // app accepts PD-side watts with no guardrail and reports 64 W of
      // headroom that does not exist on the switch. 306 W is the number the
      // reference explicitly calls WRONG ("NOT 12 × 25.5 = 306 W").
      final PoeBudgetResult r = PoeBudgetScreen.compute(370, <PoeDeviceRow>[
        const PoeDeviceRow(25.5, 12),
      ])!;
      expect(
        r.total,
        closeTo(306.0, 0.1),
        reason: 'A16-6b: the app sums whatever watts the user types. Entering '
            'the IEEE class table\'s PD figure (25.5 W) yields 306 W — the '
            'number REFERENCE-VECTORS.md explicitly calls WRONG. The switch '
            'actually sees 360 W. The app offers no class picker and no '
            'PSE/PD guidance, so the user cannot tell which number the field '
            'wants. Copy/UX finding, not a math bug.',
      );
      // The harm, stated precisely: the headroom is overstated by 54 W.
      final PoeBudgetResult truth = PoeBudgetScreen.compute(370, <PoeDeviceRow>[
        const PoeDeviceRow(30.0, 12),
      ])!;
      expect(
        r.remaining - truth.remaining,
        closeTo(54.0, 0.1),
        reason: 'A16-6b: entering PD-side watts reports '
            '${r.remaining.toStringAsFixed(1)} W of headroom when the switch '
            'really has ${truth.remaining.toStringAsFixed(1)} W. That is 54 W '
            'of phantom headroom — enough to talk someone into adding two more '
            'Class-4 APs to a switch that cannot carry them.',
      );
    });

    test('A16-7  370 W switch, 8 × Class-6 APs at the PSE-side 60 W', () {
      final PoeBudgetResult r = PoeBudgetScreen.compute(370, <PoeDeviceRow>[
        const PoeDeviceRow(60.0, 8),
      ])!;
      expectVector(
        id: 'A16-7',
        tool: 'PoE Budget',
        input: '370 W budget, 8 × Class-6 AP @ 60.0 W',
        expected: 480.0,
        actual: r.total,
        tolerance: 0.1,
        unit: 'W',
      );
      expect(
        r.verdict,
        PoeVerdict.over,
        reason: 'A16-7: 480 W > 370 W — INSUFFICIENT',
      );
      // The vector states the max is 6 APs.
      expect(
        PoeBudgetScreen.compute(370, <PoeDeviceRow>[
          const PoeDeviceRow(60.0, 6),
        ])!.verdict,
        isNot(PoeVerdict.over),
        reason: 'A16-7: 6 × 60 = 360 W ≤ 370 W fits',
      );
      expect(
        PoeBudgetScreen.compute(370, <PoeDeviceRow>[
          const PoeDeviceRow(60.0, 7),
        ])!.verdict,
        PoeVerdict.over,
        reason: 'A16-7: 7 × 60 = 420 W > 370 W does not',
      );
    });

    // ── The class table IS in the app — as two rendered reference cards
    //    (`_classesCard`, `_standardsCard`), not as computable data. That is
    //    exactly what poe_budget_screen_test.dart's two tautologies were
    //    *trying* to guard ("this test documents the canonical value") and
    //    could not, because they compare a literal to itself. These pump the
    //    real screen and read the real rendered strings.

    testWidgets('A16-2  Class 8 PD = 71.3 W — the tautology, done for real', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MaterialApp(theme: AppTheme.dark(), home: const PoeBudgetScreen()),
      );
      await tester.pumpAndSettle();

      expect(
        find.text('71.3 W', skipOffstage: false),
        findsWidgets,
        reason: 'A16-2: IEEE 802.3bt Class 8 PD max average power = 71.3 W. '
            'This assertion reads the rendered card. Contrast '
            'poe_budget_screen_test.dart:111 — expect(71.3, closeTo(71.3, '
            '1e-9)) — which would still pass if the card said 7.13 W.',
      );
    });

    testWidgets('A16-1  Class 4 PD = 25.5 W — the second tautology, for real', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MaterialApp(theme: AppTheme.dark(), home: const PoeBudgetScreen()),
      );
      await tester.pumpAndSettle();

      expect(
        find.text('25.5 W', skipOffstage: false),
        findsWidgets,
        reason: 'A16-1: IEEE 802.3at Class 4 PD max = 25.5 W (reads the '
            'rendered card). Contrast poe_budget_screen_test.dart:115.',
      );
    });

    testWidgets('A16-6  🟥 the PSE-side watts must be VISIBLE somewhere', (
      WidgetTester tester,
    ) async {
      // THE HEADLINE FINDING.
      //
      // `_standardsCard` holds [standard, name, PSE W, PD W] but its Row
      // renders row[0], row[1], row[3] — row[2], the PSE column, is dropped.
      // So the app carries 15.4 / 30.0 / 60.0 / 100.0 W in its source and
      // displays NONE of them, while the classes card prominently shows the
      // PD watts (12.95 / 25.5 / 51.0 / 71.3) and the card's own caption
      // correctly says "PD W is the power available at the device (after
      // cable loss)."
      //
      // A switch's PoE budget is spent in PSE-side watts. The app shows the
      // user only the post-cable-loss column and then asks them to fill a
      // switch-budget field — leading them straight into A16-6b (306 W for
      // 12 Class-4 APs that really cost the switch 360 W).
      await tester.pumpWidget(
        MaterialApp(theme: AppTheme.dark(), home: const PoeBudgetScreen()),
      );
      await tester.pumpAndSettle();

      const Map<String, String> pseWatts = <String, String>{
        'Class 3 / Type 1 (802.3af)': '15.4 W',
        'Class 4 / Type 2 (802.3at)': '30.0 W',
        'Class 6 / Type 3 (802.3bt)': '60.0 W',
      };

      final List<String> missing = <String>[];
      pseWatts.forEach((String label, String w) {
        if (find.text(w, skipOffstage: false).evaluate().isEmpty) {
          missing.add('  $label → PSE supplies "$w" — NOT RENDERED ANYWHERE');
        }
      });

      expect(
        missing,
        isEmpty,
        reason: <String>[
          '',
          '─────────────────────────────────────────────────────────────────',
          'REFERENCE VECTOR A16-6 — PoE Budget, PSE-side watts',
          '',
          ...missing,
          '',
          '  The switch budget is consumed in PSE-side watts. The app renders',
          '  ONLY the PD-side column (25.5 / 51.0 / 71.3 W) and drops the PSE',
          '  column (row[2]) on the floor — the data is in the source and never',
          '  reaches the screen.',
          '',
          '  A user who reads the app\'s own reference cards will budget a',
          '  Class-4 AP at 25.5 W. Twelve of them come to 306 W against a 370 W',
          '  switch — "plenty of headroom". The switch actually sees 360 W.',
          '',
          '  This is a rendering/copy defect, not a math bug. Reported, not',
          '  fixed. Do not edit these expectations.',
          '─────────────────────────────────────────────────────────────────',
          '',
        ].join('\n'),
      );
    });

    testWidgets('A16 FULL CLASS TABLE vs IEEE 802.3 (rendered card)', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MaterialApp(theme: AppTheme.dark(), home: const PoeBudgetScreen()),
      );
      await tester.pumpAndSettle();

      // PD max average power at the PD PI, per REFERENCE-VECTORS.md §A16.
      const Map<String, String> pdWatts = <String, String>{
        '0': '13.0 W',
        '1': '3.84 W',
        '2': '6.49 W',
        '3': '12.95 W',
        '4': '25.5 W',
        '5': '40.0 W',
        '6': '51.0 W',
        '7': '62.0 W',
        '8': '71.3 W',
      };

      final List<String> missing = <String>[];
      pdWatts.forEach((String cls, String w) {
        if (find.text(w, skipOffstage: false).evaluate().isEmpty) {
          missing.add('  Class $cls → expected "$w" — NOT RENDERED');
        }
      });

      expect(
        missing,
        isEmpty,
        reason: <String>[
          '',
          'REFERENCE VECTOR A16 (class table) — PoE Budget reference card',
          'PD max average power per IEEE 802.3 class (REFERENCE-VECTORS §A16):',
          '',
          ...missing,
          '',
          'Every value above is GROUND TRUTH. Do not edit it.',
          '',
        ].join('\n'),
      );
    });

    testWidgets('A16-2  Type 4 PSE minimum output = 90.0 W', (
      WidgetTester tester,
    ) async {
      await tester.pumpWidget(
        MaterialApp(theme: AppTheme.dark(), home: const PoeBudgetScreen()),
      );
      await tester.pumpAndSettle();

      expect(
        find.text('90.0 W', skipOffstage: false),
        findsWidgets,
        reason: '\nREFERENCE VECTOR A16-2 — PoE standards card\n'
            '  expected : the Type 4 / Class 8 PSE supplies 90.0 W at the PSE '
            'PI\n'
            '  ground truth: REFERENCE-VECTORS.md §A16 canonical class table, '
            'reverse-derived\n'
            '  from P_PD = P_PSE − I²R and confirmed on all 8 classes '
            '(90.0 − 18.72 = 71.3 ✓).\n'
            '  The PSE-side watt is the number a user must put in the budget '
            'field.\n'
            '  Do not edit this expectation to match the card.\n',
      );
    });

    test('A16-3/4/5  cable loss I²R at Classes 4 / 6 / 8', () {
    }, skip: 'NOT RUNNABLE — the app has no cable-loss term (no length, no '
        'gauge, no loop-resistance input). GOOD NEWS: this means Pax\'s trap #2 '
        '(double-counting cable loss the 802.3 class table already subtracted) '
        'is structurally impossible here — there is nothing to double-count.');
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §A17 — CHANNEL ↔ FREQUENCY                          (Pax trap #5)
  // ═════════════════════════════════════════════════════════════════════════
  group('§A17 Channel ↔ frequency — IEEE 802.11-2020 Annex E  [trap #5]', () {
    void ch(String id, WifiBand band, int channel, int expected,
        {String trap = ''}) {
      test('$id  ${band.name} ch $channel', () {
        expectVectorInt(
          id: id,
          tool: 'Channel/Frequency Converter',
          input: '${band.name}, channel $channel',
          expected: expected,
          actual: channelToFrequency(band, channel),
          unit: 'MHz',
          trap: trap,
        );
      });
    }

    ch('A17-1', WifiBand.band24, 1, 2412);
    ch('A17-2', WifiBand.band24, 6, 2437);
    ch('A17-3', WifiBand.band24, 11, 2462);
    ch('A17-4', WifiBand.band24, 13, 2472);
    ch('A17-5', WifiBand.band24, 14, 2484,
        trap: 'a blind 2407 + 5n returns 2477 — wrong by 7 MHz');
    ch('A17-6', WifiBand.band5, 36, 5180);
    ch('A17-7', WifiBand.band5, 100, 5500);
    ch('A17-8', WifiBand.band5, 165, 5825);
    ch('A17-9', WifiBand.band6, 1, 5955,
        trap: 'channel starting frequency is 5950, not 5945 or 5955');
    ch('A17-10', WifiBand.band6, 2, 5935,
        trap: 'ch 2 uses a DIFFERENT start (5925) and sits BELOW ch 1. '
            'A monotonic 5950 + 5n returns 5960 — wrong by 25 MHz');
    ch('A17-11', WifiBand.band6, 37, 6135);
    ch('A17-12', WifiBand.band6, 233, 7115);

    test('A17-10 ordering — 6 GHz ch 2 must be BELOW ch 1', () {
      expect(
        channelToFrequency(WifiBand.band6, 2)!,
        lessThan(channelToFrequency(WifiBand.band6, 1)!),
        reason: 'A17-10: ch 2 (5935) sits below ch 1 (5955). Surprising, which '
            'is exactly why implementations get it wrong.',
      );
    });

    test('A17-13  reverse: 5955 MHz → 6 GHz ch 1, NOT 5 GHz ch 191', () {
      final ({WifiBand band, int channel})? r = frequencyToChannel(5955);
      expect(
        r,
        isNotNull,
        reason: 'A17-13: 5955 MHz must resolve to a channel',
      );
      expect(
        r!.band,
        WifiBand.band6,
        reason: 'A17-13: the reverse map is ambiguous without a band. '
            '(5955 − 5000)/5 = 191, so a naive 5 GHz reverse returns "ch 191".',
      );
      expectVectorInt(
        id: 'A17-13',
        tool: 'Channel/Frequency Converter',
        input: '5955 MHz → channel',
        expected: 1,
        actual: r.channel,
      );
    });

    test('A17-13b  reverse: 5935 and 2484 round-trip', () {
      final ({WifiBand band, int channel})? six = frequencyToChannel(5935);
      expect(six?.band, WifiBand.band6);
      expectVectorInt(
        id: 'A17-10 (reverse)',
        tool: 'Channel/Frequency Converter',
        input: '5935 MHz → channel',
        expected: 2,
        actual: six?.channel,
      );
      final ({WifiBand band, int channel})? two4 = frequencyToChannel(2484);
      expect(two4?.band, WifiBand.band24);
      expectVectorInt(
        id: 'A17-5 (reverse)',
        tool: 'Channel/Frequency Converter',
        input: '2484 MHz → channel',
        expected: 14,
        actual: two4?.channel,
      );
    });
  });

  // ═════════════════════════════════════════════════════════════════════════
  // §B5 — dBm ↔ mW ↔ W and the exact unit definitions
  // (Kept with Part A because it exercises the RF power converters.)
  // ═════════════════════════════════════════════════════════════════════════
  group('§B5 Power conversions — the 10·log10 vs 20·log10 trap', () {
    test('B5-1  0 dBm = 1 mW', () {
      expectVector(
        id: 'B5-1',
        tool: 'Unit Converter (power)',
        input: '0 dBm → mW',
        expected: 1.0,
        actual: appDbmToMw(0),
        tolerance: 0.0001,
        unit: 'mW',
      );
    });

    test('B5-2  20 dBm = 100 mW', () {
      expectVector(
        id: 'B5-2',
        tool: 'Unit Converter (power)',
        input: '20 dBm → mW',
        expected: 100.000,
        actual: appDbmToMw(20),
        tolerance: 0.001,
        unit: 'mW',
      );
    });

    test('B5-3  30 dBm = 1000 mW = 1 W', () {
      expectVector(
        id: 'B5-3',
        tool: 'Unit Converter (power)',
        input: '30 dBm → mW',
        expected: 1000.00,
        actual: appDbmToMw(30),
        tolerance: 0.01,
        unit: 'mW',
      );
      expectVector(
        id: 'B5-3 (W)',
        tool: 'Unit Converter (power)',
        input: '30 dBm → W',
        expected: 1.0,
        actual: UnitConversion.convert(
          30,
          UnitCategory.power,
          _unit(UnitCategory.power, 'dbm'),
          _unit(UnitCategory.power, 'w'),
        ),
        tolerance: 0.0001,
        unit: 'W',
      );
    });

    test('B5-4  23 dBm = 199.526 mW', () {
      expectVector(
        id: 'B5-4',
        tool: 'Unit Converter (power)',
        input: '23 dBm → mW',
        expected: 199.526,
        actual: appDbmToMw(23),
        tolerance: 0.001,
        unit: 'mW',
      );
    });

    test('B5-5  36 dBm = 3981.07 mW (the FCC 4 W EIRP limit)', () {
      expectVector(
        id: 'B5-5',
        tool: 'Unit Converter (power)',
        input: '36 dBm → mW',
        expected: 3981.07,
        actual: appDbmToMw(36),
        tolerance: 0.01,
        unit: 'mW',
      );
    });

    test('B5-6  100 mW = 20 dBm', () {
      expectVector(
        id: 'B5-6',
        tool: 'Unit Converter (power)',
        input: '100 mW → dBm',
        expected: 20.0,
        actual: appMwToDbm(100),
        tolerance: 0.0001,
        unit: 'dBm',
      );
    });

    test('B5-7  1 mW = 0 dBm', () {
      expectVector(
        id: 'B5-7',
        tool: 'Unit Converter (power)',
        input: '1 mW → dBm',
        expected: 0.0,
        actual: appMwToDbm(1),
        tolerance: 0.0001,
        unit: 'dBm',
      );
    });

    test('B5-8  −3 dBm = 0.501187 mW', () {
      expectVector(
        id: 'B5-8',
        tool: 'Unit Converter (power)',
        input: '−3 dBm → mW',
        expected: 0.501187,
        actual: appDbmToMw(-3),
        tolerance: 0.000001,
        unit: 'mW',
      );
    });

    test('B5-9  1 W = 30 dBm, NOT 0  [the W/mW trap]', () {
      expectVector(
        id: 'B5-9 (Unit Converter)',
        tool: 'Unit Converter (power)',
        input: '1 W → dBm',
        expected: 30.0,
        actual: UnitConversion.convert(
          1,
          UnitCategory.power,
          _unit(UnitCategory.power, 'w'),
          _unit(UnitCategory.power, 'dbm'),
        ),
        tolerance: 0.0001,
        unit: 'dBm',
        trap: 'feeding watts to a 10·log10(mW) function returns 0 dBm — a 1 W '
            'amplifier reads as 1 mW',
      );
      expectVector(
        id: 'B5-9 (Link Budget)',
        tool: 'Link Budget',
        input: '1 W → dBm via wattsTodBm',
        expected: 30.0,
        actual: LinkBudgetScreen.wattsTodBm(1.0),
        tolerance: 0.0001,
        unit: 'dBm',
      );
      expectVector(
        id: 'B5-9 (Link Budget TX unit toggle)',
        tool: 'Link Budget',
        input: 'TX power = 1, unit = W',
        expected: 30.0,
        actual: LinkBudgetScreen.txPowerToDbm(1.0, TxPowerUnit.w),
        tolerance: 0.0001,
        unit: 'dBm',
      );
    });

    test('B5 exact unit definitions (NIST SP 811)', () {
      expect(
        MetricConversionScreen.metersPerUnit(LengthUnit.ft),
        closeTo(0.3048, 1e-12),
        reason: 'B5: 1 ft = 0.3048 m EXACTLY, by definition',
      );
      expect(
        MetricConversionScreen.metersPerUnit(LengthUnit.mi),
        closeTo(1609.344, 1e-9),
        reason: 'B5: 1 mi = 1609.344 m EXACTLY (common wrong value: 1.6 km)',
      );
      expect(
        MetricConversionScreen.metersPerUnit(LengthUnit.nmi),
        closeTo(1852.0, 1e-9),
        reason: 'B5: 1 NM = 1852 m EXACTLY',
      );
      expect(
        MetricConversionScreen.metersPerUnit(LengthUnit.inch),
        closeTo(0.0254, 1e-12),
        reason: 'B5: 1 in = 2.54 cm EXACTLY',
      );
      expectVector(
        id: 'B5 (100 ft → m)',
        tool: 'Metric Conversion',
        input: '100 ft → m',
        expected: 30.48,
        actual: MetricConversionScreen.convert(
          100,
          LengthUnit.ft,
          LengthUnit.m,
        ),
        tolerance: 0.0001,
        unit: 'm',
      );
      expectVector(
        id: 'B5 (1 km → mi)',
        tool: 'Metric Conversion',
        input: '1 km → mi',
        expected: 0.621371,
        actual: MetricConversionScreen.convert(1, LengthUnit.km, LengthUnit.mi),
        tolerance: 0.000001,
        unit: 'mi',
      );
      expectVector(
        id: 'B5 (1 km → NM)',
        tool: 'Metric Conversion',
        input: '1 km → nautical miles',
        expected: 0.539957,
        actual: MetricConversionScreen.convert(
          1,
          LengthUnit.km,
          LengthUnit.nmi,
        ),
        tolerance: 0.000001,
        unit: 'NM',
      );
    });

    test('B5 the RF screens\' mile factor (1.60934) vs the exact 1.609344', () {
      // The RF screens inline 1.60934; the converters use the exact 1.609344.
      expectVector(
        id: 'B5 (FSPL mi→km)',
        tool: 'FSPL',
        input: '1 mi → km via FsplScreen.distToKm',
        expected: 1.609344,
        actual: FsplScreen.distToKm(1, DistUnit.mi),
        tolerance: 0.00001,
        unit: 'km',
        trap: 'the RF screens inline 1.60934 (5 dp) in 5 places; the unit '
            'converters use the exact 1.609344',
      );
    });
  });
}
