// Analog vs Digital, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   analog-vs-digital-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kAnalogVsDigitalLesson = GuidedLesson(
  toolId: 'analog-vs-digital-explained',
  route: '/tools/analog-vs-digital-explained',
  title: 'Analog vs Digital, Explained',
  guideTitle: 'Analog vs Digital, Explained',
  tagline: 'A plain-English guide',
  promise:
      'What the two words mean, and why your Wi-Fi slows down while your '
      'TV just freezes.',
  byline: <String>['Keith Parsons · CWNE #3', 'October 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/analog-vs-digital/cover.svg',
    width: 700,
    height: 240,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Analog keeps a smooth copy of something. Digital measures it '
          'again and again, and keeps only the numbers.',
        ),
        LessonText(
          'This guide answers three questions. What do the two words mean? '
          'Why does it matter to you? And what can you do when a picture '
          'freezes or Wi-Fi crawls?',
        ),
        LessonCallout.note(
          title: 'The one idea behind this guide',
          body:
              'Noise makes an analog signal worse a little at a time. A '
              'digital signal ignores noise until it can\'t, and then it '
              'fails all at once. Wi-Fi sits in between. It slows down '
              'in steps to stay connected.',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'A **signal** is anything that carries information, like a '
              'sound or a radio wave. A **bit** is a single 1 or 0, the '
              'smallest piece of digital data.',
        ),
      ],
    ),
    // ── 2. A smooth copy or a list of numbers ──────────────────────────────
    LessonStep(
      number: '2',
      title: 'A smooth copy or a list of numbers',
      blocks: <LessonBlock>[
        LessonLede(
          'Put a record on a turntable. The needle rides a groove cut in '
          'the shape of the sound. That\'s analog.',
        ),
        LessonText(
          'Now stream the same song. Your phone gets a file of numbers. '
          'Someone measured the sound over and over, fast, and wrote down '
          'each measurement. That\'s digital.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-01.svg',
          width: 784,
          height: 328,
          caption:
              '**Figure 1. A groove or a list of numbers.** A record '
              'keeps the shape of the sound. A phone keeps '
              'measurements of it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-02.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 2. The same sound, kept two ways.** The '
              'analog copy follows the wave everywhere. The digital '
              'copy keeps only the dots, and stores each dot as a '
              'number.',
        ),
        LessonText(
          'A CD measures the sound 44,100 times every second. That\'s fast '
          'enough that your ears can\'t tell the difference.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-03.svg',
          width: 784,
          height: 714,
          caption:
              '**Figure 3. More measurements make a closer copy.** '
              'Join the dots and you get the digital copy. With '
              'enough dots, it lands right on the real sound.',
        ),
      ],
    ),
    // ── 3. Why a digital copy doesn't fade ─────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Why a digital copy doesn\'t fade',
      blocks: <LessonBlock>[
        LessonLede(
          'Copy a cassette tape, then copy the copy. Each time, you get a '
          'little more hiss. Analog copies wear out.',
        ),
        LessonText(
          'A digital copy is just the same list of numbers. The computer '
          'checks every number, so the copy is exact. Your hundredth copy '
          'of a photo is as good as the first.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-04.svg',
          width: 784,
          height: 470,
          caption:
              '**Figure 4. Copies of copies.** Every tape copy adds a '
              'little hiss, but every digital copy is the same list '
              'of numbers. Read each row from left to right.',
        ),
        LessonText(
          'Your ears are still analog, and so are your speakers. So your '
          'phone turns the numbers back into a smooth wave before you hear '
          'it. It doesn\'t come out as a staircase.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-05.svg',
          width: 784,
          height: 442,
          caption:
              '**Figure 5. Analog at both ends, digital in the '
              'middle.** Sound is only numbers while it is stored or '
              'sent. Before the speaker plays it, the phone smooths '
              'the steps back into a wave.',
        ),
        LessonCallout.note(
          title: 'Files don\'t fade, but drives fail',
          body:
              'A digital file never wears out, but the phone or drive '
              'holding it can break. Keep two copies of anything you '
              'can\'t replace, in two different places.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-06.svg',
          width: 784,
          height: 208,
          caption:
              '**Figure 6. One copy can be lost. Two copies in two '
              'places are safer.** A cloud backup counts as a second '
              'place, but a delete on your phone can delete it there '
              'too.',
        ),
      ],
    ),
    // ── 4. Every radio wave is analog ──────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Every radio wave is analog',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi, your phone and digital TV all send digital data. But '
          'what leaves the antenna is always a smooth wave. Nothing flies '
          'through the air as ones and zeros.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-07.svg',
          width: 784,
          height: 200,
          caption:
              '**Figure 7. Only waves travel through the air.** The '
              'ones and zeros stay inside the router and the phone.',
        ),
        LessonText(
          'The sender starts with a steady wave. To send data, it changes '
          'the wave a little. It can change how tall the wave is, how fast '
          'it wiggles, or its timing.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-08.svg',
          width: 760,
          height: 344,
          caption:
              '**Figure 8. One wave, three ways to change it.** Each '
              'wave starts the same. After the dashed line, one thing '
              'changes. The receiver watches for those changes and '
              'reads them as numbers.',
        ),
        LessonText(
          'Wi-Fi changes the height and the timing at the same time. Each '
          'small change stands for a few bits. That\'s how a smooth wave '
          'carries your video.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-09.svg',
          width: 784,
          height: 608,
          caption:
              '**Figure 9. Each change in the wave stands for bits.** '
              'Here the height alone picks one of four patterns. Real '
              'Wi-Fi changes height and timing together, so each '
              'change carries more bits.',
        ),
      ],
    ),
    // ── 5. Three ways a signal fades ───────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Three ways a signal fades',
      blocks: <LessonBlock>[
        LessonLede(
          'Move away from the source, and every signal gets weaker. What '
          'you notice depends on the kind of signal.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-10.svg',
          width: 784,
          height: 400,
          caption:
              '**Figure 10. A slope, a cliff and a staircase.** Wi-Fi '
              'sits in between: it slows down in steps to stay '
              'connected. A sketch, not a measurement.',
        ),
        LessonText(
          '**Analog fades on a slope.** Old TV got snowy. FM radio gets '
          'more hiss the farther you drive.',
        ),
        LessonText(
          '**Digital TV drops off a cliff.** The picture looks perfect, '
          'right up until it freezes or disappears.',
        ),
        LessonText(
          '**Wi-Fi steps down a staircase.** As the signal weakens, Wi-Fi '
          'switches to a simpler, slower way of sending. It only drops you '
          'when even the simplest way fails.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“Get closer to the box. Walls, floors, furniture, and '
              'distance all chew up the radio signal between you and the '
              'box on the wall, and the further away you sit, the more '
              'gets chewed up.”',
          attribution:
              'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, '
              'in preparation, 2026), chapter 5',
        ),
      ],
    ),
    // ── 6. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonLede('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'Digital always sounds better.',
          fact:
              'Digital is better at copying and at ignoring noise. How '
              'good it sounds depends on how much of the sound it keeps.',
        ),
        LessonMyth(
          myth: 'Wi-Fi sends ones and zeros through the air.',
          fact:
              'What travels is a smooth wave. The ones and zeros are in '
              'the small changes to that wave.',
        ),
        LessonMyth(
          myth: 'Digital sound comes out of the speaker in steps.',
          fact:
              'Your phone smooths the numbers back into a wave before '
              'the speaker plays it.',
        ),
        LessonMyth(
          myth: 'A weak digital signal just looks a little worse.',
          fact:
              'Digital TV usually looks fine until it stops. Wi-Fi slows '
              'down in steps instead.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-11.svg',
          width: 784,
          height: 180,
          caption:
              '**Figure 11. The four facts, in pictures.** One '
              'picture for each fact above, in the same order.',
        ),
      ],
    ),
    // ── 7. What this means at home ─────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'What this means at home',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/analog-vs-digital/fig-12.svg',
          width: 784,
          height: 428,
          caption:
              '**Figure 12. Two things you can do today.** Move '
              'closer or clear the path, and Wi-Fi climbs back up its '
              'staircase. Copy files rather than converting them.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'TV channels vanish instead of going fuzzy?',
            body:
                'That\'s the cliff. Raise or aim the antenna, and watch '
                'the signal meter in your TV\'s menu.',
          ),
          LessonCardData(
            title: 'Want the best music?',
            body:
                'Turn on lossless in your music app, and listen through '
                'a wire. Bluetooth squeezes the sound.',
          ),
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked 28 September 2026. Music app settings change with '
          'updates.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Steven W. Smith, __The Scientist and Engineer\'s Guide to '
              'Digital Signal Processing__, chapters 3.1 to 3.3 '
              '(dspguide.com): sampling, aliasing, rebuilding the curve',
          'Keysight, application note 1298, __Digital Modulation in '
              'Communications Systems__: the carrier, and the three things '
              'that can change',
          'Cisco Meraki documentation, "802.11 Fundamentals: Modulation" '
              'and the Wi-Fi 6 technical guide: QAM, and Wi-Fi choosing '
              'simpler patterns as the signal weakens',
          'Library of Congress, Data Integrity Management; Digital '
              'Preservation Coalition, Fixity and checksums',
          'Apple support article 118295, Apple Music lossless audio '
              '("Bluetooth connections aren\'t lossless")',
          'FCC, Antennas and Digital Television, and converter-box '
              'troubleshooting guide: the cliff effect',
          'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, in '
              'preparation, 2026), chapter 5',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to know '
              'what the two words mean. Company names appear only where '
              'their own documents are the source. The guide is '
              'independent and isn\'t affiliated with any maker or '
              'broadcaster.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
