// Bluetooth, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   bluetooth-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kBluetoothLesson = GuidedLesson(
  toolId: 'bluetooth-explained',
  route: '/tools/bluetooth-explained',
  title: 'Bluetooth, Explained',
  guideTitle: 'Bluetooth, Explained',
  tagline: 'A plain-English guide',
  promise:
      'Why your earbuds cut out, why the car won\'t connect, and what to '
      'do about each.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/bluetooth/cover.svg',
    width: 700,
    height: 250,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Bluetooth is a short-range radio. It links your phone to '
          'earbuds, speakers, watches and your car. When the sound cuts '
          'out, one of three things is usually to blame.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'Something in the way',
            body:
                'Often it\'s you. Your body sits between the phone in '
                'your pocket and the earbud in your ear.',
          ),
          LessonCardData(
            title: 'A crowded band',
            body:
                'Bluetooth shares its radio space with Wi-Fi. On a busy '
                'train, lots of radios take turns.',
          ),
          LessonCardData(
            title: 'A stale pairing',
            body:
                'Cars and earbuds remember old phones. Old entries cause '
                'many car troubles.',
          ),
        ]),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**Pairing** is the one-time introduction between two '
              'devices. **Connecting** is what they do every time after '
              'that. **CarPlay** puts iPhone apps on the car\'s screen. '
              '**Android Auto** does the same for Android phones.',
        ),
      ],
    ),
    // ── 2. Pairing and connecting ──────────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Pairing and connecting',
      blocks: <LessonBlock>[
        LessonLede(
          'People use these two words as if they mean the same thing. They '
          'are two steps. Knowing which one failed tells you what to do.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-01.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 1. Pair once, connect every time.** Pairing '
              'stores a secret key on both devices. Connecting uses '
              'that key each time they meet.',
        ),
        LessonBullets(<String>[
          '**It never shows up in the list?** Pairing failed. Put the '
              'other device in pairing mode. Its manual says how.',
          '**It\'s saved, but won\'t connect?** Turn Bluetooth off, wait '
              'a few seconds, and turn it back on. Then restart both devices.',
          '**It connects, but the sound cuts in and out?** The pairing '
              'is fine. Something is in the way (steps 4 and 5).',
        ]),
      ],
    ),
    // ── 3. One band, shared with Wi-Fi ─────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'One band, shared with Wi-Fi',
      blocks: <LessonBlock>[
        LessonLede(
          'Bluetooth uses the same radio band as a lot of Wi-Fi. Microwave '
          'ovens use it too. Everyone takes turns in the same small space.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-02.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 2. One small band, lots of users.** Bluetooth '
              'hops between many tiny channels, many times a second. '
              'It learns which ones are busy and skips them.',
        ),
        LessonText(
          'Hopping works well until the whole band is busy. Then there\'s '
          'nowhere quiet left to hop to.',
        ),
        LessonCallout.note(
          title: 'The free fix at home',
          body:
              'If your router offers 5 GHz Wi-Fi, put the devices that '
              'can use it there. That leaves more room for your earbuds, '
              'keyboard and mouse.',
        ),
      ],
    ),
    // ── 4. Your body is the wall ───────────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Your body is the wall',
      blocks: <LessonBlock>[
        LessonLede(
          'You may have heard Bluetooth reaches about 10 m (33 feet). Yet '
          'the sound breaks up with the phone in your back pocket. The '
          'difference is what\'s in the way.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-03.svg',
          width: 760,
          height: 310,
          caption:
              '**Figure 3. Bodies get in the way.** Every person '
              'between your phone and your earbud weakens the signal. '
              'Thicker lines mean a stronger signal.',
        ),
        LessonText(
          'You are mostly water. Water soaks up this kind of radio signal. '
          'And you\'re standing right next to both radios.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note, from __Fix Your Own Wi-Fi__',
          body:
              '"Water and metal are usually the ones that surprise '
              'people, which is one reason kitchens and bathrooms turn '
              'up as dead spots so often, though your house is its own '
              'experiment and the only way to know is to read it."',
        ),
        LessonCallout.note(
          title: 'Why it can be worse outdoors',
          body:
              'Indoors, walls bounce the signal around, so some of it '
              'finds a way around your body. Outside there\'s less to '
              'bounce off. Your body blocks more of what\'s left.',
        ),
      ],
    ),
    // ── 5. Crowds, trains and calls ────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Crowds, trains and calls',
      blocks: <LessonBlock>[
        LessonLede(
          'Earbuds that are fine at home often stutter on the train or at '
          'the airport. There are more bodies in the way, and more radios '
          'sharing the band.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-04.svg',
          width: 760,
          height: 262,
          caption:
              '**Figure 4. In a crowd, your earbuds get fewer '
              'turns.** Every radio nearby shares the same band, so '
              'your earbuds get fewer clear chances. Lime boxes are '
              'your earbuds\' turns. Not to scale.',
        ),
        LessonHeading('What you can do'),
        LessonSteps(<String>[
          '**Move the phone.** Put it in a front pocket, on the same '
              'side as the ear that drops out. Or hold it.',
          '**Test with downloaded music.** If it plays cleanly but '
              'streaming stutters, the problem is your internet, not '
              'Bluetooth.',
          '**Pick "stable connection."** Some earbud apps offer it. It '
              'sends less data, so there\'s less to lose.',
        ]),
      ],
    ),
    // ── 6. Why calls sound thinner than music ──────────────────────────────
    LessonStep(
      number: '6',
      title: 'Why calls sound thinner than music',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-05.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 5. Music goes one way. A call goes both '
              'ways.** Lime is sound coming to your ears. Blue is '
              'your voice going back to the phone.',
        ),
        LessonText(
          'Music only goes one way, to your ears. A call goes both ways, '
          'because your voice travels back from the earbud\'s microphone. '
          'Most earbuds switch to a simpler mode for that, so voices sound '
          'flat. That\'s normal, not a fault.',
        ),
        LessonText(
          'Your phone and earbuds also squeeze the sound to fit it over '
          'the air. They pick the method on their own. You rarely need to '
          'think about it.',
          small: true,
        ),
      ],
    ),
    // ── 7. One set of earbuds, two devices ─────────────────────────────────
    LessonStep(
      number: '7',
      title: 'One set of earbuds, two devices',
      blocks: <LessonBlock>[
        LessonLede(
          'You paired your earbuds with your phone and your laptop. '
          'Sometimes they follow you from one to the other. Sometimes they '
          'stay on the wrong one.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-06.svg',
          width: 760,
          height: 220,
          caption:
              '**Figure 6. Two devices at once.** Some earbuds stay '
              'connected to a phone and a laptop together. The earbud '
              'maker decides which one wins when both make sound.',
        ),
        LessonHeading('When the earbuds go to the wrong device'),
        LessonSteps(<String>[
          'Pick the earbuds from the Bluetooth or sound menu on the '
              'device you want.',
          'If two devices keep grabbing them, turn off Bluetooth on the '
              'one you\'re not using.',
        ]),
      ],
    ),
    // ── 8. Bluetooth in your car ───────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Bluetooth in your car',
      blocks: <LessonBlock>[
        LessonLede(
          'To your phone, the car is just another Bluetooth device. What '
          'makes cars harder is that they\'re shared, and they remember.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'A full memory',
            body:
                'Cars keep a list of every phone they\'ve met, including '
                'rental drivers and the last owner. Delete phones nobody '
                'uses.',
          ),
          LessonCardData(
            title: 'Look-alike names',
            body:
                'Two phones both called "iPhone" confuse the car. Give '
                'yours its own name in your phone\'s settings.',
          ),
          LessonCardData(
            title: 'Two phones aboard',
            body:
                'With two paired phones in the car, the car connects to '
                'one of them, not always the one you wanted. Most cars '
                'let you choose the phone on the car\'s screen.',
          ),
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-07.svg',
          width: 760,
          height: 304,
          caption:
              '**Figure 7. A short, clear list helps the car find '
              'your phone.** Left, the list a car builds up over the '
              'years. Right, the same list cleaned up.',
        ),
        LessonHeading('Pairing with a car'),
        LessonSteps(<String>[
          'Park first. Setup means looking at the screen.',
          'Start pairing from the car\'s screen. Look for Phone, '
              'Bluetooth or Connections.',
          'On your phone, open Bluetooth settings and pick the car\'s '
              'name.',
          'If a code shows on both screens, check that they match, then '
              'confirm.',
        ]),
      ],
    ),
    // ── 9. Wireless CarPlay and Android Auto ───────────────────────────────
    LessonStep(
      number: '9',
      title: 'Wireless CarPlay and Android Auto',
      blocks: <LessonBlock>[
        LessonLede(
          'Most people think wireless CarPlay is all Bluetooth. It isn\'t. '
          'Bluetooth finds the car. Wi-Fi carries the screen and the sound.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-08.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 8. Two radios, two jobs.** Bluetooth finds '
              'the car and reconnects. Wi-Fi carries the maps, music '
              'and messages to the car\'s screen.',
        ),
        LessonText(
          'So both radios have to be on. If you switch Wi-Fi off to save '
          'battery, wireless CarPlay stops working.',
        ),
        LessonCallout.note(
          title: 'If your car has a USB port for CarPlay',
          body:
              'Plug in with a cable. If the problem goes away, the '
              'wireless link was the trouble. Use a cable that carries '
              'data, not just charge.',
        ),
      ],
    ),
    // ── 10. When the car won't connect ─────────────────────────────────────
    LessonStep(
      number: '10',
      title: 'When the car won\'t connect',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-09.svg',
          width: 760,
          height: 270,
          caption:
              '**Figure 9. Fix the car connection in this order.** '
              'Start at the lime box. Stop as soon as it works.',
        ),
        LessonText('Do these while parked.', small: true),
        LessonSteps(<String>[
          'Restart your phone. Turn the car fully off and on again.',
          'Turn Bluetooth off on the phone, wait a few seconds, and turn '
              'it back on.',
          'For wireless CarPlay or Android Auto, check that Wi-Fi is on '
              'too.',
          'On the car\'s screen, delete phones nobody uses any more.',
          'Update your phone. Ask the car maker about a stereo update '
              'too.',
          'Last: forget the car on your phone, delete your phone on the '
              'car, and pair again from the car\'s screen.',
        ]),
        LessonCallout.note(
          title: 'Before a road trip in a rental',
          body:
              'Pair from the car\'s screen before you pull out, and '
              'delete your phone from the car\'s list when you return '
              'it, so the next driver doesn\'t see your contacts or '
              'recent calls.',
        ),
      ],
    ),
    // ── 11. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth:
              'Bluetooth reaches 10 m (33 feet), so a phone in my pocket '
              'should be perfect.',
          fact:
              'Range depends on what\'s in the way. Your own body is '
              'often the problem.',
        ),
        LessonMyth(
          myth: 'Wireless CarPlay is just Bluetooth.',
          fact:
              'Bluetooth finds the car. Wi-Fi carries the screen and '
              'sound. Turn off Wi-Fi and it stops.',
        ),
        LessonMyth(
          myth: 'Forgetting and pairing again fixes everything.',
          fact:
              'It fixes a broken pairing. It does nothing for a body or '
              'a crowd in the way.',
        ),
        LessonMyth(
          myth: 'My earbuds sound bad on calls, so they\'re broken.',
          fact:
              'Calls use a simpler two-way mode made for voices. Thin '
              'sound on calls is normal.',
        ),
        LessonHeading('When to forget and pair again'),
        LessonFigure(
          asset: 'assets/lesson-figures/bluetooth/fig-10.svg',
          width: 760,
          height: 260,
          caption:
              '**Figure 10. Pairing again fixes a broken pairing, not '
              'a blocked path.** Left, when to forget and pair again. '
              'Right, when it won\'t help.',
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked against each company\'s own pages in September 2026. '
          'Menus and car support change with software updates.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Bluetooth SIG, Understanding Bluetooth Range '
              '(bluetooth.com/learn-about-bluetooth/key-attributes/range): '
              'the 2,400 to 2,483.5 MHz band, "more than a kilometer" to '
              '"less than a meter", obstacles',
          'Bluetooth SIG, LE Audio '
              '(bluetooth.com/learn-about-bluetooth/bluetooth-technology/le-audio): '
              'LC3 against SBC, hearing aids, Auracast',
          'Apple, WWDC 2017 session 717, Developing Wireless CarPlay '
              'Systems: Bluetooth "to discover and reconnect", Wi-Fi for '
              '"all audio and video", 5 GHz recommended',
          'Apple 108415, Use CarPlay with your iPhone (updated 6 March '
              '2025)',
          'Apple 105109, If you need help with CarPlay (13 March 2025)',
          'Apple 102521, How to connect your iPhone, iPad or iPod touch '
              'to your car (9 January 2026)',
          'Apple 102530, If the sound from your wireless headphones cuts '
              'out or is distorted (30 March 2026)',
          'Apple 102319, Resolve Wi-Fi and Bluetooth issues caused by '
              'wireless interference',
          'Apple 105108, Connect a third-party Bluetooth accessory to '
              'your iPhone or iPad (18 December 2025)',
          'Google, Android Auto Help 6348019, Get started with Android '
              'Auto: wireless requirements',
          'Google, Android Help 9769184, Fix Bluetooth problems on '
              'Android; Android Help 9417604, Find and set up Bluetooth '
              'devices',
          'U.S. Geological Survey, The Water in You: Water and the Human '
              'Body',
          'Keith Parsons, __Fix Your Own Wi-Fi__ (in preparation, 2026), '
              'chapter 5',
        ]),
      ],
    ),
  ],
);
