// Cameras, Doorbells and Baby Monitors, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   cameras-doorbells-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kCamerasDoorbellsLesson = GuidedLesson(
  toolId: 'cameras-doorbells-explained',
  route: '/tools/cameras-doorbells-explained',
  title: 'Cameras, Doorbells and Baby Monitors, Explained',
  guideTitle: 'Cameras, Doorbells and Baby Monitors, Explained',
  tagline: 'A plain-English guide',
  promise:
      'A camera is the rare gadget in your home that sends more than it '
      'receives. Make yours record when it matters, and keep strangers out '
      'of it.',
  byline: <String>['Keith Parsons · CWNE #3', 'Current as of September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/cameras-doorbells/cover.svg',
    width: 700,
    height: 190,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Most gadgets in your home pull things in. A camera pushes video '
          'out, often all day.',
        ),
        LessonText(
          'That one fact explains most camera trouble. Clips start late. '
          'Live video spins. The doorbell drops offline. Each usually '
          'comes down to three things: how much your internet can send, '
          'how well the camera hears your Wi-Fi, and where the video ends '
          'up.',
        ),
        LessonCallout.note(
          title: 'The one idea to remember',
          body:
              'A camera is judged by what it can send, from the spot '
              'where it hangs.',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**The box** means whatever your camera talks to over the '
              'air: your router, or the nearest unit of a mesh system. '
              '**Camera** covers security cameras, video doorbells and '
              'Wi-Fi baby monitors. They all send video the same way.',
        ),
      ],
    ),
    // ── 2. The camera sends ────────────────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'The camera sends',
      blocks: <LessonBlock>[
        LessonLede(
          'Your internet line runs two ways. Download is what comes to '
          'you. Upload is what you send.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-01.svg',
          width: 720,
          height: 190,
          caption:
              '**Figure 1. Two directions.** A camera\'s video leaves '
              'your home on the upload side. The big download number '
              'on your bill says little about it.',
        ),
        LessonText(
          'Internet plans are sold by their download number. A camera '
          'lives on the upload side, and upload is usually much smaller.',
        ),
        LessonText(
          'Some cameras send all the time. Others send only when something '
          'moves. Your camera\'s help page says which kind you have.',
        ),
      ],
    ),
    // ── 3. How many cameras your line can carry ────────────────────────────
    LessonStep(
      number: '3',
      title: 'How many cameras your line can carry',
      blocks: <LessonBlock>[
        LessonLede('Cameras add up. Each one takes a slice of your upload.'),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-02.svg',
          width: 720,
          height: 276,
          caption:
              '**Figure 2. Cameras fill the upload.** Each camera '
              'takes a slice of your upload. Add enough and a video '
              'call no longer fits. Not to scale.',
        ),
        LessonText(
          'One maker\'s help page says its best-quality camera sends about '
          '3 megabits a second. A typical home upload is only a few times '
          'that.',
        ),
        LessonText(
          'When the upload fills, a video call freezes or a clip arrives '
          'late. Some cameras quietly switch to blurrier video instead.',
        ),
        LessonCallout.note(
          title: 'Find your own upload number',
          body:
              'Open the free WLAN Pros Toolbox, tap Network Quality, and '
              'read the upload row. Leave room for everything else you '
              'send.',
        ),
        LessonToolLink('net-quality'),
      ],
    ),
    // ── 4. Signal at the door ──────────────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Signal at the door',
      blocks: <LessonBlock>[
        LessonLede(
          'Your router usually sits at the back of the house. Your '
          'doorbell sits outside the front wall.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-03.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 3. Same house, same doorbell.** The dashed '
              'line is the Wi-Fi path. Moving the box, or adding a '
              'unit near the front, takes walls out of the way.',
        ),
        LessonText(
          'The outside wall is the hardest one for Wi-Fi to cross. Brick, '
          'stone and stucco take a lot of the signal. Metal siding is '
          'worse.',
        ),
        LessonText(
          'A camera with one bar sends slowly. It keeps the Wi-Fi busy for '
          'everyone else too. Check its signal in the camera\'s app, with '
          'the door shut.',
        ),
        LessonHeading('Fixes, gentlest first'),
        LessonSteps(<String>[
          'Move the box toward the front of the house, up off the floor.',
          'Add a mesh unit or access point inside, near the front wall.',
          'Run a cable to the camera, or to an access point near the '
              'door.',
        ]),
      ],
    ),
    // ── 5. Which Wi-Fi lane? ───────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Which Wi-Fi lane?',
      blocks: <LessonBlock>[
        LessonLede(
          'Home Wi-Fi runs in separate lanes, called 2.4 GHz and 5 GHz.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-04.svg',
          width: 720,
          height: 215,
          caption:
              '**Figure 4. Two lanes to the door.** The 2.4 GHz lane '
              'reaches farther through walls but is busier. The 5 GHz '
              'lane carries more but gives up sooner.',
        ),
        LessonCallout.quote(
          speaker: 'From Keith\'s book',
          body:
              '"The old outer lane is named 2.4. It reaches farther than '
              'the others, and it is also the most crowded road in the '
              'neighborhood, because every old gadget in every house '
              'nearby is crammed into it alongside yours. The middle '
              'lane is named 5. It does not reach quite as far, but '
              'there is far more room in it, and that room is what you '
              'actually feel as speed."',
          attribution: 'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 3',
        ),
        LessonText(
          'Some cameras only use 2.4 GHz. If yours can use either and '
          'hangs far from the box, 2.4 GHz often holds better. Close by, 5 '
          'GHz gives it more room.',
        ),
      ],
    ),
    // ── 6. Wired cameras and doorbells ─────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Wired cameras and doorbells',
      blocks: <LessonBlock>[
        LessonLede('"Wired" can mean two different things on a camera box.'),
        LessonBullets(<String>[
          '**Wired for power.** A plug-in camera, or a doorbell on your '
              'old doorbell wires. Its video still goes out by Wi-Fi.',
          '**Wired for video.** An Ethernet camera. One network cable '
              'can carry both power and video, so there\'s no radio link at '
              'all. Most routers can\'t send power down the cable, so it may '
              'need a small power box.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-05.svg',
          width: 720,
          height: 268,
          caption:
              '**Figure 5. What the wire carries.** Only the one on a '
              'network cable sends its video without Wi-Fi. The other '
              'two still need a good Wi-Fi signal.',
        ),
        LessonText(
          'A battery camera is the easiest to mount anywhere. It needs '
          'charging, and weak Wi-Fi drains it faster.',
        ),
        LessonCallout.note(
          title: 'Why the cable wins, where you can run one',
          body:
              'A cable has no walls to cross and no neighbors in the '
              'same lane. An Ethernet camera works the same on the '
              'busiest evening as it does in the middle of the night. '
              'It\'s the best choice for the camera that watches your '
              'door.',
        ),
        LessonText(
          'Can\'t run a cable to the camera? A cable to an access point '
          'just inside the front wall does most of the same good.',
        ),
      ],
    ),
    // ── 7. Where the video goes ────────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Where the video goes',
      blocks: <LessonBlock>[
        LessonLede(
          'Every camera saves its video somewhere: in the cloud, or in '
          'your home.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-06.svg',
          width: 720,
          height: 230,
          caption:
              '**Figure 6. Two places to keep video.** Many cameras '
              'can do both.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'Cloud',
            body:
                'A thief who takes the camera doesn\'t take the video '
                'already saved. It uses your upload, often needs a '
                'monthly plan, and stops saving if the internet drops.',
          ),
          LessonCardData(
            title: 'In your home',
            body:
                'A memory card or a home recorder keeps saving when the '
                'internet is down. But a card inside the camera leaves '
                'with the camera.',
          ),
        ]),
      ],
    ),
    // ── 8. Baby monitors ───────────────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Baby monitors',
      blocks: <LessonBlock>[
        LessonLede(
          'A baby monitor is a camera with one job and one viewer. There '
          'are two kinds.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-07.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 7. Two kinds of baby monitor.** One talks '
              'straight to its own screen. The other goes through '
              'your Wi-Fi and the internet to your phone.',
        ),
        LessonText(
          'If you only need to watch from inside the house, a direct-radio '
          'monitor keeps the nursery off the internet. If you want to '
          'check in from work, a Wi-Fi monitor needs the same care as a '
          'front-door camera.',
        ),
        LessonCallout.stop(
          title: 'Keep the monitor and its cord out of reach',
          body:
              'Baby monitor cords have strangled children. Keep the '
              'monitor and its cord at least 1 m (3 feet) from any part '
              'of the crib. Never put a monitor in the crib or on its '
              'edge.',
        ),
      ],
    ),
    // ── 9. Keep strangers out ──────────────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Keep strangers out',
      blocks: <LessonBlock>[
        LessonLede(
          'A camera on the internet needs a lock. Four habits do most of '
          'the work.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-08.svg',
          width: 720,
          height: 178,
          caption:
              '**Figure 8. Four ways to lock a camera down.** Do all '
              'four, starting with the password.',
        ),
        LessonSteps(<String>[
          '**Give it its own password.** Never keep the one it came '
              'with, and don\'t reuse one from another account.',
          '**Turn on two-step sign-in.** A code on your phone stops '
              'someone who guesses the password.',
          '**Keep it updated.** Turn on automatic updates in the '
              'camera\'s app.',
          '**Check who can watch.** Remove anyone who no longer needs to '
              'see your cameras.',
        ]),
      ],
    ),
    // ── 10. When the Wi-Fi is cut on purpose ───────────────────────────────
    LessonStep(
      number: '10',
      title: 'When the Wi-Fi is cut on purpose',
      blocks: <LessonBlock>[
        LessonLede(
          'A jammer is a gadget that drowns out radio signals nearby. '
          'Police have warned about burglars using them to cut wireless '
          'cameras off.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-09.svg',
          width: 720,
          height: 240,
          caption:
              '**Figure 9. When the radio link drops.** The red X is '
              'any break in the Wi-Fi hop: a jammer, a box that\'s '
              'switched off, or plain weak signal.',
        ),
        LessonHeading('Three defenses, strongest first'),
        LessonSteps(<String>[
          '**Wire the cameras that matter.** A cable has no radio link '
              'to drown out.',
          '**Record on a memory card too.** The camera keeps saving '
              'while its Wi-Fi is down.',
          '**Turn on offline alerts.** The app can tell you when a '
              'camera goes quiet.',
        ]),
        LessonCallout.caution(
          title: 'Jammers are illegal in the US',
          body:
              'Using, selling or importing one is against the law, with '
              'fines and even prison. Ordering one online from overseas '
              'counts as importing. Don\'t buy one to test your own '
              'cameras.',
        ),
      ],
    ),
    // ── 11. Five things people get wrong ───────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Five things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-10.svg',
          width: 720,
          height: 226,
          caption:
              '**Figure 10. What\'s true, in pictures.** Each '
              'numbered panel goes with the myth of the same number '
              'below.',
        ),
        LessonMyth(
          myth: 'A fast internet plan covers my cameras.',
          fact:
              'Cameras send. The upload number is the one that counts, '
              'and it\'s usually much smaller.',
        ),
        LessonMyth(
          myth: 'One bar at the front door is fine.',
          fact:
              'A camera that barely hears the box sends slowly, may blur '
              'its own video, and slows the Wi-Fi for everyone.',
        ),
        LessonMyth(
          myth: 'A "wired" doorbell sends its video over the wire.',
          fact:
              'In most homes the wire only powers it. The video still '
              'goes out by Wi-Fi.',
        ),
        LessonMyth(
          myth: 'The default password is fine on my own network.',
          fact:
              'Change it. The first rule for any camera is its own '
              'password.',
        ),
        LessonMyth(
          myth: 'Cloud recording is the only option.',
          fact: 'Memory cards and home recorders keep video in your house.',
        ),
      ],
    ),
    // ── A. Do this now ─────────────────────────────────────────────────────
    LessonStep(
      number: 'A',
      spoken: 'Appendix',
      title: 'Do this now',
      blocks: <LessonBlock>[
        LessonLede(
          'Half an hour, one camera at a time. Start with the one at your '
          'door.',
        ),
        LessonTask(
          title: 'Check the upload',
          steps: <String>[
            'Look up each camera\'s upload on its maker\'s help page, and '
                'add them up.',
            'In the free WLAN Pros Toolbox, tap Network Quality and read '
                'the upload row. Compare.',
          ],
        ),
        LessonToolLink('net-quality'),
        LessonTask(
          title: 'Check the signal where it hangs',
          steps: <String>[
            'Open the camera\'s app and find its signal reading, with the '
                'door shut.',
            'If it\'s weak, work through the fixes in step 4.',
          ],
        ),
        LessonTask(
          title: 'Lock it down',
          steps: <String>[
            'Its own password, two-step sign-in and automatic updates on '
                'every camera.',
            'Baby monitor and cord at least 1 m (3 feet) from the crib.',
          ],
        ),
      ],
    ),
    // ── A. Do this now, continued ──────────────────────────────────────────
    LessonStep(
      number: 'A',
      spoken: 'Appendix',
      title: 'Do this now, continued',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/cameras-doorbells/fig-11.svg',
          width: 720,
          height: 312,
          caption:
              '**Figure 11. The unplug test.** Take the internet '
              'away, give the camera something to record, then look '
              'on its card or home recorder. A clip there means it '
              'records at home.',
        ),
        LessonTask(
          title: 'Test recording without the internet',
          steps: <String>[
            'When nobody needs the internet, unplug the internet line from '
                'the box for five minutes, and walk past the camera.',
            'Plug it back in. If the clip isn\'t on the memory card or '
                'your home recorder, the camera saves only to the cloud.',
          ],
        ),
      ],
    ),
    // ── →. Where this comes from ───────────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where this comes from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked in September 2026. Rules, plans and products change, so '
          'check the ones you rely on.',
          small: true,
        ),
        LessonSourceList(<String>[
          'FCC, "Jammer Enforcement," updated September 2026: '
              'fcc.gov/general/jammer-enforcement',
          'FTC Consumer Advice, "How To Secure Your Home Security '
              'Cameras," February 2023: '
              'consumer.ftc.gov/articles/how-secure-your-home-security-cameras',
          'FTC Consumer Advice, "Securing Your Internet-Connected '
              'Devices at Home," August 2022: '
              'consumer.ftc.gov/articles/securing-your-internet-connected-devices-home',
          'Google Nest Help, "Learn about internet bandwidth & speed '
              'requirements for Nest cameras": '
              'support.google.com/googlenest/answer/9245832',
          'US Consumer Product Safety Commission, OnSafety, "Baby '
              'Monitor Cords: 3 Feet from Baby," 11 July 2012: '
              'onsafety.cpsc.gov',
          'Police warnings, as reported: PCWorld, "Burglars are jamming '
              'Wi-Fi security cameras," 12 November 2024 (LAPD Wilshire '
              'Division, 2024); NBC Los Angeles, 17 March 2025 (LAPD Chief '
              'Jim McDonnell)',
          'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, in '
              'preparation, 2026), chapter 3',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want their '
              'cameras to work when it matters. The figures come from '
              'one maker\'s help page because it publishes per-camera '
              'upload numbers; they\'re one maker\'s numbers, not a '
              'rating, and no maker had a part in this guide. The guide '
              'is independent and isn\'t affiliated with any camera '
              'maker, provider or carrier.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
