// Captive Portals, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   captive-portals-explained--SOURCE.html
//   myPKA commit 3393a775 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kCaptivePortalsLesson = GuidedLesson(
  toolId: 'captive-portals-explained',
  route: '/tools/captive-portals-explained',
  title: 'Captive Portals, Explained',
  guideTitle: 'Captive Portals, Explained',
  tagline: 'A plain-English guide',
  promise:
      'What that Wi-Fi sign-in page is, why it shows up, and what to do '
      'when it doesn\'t.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/captive-portals/cover.svg',
    width: 616,
    height: 360,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'That Wi-Fi sign-in page has a name: a captive portal. It sits '
          'between the Wi-Fi and the internet. Until you finish it, almost '
          'nothing else loads.',
        ),
        LessonText(
          'This guide answers three questions. What is that page? Why does '
          'it matter to you? And what do you do when it won\'t show up?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'People call it a sign-in page, a login page, a splash '
              'page or a captive portal. They all mean the same page. '
              'This guide calls it the **sign-in page**.',
        ),
        LessonCallout.note(
          title: 'Other guides in this series',
          body:
              'Plane Wi-Fi has its own guide: __Wi-Fi on Planes, '
              'Explained__. For a TV stick or game console on the road, '
              'see __Travel Routers, Explained__.',
        ),
        LessonToolLink('wifi-on-planes-explained'),
        LessonToolLink('travel-routers-explained'),
      ],
    ),
    // ── 2. A gate in front of the internet ─────────────────────────────────
    LessonStep(
      number: '2',
      title: 'A gate in front of the internet',
      blocks: <LessonBlock>[
        LessonLede(
          'Joining the Wi-Fi and reaching the internet are two separate '
          'steps. A sign-in page stops you between them.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-01.svg',
          width: 616,
          height: 360,
          caption:
              '**Figure 1. Full bars is only step one.** Your phone '
              'joins the Wi-Fi first. The road to the internet stays '
              'closed until you finish the page.',
        ),
        LessonText(
          'That\'s why your phone can show full bars and still load '
          'nothing. The bars only tell you the Wi-Fi part worked.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“If a network ever asked you to sign in on a web page, '
              'your Wi-Fi already worked.”',
          attribution:
              'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 6, '
              '2026',
        ),
        LessonHeading('What the page asks for'),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-02.svg',
          width: 616,
          height: 250,
          caption:
              '**Figure 2. Four common asks.** Most pages want one of '
              'these. Some only want you to tap Accept.',
        ),
        LessonHeading('Why places use one'),
        LessonText(
          'A place with free or paid Wi-Fi wants a say before you go '
          'online. It may check that you\'re a guest, show its rules, or '
          'charge for time.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-03.svg',
          width: 616,
          height: 270,
          caption:
              '**Figure 3. Why places use one.** Hotels, airports, '
              'cafes and planes each have a reason. The page always '
              'comes first.',
        ),
      ],
    ),
    // ── 3. How your phone notices ──────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'How your phone notices',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone checks every new Wi-Fi network. It asks for a small '
          'test page it already knows by heart.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-04.svg',
          width: 616,
          height: 420,
          caption:
              '**Figure 4. A test with a known answer.** A normal '
              'network sends the test page back. A sign-in network '
              'answers differently, usually by sending you to its own '
              'page. Your phone sees the wrong answer and pops the '
              'page up for you.',
        ),
        LessonText(
          'You don\'t have to do anything for this check. It happens by '
          'itself, in a moment.',
        ),
        LessonHeading('What you\'ll see'),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-05.svg',
          width: 616,
          height: 380,
          caption:
              '**Figure 5. Three ways the page shows up.** Each kind '
              'of device brings the page to you a little differently. '
              'Either way, finish the page.',
        ),
        LessonText(
          'On an iPhone, tapping Cancel on the sign-in window takes you '
          'off the network. Finish the page first. If you cancel by '
          'mistake, just join again.',
        ),
        LessonText(
          'Email, messages and Wi-Fi Calling over that Wi-Fi wait for the '
          'page too. Regular calls over the cell network may still work.',
        ),
      ],
    ),
    // ── 4. When the page doesn't show up ───────────────────────────────────
    LessonStep(
      number: '4',
      title: 'When the page doesn\'t show up',
      blocks: <LessonBlock>[
        LessonLede(
          'Sometimes the page never pops up. You\'re on the Wi-Fi, but '
          'nothing loads. Try these, in order.',
        ),
        LessonSteps(<String>[
          '**Give it a moment.** The page can take a few seconds to '
              'appear.',
          '**Open your web browser and type an address that starts with '
              'http://,** such as http://example.com. The network can then '
              'show you its page.',
          '**Forget the network, then join it again.** Your phone checks '
              'again from the start.',
          '**Turn off your own VPN for a moment.** Turn it back on once '
              'you\'re signed in. For a work or school VPN, ask your IT team.',
          '**Still stuck? Ask the front desk or the staff.**',
          '**Need the internet right now?** Turn Wi-Fi off and use cell '
              'data, if your plan allows it.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-06.svg',
          width: 616,
          height: 360,
          caption:
              '**Figure 6. Start with http://.** A plain http:// '
              'address lets the network show its page. A secure '
              'https:// site can\'t be swapped, so your browser warns '
              'you instead.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-07.svg',
          width: 616,
          height: 284,
          caption:
              '**Figure 7. Forget, then join again.** This makes your '
              'phone check the network from the start.',
        ),
        LessonHeading('If you use a VPN or private DNS'),
        LessonText(
          'A VPN (virtual private network) is an app that wraps up '
          'everything your phone sends. That can keep the sign-in page '
          'from reaching you. On Android, if Private DNS is set to a '
          'provider hostname, switch it to Automatic while you sign in. On '
          'an iPhone, a Private Relay message means you can turn it off '
          'for that one network.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-08.svg',
          width: 616,
          height: 266,
          caption:
              '**Figure 8. Off for a moment, then back on.** Switch '
              'the VPN off only long enough to finish the page, then '
              'turn it back on.',
        ),
      ],
    ),
    // ── 5. Why the page comes back ─────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Why the page comes back',
      blocks: <LessonBlock>[
        LessonLede(
          'You signed in yesterday, and today the page is back. That\'s '
          'normal.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-09.svg',
          width: 616,
          height: 380,
          caption:
              '**Figure 9. Two reasons the page returns.** Your time '
              'or pass ran out. Or your phone now shows the network a '
              'new Wi-Fi address, so it looks like a new guest.',
        ),
        LessonText(
          'Some phones change their Wi-Fi address from time to time. It '
          'makes you harder to follow from place to place. When the '
          'address changes, the network may not know you, so you sign in '
          'again.',
        ),
      ],
    ),
    // ── 6. What the network can see ────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'What the network can see',
      blocks: <LessonBlock>[
        LessonLede(
          'Any Wi-Fi network can see some of what you do on it. A network '
          'with a sign-in page is no different.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-10.svg',
          width: 616,
          height: 360,
          caption:
              '**Figure 10. Outside and inside.** Most sites now use '
              'secure pages, marked with a padlock. The network '
              'usually sees which site you visit, unless a VPN or a '
              'privacy setting hides it. It doesn\'t see what\'s on '
              'the page.',
        ),
        LessonText(
          'A real sign-in page is a gate, not a window into your secure '
          'pages. Still, type only what the place needs.',
        ),
      ],
    ),
    // ── 7. Stay safe on the sign-in page ───────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Stay safe on the sign-in page',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-11.svg',
          width: 616,
          height: 280,
          caption:
              '**Figure 11. A real page, and a trap.** A real page '
              'asks for a room number, a code, a login the place gave '
              'you, or a pass. A trap asks for the password to your '
              'email.',
        ),
        LessonCallout.stop(
          title: 'Never type your email password into a sign-in page.',
          body:
              'A hotel or cafe doesn\'t need it. Fake networks use fake '
              'sign-in pages to catch passwords.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-12.svg',
          width: 616,
          height: 246,
          caption:
              '**Figure 12. Check the network name.** A look-alike '
              'name can be a trap. Join the one the staff or the sign '
              'names.',
        ),
      ],
    ),
    // ── 8. Devices with no screen ──────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Devices with no screen',
      blocks: <LessonBlock>[
        LessonLede(
          'A TV stick, a game console or a smart speaker can join Wi-Fi. '
          'But many can\'t show you a sign-in page.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-13.svg',
          width: 616,
          height: 360,
          caption:
              '**Figure 13. No screen, no sign-in.** Ask whether the '
              'front desk can add your device. Or bring a travel '
              'router: it signs in once, and your devices join it.',
        ),
        LessonText(
          'Some TV sticks let you finish the page on your phone instead. '
          'Check the device\'s help pages before you travel.',
        ),
        LessonText(
          'Travel routers have their own guide: __Travel Routers, '
          'Explained__.',
        ),
        LessonToolLink('travel-routers-explained'),
      ],
    ),
    // ── 9. Five things people get wrong ────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Five things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'Full bars means I\'m online.',
          fact:
              'The bars only show the Wi-Fi part. A sign-in page can '
              'still be holding back the internet.',
        ),
        LessonMyth(
          myth: 'The page broke, so the Wi-Fi is broken.',
          fact:
              'The page reached you over the Wi-Fi, so the Wi-Fi works. '
              'Open a browser to bring the page back.',
        ),
        LessonMyth(
          myth: 'The sign-in page can read everything I do.',
          fact:
              'On secure pages, the network sees the site\'s name, not '
              'what you read or type.',
        ),
        LessonMyth(
          myth: 'Once I sign in, I\'m set for the whole trip.',
          fact:
              'Time limits and a new Wi-Fi address can bring the page '
              'back. Just sign in again.',
        ),
        LessonMyth(
          myth: 'A network with a sign-in page is a safe network.',
          fact:
              'The page is about who gets in, not about keeping you '
              'safe. Check the network name. A padlock means the link is '
              'private, not that the site is honest.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-14.svg',
          width: 616,
          height: 190,
          caption:
              '**Figure 14. What the bars measure.** Full bars say '
              'you hear the Wi-Fi well. They say nothing about the '
              'internet.',
        ),
      ],
    ),
    // ── 10. Tips for your next trip ────────────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Tips for your next trip',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/captive-portals/fig-15.svg',
          width: 616,
          height: 250,
          caption:
              '**Figure 15. Arriving and leaving.** Finish the page '
              'before you count on your apps. Forget the network when '
              'you go.',
        ),
        LessonSteps(<String>[
          '**Get the network name from the staff or a sign.** Don\'t '
              'guess from the list.',
          '**Join, and give the page a moment.** It usually pops up by '
              'itself.',
          '**Finish the page before you count on email, messages or '
              'calls.**',
          '**No page? Open a browser and type an http:// address.**',
          '**Never give your email password to a sign-in page.**',
          '**When you leave, forget the network.**',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked on 28 September 2026. Menus change with updates, so '
          'look for the same words nearby.',
        ),
        LessonSourceList(<String>[
          'Apple Support, "Use captive Wi-Fi networks on your iPhone or '
              'iPad", 23 April 2026',
          'Apple Developer, "How to modernize your captive network," 22 '
              'June 2020',
          'Apple Support, "About iCloud Private Relay"',
          'Google, Pixel Phone Help, "How to fix Wi-Fi connection '
              'problems"',
          'Google, Chrome Help, "Fix connection errors"',
          'Google, Pixel Phone Help, "Control airplane mode, private DNS '
              '& other network settings"',
          'Apple Support, "Manage iCloud Private Relay for specific '
              'websites, networks, or system settings", 15 September 2025',
          'Apple Support, "Use private Wi-Fi addresses on Apple '
              'devices", 5 December 2025',
          'Android Open Source Project, "MAC randomization behavior" and '
              '"Implement MAC randomization"',
          'Microsoft Learn, "An Internet Explorer or Edge window opens '
              'when your computer connects to a corporate network or a '
              'public network," 12 February 2026',
          'Microsoft Learn, "Network Connectivity Status Indicator FAQ '
              'for Windows," 6 February 2025',
          'US Federal Trade Commission, "Are Public Wi-Fi Networks Safe? '
              'What You Need To Know," February 2023',
          'US Cybersecurity and Infrastructure Security Agency (CISA), '
              '"Securing Wireless Networks," 1 February 2021',
          'CISA, Eviction Strategies Tool, "Evil Twin," 15 April 2025',
          'Government of Canada, Get Cyber Safe, "Public Wi-Fi," 27 '
              'October 2021',
          'Electronic Frontier Foundation, Surveillance Self-Defense, '
              '"What Should I Know About Encryption?", reviewed 2025',
          'Roku Support, "How do I use Hotel & Dorm Connect to connect '
              'to the internet?", 13 February 2026',
          'TP-Link, FAQ 4087, 23 June 2026',
          'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 6, 2026',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'This guide is independent. It isn\'t affiliated with or '
              'endorsed by any hotel, airline, phone maker or government '
              'agency. Companies are named here only as sources.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed and fixed Wi-Fi for '
              'over 25 years. He runs Wireless LAN Professionals and the '
              'WLPC conferences.',
        ),
      ],
    ),
  ],
);
