// How Your Devices Access the Internet, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   devices-to-internet-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kDevicesToInternetLesson = GuidedLesson(
  toolId: 'devices-to-internet-explained',
  route: '/tools/devices-to-internet-explained',
  title: 'How Your Devices Access the Internet, Explained',
  guideTitle: 'How Your Devices Access the Internet, Explained',
  tagline: 'A plain-English guide',
  promise:
      'Wi-Fi and cellular are ways to reach the internet. They are not the '
      'internet. Follow the trip one hop at a time, and learn which hop to '
      'blame when something is slow.',
  byline: <String>[
    'Keith Parsons · CWNE #3',
    'From __Fix Your Own Wi-Fi__ · September 2026',
  ],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/devices-to-internet/cover.svg',
    width: 700,
    height: 190,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Your Wi-Fi and your internet are two different things. They '
          'meet at one box in your home. So they get blamed as one thing.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-01.svg',
          width: 720,
          height: 192,
          caption:
              '**Figure 1. Two roads meet at one box.** Your Wi-Fi '
              'and your internet are different roads, and they meet '
              'at the box. Green is the Wi-Fi inside your home. Blue '
              'is the line out to the world.',
        ),
        LessonText(
          'Everything you do online takes the same trip. It goes from your '
          'phone to the box, out the line you pay for, across the '
          'internet, and to the video or call you wanted. Any stop can be '
          'the slow one.',
        ),
        LessonCallout.note(
          title: 'The one big idea',
          body:
              'Your signal bars only measure the first hop, from your '
              'device to the box. They know nothing about the rest of '
              'the trip.',
        ),
        LessonCallout.note(
          title: 'A word on "the box"',
          body:
              'It\'s whatever your device talks to over the air. That '
              'might be the router your provider gave you, a gateway, or '
              'one of the mesh units around your house.',
        ),
      ],
    ),
    // ── 2. The whole trip ──────────────────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'The whole trip',
      blocks: <LessonBlock>[
        LessonLede(
          'Here\'s the whole trip on one page. Every picture after this is '
          'a close-up of one part of it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-02.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 2. The trip.** Your device talks to the box '
              'over Wi-Fi. The box sends it out the line you pay for, '
              'across the internet, to what you wanted. Cellular goes '
              'its own way through a tower and never touches your box.',
        ),
        LessonText(
          'Keep this picture in mind. When something is slow, the question '
          'is always the same: which part of this trip is the slow one?',
        ),
      ],
    ),
    // ── 3. Two roads, one box ──────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Two roads, one box',
      blocks: <LessonBlock>[
        LessonLede(
          'The trip has two roads. The short hop through the air is your '
          'Wi-Fi. The long trip out to the world is your internet.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-03.svg',
          width: 720,
          height: 200,
          caption:
              '**Figure 3. Two roads, one box.** The two roads meet '
              'at the box on your wall. That\'s why people blame them '
              'as one thing.',
        ),
        LessonText(
          'Your internet plan pays for the second road. It does nothing '
          'for the first. If the slow part is the Wi-Fi hop, a bigger plan '
          'just costs more.',
        ),
        LessonText(
          'Wi-Fi gets the blame because it\'s the part you can see. You '
          'can see the bars and the network name. The internet road is '
          'invisible, so nobody blames it.',
        ),
      ],
    ),
    // ── 4. Six stops ───────────────────────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Six stops',
      blocks: <LessonBlock>[
        LessonLede(
          'Up close, the two roads have six stops. Any one of them can be '
          'the slow one.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-04.svg',
          width: 720,
          height: 165,
          caption:
              '**Figure 4. Six stops.** The first three are in your '
              'home. The fourth belongs to your provider. The last '
              'two are out in the world, and nobody in your house can '
              'fix them.',
        ),
        LessonSteps(<String>[
          '**Your device.** An old or busy phone can be slow on its own.',
          '**Wi-Fi or a cable.** The short hop to the box. Walls and '
              'distance weaken Wi-Fi.',
          '**The box.** It makes your Wi-Fi and talks to your provider. '
              'It is not the internet.',
          '**The line you pay for.** Fiber, cable, DSL, 5G or satellite. '
              'A faster plan only changes this stop. __Home Internet, '
              'Explained__ covers each kind.',
          '**The internet.** The networks between your provider and the '
              'world.',
          '**The service.** The video, game, website or call you wanted.',
        ]),
        LessonToolLink('home-internet-explained'),
      ],
    ),
    // ── 5. What your bars measure ──────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'What your bars measure',
      blocks: <LessonBlock>[
        LessonLede(
          'The bars in the corner of your screen only grade the hop to the '
          'box. You can have full bars and no internet at all.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-05.svg',
          width: 720,
          height: 190,
          caption:
              '**Figure 5. The bars grade one hop.** Full Wi-Fi bars '
              'with a dead internet line happens every day. The bars '
              'only ever looked at the hop to the box.',
        ),
        LessonText(
          'There are two kinds of bars. The fan shape is Wi-Fi. It grades '
          'the hop to your box. The stair-step is cellular. It grades the '
          'hop to the nearest tower.',
        ),
        LessonCallout.note(
          title: 'A sign-in page means the Wi-Fi works',
          body:
              'In a hotel or coffee shop, the page that asks you to sign '
              'in came to you over the Wi-Fi. Finish it before you blame '
              'the Wi-Fi.',
        ),
      ],
    ),
    // ── 6. Cellular skips your box ─────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Cellular skips your box',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone has a second way out. On cellular, it talks straight '
          'to a nearby tower. It never touches your box, your Wi-Fi or '
          'your home internet.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-06.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 6. Two ways out.** On cellular, your phone '
              'reaches the internet through a tower. Your box and '
              'your home internet are not part of that trip.',
        ),
        LessonCallout.note(
          title: 'A free test for a bad corner of the house',
          body:
              'Turn Wi-Fi off on your phone and let it use cellular. If '
              'everything works, the trouble is in your home. If it '
              'fails on cellular too, suspect the phone, the app or the '
              'website.',
        ),
        LessonText(
          '__Wi-Fi Calling, Explained__ covers the opposite trip: calls '
          'that go over your Wi-Fi.',
        ),
        LessonToolLink('wifi-calling-explained'),
      ],
    ),
    // ── 7. Which road is slow? ─────────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Which road is slow?',
      blocks: <LessonBlock>[
        LessonLede(
          'The free WLAN Pros Toolbox can tell you. Tap **Check My '
          'Connection**. In about a minute it grades your Wi-Fi and your '
          'internet separately.',
        ),
        LessonToolLink(
          'test-my-connection',
          route: '/tools/test-my-connection',
          title: 'Test My Connection',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-07.svg',
          width: 700,
          height: 200,
          caption:
              '**Figure 7. One complaint, three causes.** The Wi-Fi '
              'hop, the internet line, or one app or website. The '
              'test tells you which to check first.',
        ),
        LessonBullets(<String>[
          '**Wi-Fi is weaker:** move closer to the box, or move the box.',
          '**Internet is weaker:** run it again, then check with your '
              'provider.',
          '**Both look good:** the slow thing is probably one app or '
              'website.',
        ]),
        LessonText(
          'Then walk. Test next to the box, then in the far corner. The '
          'internet grade stays the same. The Wi-Fi grade changes as you '
          'move.',
        ),
      ],
    ),
    // ── 8. A bigger plan won't fix slow Wi-Fi ──────────────────────────────
    LessonStep(
      number: '8',
      title: 'A bigger plan won\'t fix slow Wi-Fi',
      blocks: <LessonBlock>[
        LessonLede(
          'A faster internet plan does not make your Wi-Fi faster. Traffic '
          'moves only as fast as the narrowest part of the trip.',
        ),
        LessonText(
          'Picture a wide highway that ends in a country lane. If the back '
          'bedroom is slow because of the Wi-Fi, no plan will fix it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-08.svg',
          width: 720,
          height: 330,
          caption:
              '**Figure 8. The narrowest part sets the speed.** A '
              'bigger plan widens the highway, but the back bedroom '
              'still sits at the end of the same narrow Wi-Fi lane. '
              'Top: today. Bottom: after the upgrade.',
        ),
      ],
    ),
    // ── 9. The hotel with perfect bars ─────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'The hotel with perfect bars',
      blocks: <LessonBlock>[
        LessonText(
          'Picture a hotel where every phone shows full Wi-Fi bars, in '
          'every room. Yet web pages crawl and videos won\'t start. '
          'Everyone blames the Wi-Fi.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-09.svg',
          width: 720,
          height: 296,
          caption:
              '**Figure 9. Full bars, slow pages.** Every room has '
              'strong Wi-Fi, but the whole building shares one thin '
              'line to the internet. The highlighted line is the slow '
              'part, not the Wi-Fi.',
        ),
        LessonText(
          'The Wi-Fi is fine. The problem is the other road. The whole '
          'building shares one thin internet line. Adding more Wi-Fi would '
          'cost a fortune and fix nothing.',
        ),
        LessonCallout.note(
          title: 'Ask the slow spot first',
          body:
              'Run Check My Connection where things feel slow. If the '
              'Wi-Fi is the weaker road, keep your wallet closed. A '
              'bigger plan won\'t help.',
        ),
        LessonToolLink(
          'test-my-connection',
          route: '/tools/test-my-connection',
          title: 'Test My Connection',
        ),
      ],
    ),
    // ── 10. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'Full bars means the internet is working.',
          fact:
              'The bars only grade the hop to the box. The internet can '
              'still be down.',
        ),
        LessonMyth(
          myth: 'A faster plan means faster Wi-Fi.',
          fact:
              'A plan only changes the line to your provider. It never '
              'touches the hop through the air.',
        ),
        LessonMyth(
          myth: 'Wi-Fi is the internet.',
          fact:
              'Wi-Fi and cellular are ways to reach the internet. They '
              'are not the internet.',
        ),
        LessonMyth(
          myth: 'If one video won\'t play, the Wi-Fi is broken.',
          fact:
              'If everything else works, that one service is having a '
              'bad day.',
        ),
      ],
    ),
    // ── 11. Do this now ────────────────────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Do this now',
      blocks: <LessonBlock>[
        LessonSteps(<String>[
          '**Get the free Toolbox** at toolbox.wlanpros.com. No account '
              'needed.',
          '**Go to the spot that feels slow** and tap Check My '
              'Connection. See which grade is weaker.',
          '**Walk to the box and test again.** Watch which grade moves.',
          '**Try cellular.** Turn Wi-Fi off. If it works, the trouble is '
              'in your home.',
          '**Call your provider with the result,** not a feeling, if the '
              'internet grade stays weak.',
        ]),
        LessonToolLink(
          'test-my-connection',
          route: '/tools/test-my-connection',
          title: 'Test My Connection',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/devices-to-internet/fig-10.svg',
          width: 720,
          height: 320,
          caption:
              '**Figure 10. Watch which grade moves.** Walking toward '
              'the box changes the Wi-Fi grade. The internet grade '
              'stays the same, because the line to your home did not '
              'change.',
        ),
      ],
    ),
    // ── →. Where this comes from ───────────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where this comes from',
      blocks: <LessonBlock>[
        LessonText(
          'This guide is drawn from Keith Parsons\'s book __Fix Your Own '
          'Wi-Fi__ (WLAN Pros, in preparation, 2026), chapters 1, 2 and 6, '
          'and from its master graphic.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 1, "My Wi-Fi '
              'is broken" (the map; two roads, one box; the four outcomes; '
              'both low together)',
          'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 2, "The two '
              'roads" (the plan upgrade; the hotel; cellular does not use '
              'either road)',
          'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 6, "When it\'s '
              'not the Wi-Fi at all" (the four handoffs; the sign-in page)',
          'WLAN Pros, "How your devices access the Internet", master '
              'graphic, version 3, September 2026 (Figure 2)',
          'WLAN Pros Toolbox, Test My Connection screen: two grades, '
              'measured internet side, Wi-Fi side worked out from the '
              'negotiated rate',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to stop '
              'guessing when something online is slow. The guide is '
              'independent and isn\'t affiliated with any provider or '
              'carrier.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
