// Find My, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   find-my-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kFindMyLesson = GuidedLesson(
  toolId: 'find-my-explained',
  route: '/tools/find-my-explained',
  title: 'Find My, Explained',
  guideTitle: 'Find My, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How Apple finds your people, your phone and your things, including '
      'the AirTag in your suitcase, and what you should turn on before '
      'your next trip.',
  byline: <String>[
    'Keith Parsons · CWNE #3',
    'Current for iOS 27 and watchOS 27 · September 2026',
  ],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/find-my/cover.svg',
    width: 700,
    height: 250,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Find My is one app that finds three kinds of things. It works '
          'on your iPhone, iPad, Mac and Apple Watch.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'People',
            body:
                'Friends and family who choose to share where they are. '
                'Nobody is shared without saying yes.',
          ),
          LessonCardData(
            title: 'Devices',
            body:
                'Your Apple gear. It can be found even with no signal, '
                'and even when it\'s switched off for a while.',
          ),
          LessonCardData(
            title: 'Items',
            body:
                'AirTags and similar tags. They have no GPS. Other '
                'people\'s iPhones find them for you.',
          ),
        ]),
        LessonCallout.note(
          title: 'The one idea behind all of it',
          body:
              'An AirTag can\'t tell anyone where it is. It only '
              'whispers "I\'m here" by Bluetooth. Any iPhone that walks '
              'past hears it and reports its __own__ location. That '
              'report is locked so only you can read it.',
        ),
      ],
    ),
    // ── 2. How a stranger's phone finds your bag ───────────────────────────
    LessonStep(
      number: '2',
      title: 'How a stranger\'s phone finds your bag',
      blocks: <LessonBlock>[
        LessonLede(
          'Your suitcase is on a baggage cart. An AirTag is inside. Nobody '
          'has to do anything for what happens next.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-01.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 1. The Find My network.** The tag whispers. A '
              'passing iPhone hears it and sends its own location, '
              'sealed. Only your devices can open it.',
        ),
        LessonText(
          'A traveler walks by with an iPhone in a pocket. The phone hears '
          'your tag. It sends Apple its own spot, inside a sealed '
          'envelope. Your phone opens the envelope and shows a dot on the '
          'map.',
        ),
        LessonText(
          'The traveler never knows. Apple can\'t read the envelope. Only '
          'you can.',
        ),
      ],
    ),
    // ── 3. Why it stays private ────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Why it stays private',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-02.svg',
          width: 330,
          height: 150,
          maxWidth: 420,
          caption:
              '**Figure 2. The tag keeps changing its name.** Its '
              'radio ID changes every few minutes, so nobody can '
              'follow it by listening.',
        ),
        LessonSteps(<String>[
          '**The key stays with you.** Only your own devices can open '
              'the reports.',
          '**The finder stays anonymous.** Apple doesn\'t know who found '
              'the tag, or whose it is.',
          '**The tag keeps no history.** It doesn\'t store where it has '
              'been.',
        ]),
      ],
    ),
    // ── 4. Where the dot comes from ────────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Where the dot comes from',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-03.svg',
          width: 760,
          height: 290,
          caption:
              '**Figure 3. Your dot is the finder\'s location.** The '
              'tag has no GPS and no Wi-Fi. The phone that heard it '
              'knows where it is, and that becomes your dot.',
        ),
        LessonText(
          'So the dot moves only when someone walks by. In a busy airport, '
          'it moves all the time. In an empty field, it may not move for '
          'hours.',
        ),
      ],
    ),
    // ── 5. Three radios, three jobs ────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Three radios, three jobs',
      blocks: <LessonBlock>[
        LessonLede(
          'Far away, you see a dot on a map. In the same room, you play a '
          'sound. Up close, some iPhones show an arrow.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-04.svg',
          width: 760,
          height: 286,
          caption:
              '**Figure 4. Three radios, three jobs.** The farther '
              'away the tag is, the rougher the answer. Not to scale.',
        ),
        LessonText(
          'The arrow is called Precision Finding. It needs a special radio '
          'called Ultra Wideband in both the phone and the tag. Some '
          'budget iPhones leave it out. They can still see the map and '
          'play a sound.',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**Bluetooth** is the short-range radio your earbuds use. '
              '**Ultra Wideband** is a newer short-range radio that can '
              'tell distance and direction. It powers the arrow.',
        ),
        LessonText(
          'A few countries switch the arrow off. There, you still get the '
          'map and the sound.',
        ),
      ],
    ),
    // ── 6. The app, and sharing with people ────────────────────────────────
    LessonStep(
      number: '6',
      title: 'The app, and sharing with people',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-05.svg',
          width: 760,
          height: 330,
          caption:
              '**Figure 5. The four parts of the app:** People, '
              'Devices, Items and Me. A simple drawing, not a '
              'screenshot.',
        ),
        LessonText(
          'Sharing your location is always your choice. You pick who sees '
          'it and for how long. You can stop any time.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-06.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 6. Three ways to stay in charge of sharing.** '
              'Pause hides you from one person, Check In tells a '
              'friend only if you\'re late, and one tag can be shared '
              'with the family.',
        ),
      ],
    ),
    // ── 7. Your phone, even when it dies ───────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Your phone, even when it dies',
      blocks: <LessonBlock>[
        LessonLede(
          'A phone with a flat battery can still be found for a while. So '
          'can one that\'s switched off.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-07.svg',
          width: 760,
          height: 170,
          caption:
              '**Figure 7. Still findable.** With a signal, your '
              'phone reports itself. With a flat battery or switched '
              'off, it can still be found for a while through the '
              'Find My network.',
        ),
        LessonText(
          'Turn on {{Send Last Location}}. When the battery is almost '
          'gone, your phone sends its spot to Apple first. Step 1 at the '
          'back shows where.',
        ),
        LessonCallout.stop(
          title: 'If a device is lost or stolen',
          body:
              'Mark it as lost in Find My, from another device or at '
              'icloud.com/find. That locks it. Erasing it is the last '
              'step. **Apple will never contact you to say your device '
              'was found.** Never share your passcode or any code with '
              'someone who says they have it.',
        ),
      ],
    ),
    // ── 8. Lost luggage ────────────────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Lost luggage',
      blocks: <LessonBlock>[
        LessonLede(
          'You can send an airline a live link to your bag\'s location. '
          'Many airlines accept it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-08.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 8. If your bag doesn\'t arrive.** Check the '
              'map, file the airline\'s report, then share the link. '
              'Showing your contact info is a separate switch.',
        ),
        LessonHeading('Before you fly'),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-09.svg',
          width: 760,
          height: 278,
          caption:
              '**Figure 9. Before you fly.** Hide the tag inside the '
              'bag, and turn off its left-behind alert (Notify When '
              'Left Behind). Left: do this. Right: not this.',
        ),
        LessonBullets(<String>[
          '**Check the battery** in Find My. It\'s a cheap coin battery, '
              'so swap it before a big trip.',
          '**Name each tag clearly,** like "Blue suitcase".',
        ]),
      ],
    ),
    // ── 9. A tracker that isn't yours ──────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'A tracker that isn\'t yours',
      blocks: <LessonBlock>[
        LessonLede(
          'If someone else\'s tag travels with you, your phone warns you. '
          'iPhones do this, and so do Android phones.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-10.svg',
          width: 760,
          height: 330,
          caption:
              '**Figure 10. What to do if you get an alert.** Find '
              'it, identify it, and if you feel unsafe, go somewhere '
              'public and call the police first.',
        ),
        LessonCallout.stop(
          title: 'Why "police first" matters',
          body:
              'When you pull the battery, the owner stops getting '
              'updates and may notice. If you think someone is following '
              'you on purpose, keep the tag and get help before you '
              'disable it. That\'s our advice, not an Apple rule.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/find-my/fig-11.svg',
          width: 760,
          height: 194,
          caption:
              '**Figure 11. Both phones warn you. Only Android can '
              'also scan.** An iPhone warns you on its own, but has '
              'no button to search the room on demand.',
        ),
      ],
    ),
    // ── 10. Five things people get wrong ───────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Five things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'An AirTag is a GPS tracker.',
          fact:
              'It has no GPS, no Wi-Fi and no cell radio. Its location '
              'comes from iPhones that pass by.',
        ),
        LessonMyth(
          myth: 'Apple can see where my AirTag is.',
          fact: 'The reports are locked with a key only your devices hold.',
        ),
        LessonMyth(
          myth: 'The map updates every few seconds.',
          fact:
              'It updates when an iPhone passes by. That can be often in '
              'an airport and never in a field.',
        ),
        LessonMyth(
          myth: 'My iPhone can scan the room for hidden trackers.',
          fact:
              'It warns you on its own, but has no scan button. Android '
              'phones do.',
        ),
        LessonMyth(
          myth: 'Every iPhone can point an arrow at my AirTag.',
          fact:
              'The arrow needs Ultra Wideband. Budget iPhones can still '
              'see the map and play a sound.',
        ),
      ],
    ),
    // ── A. Step-by-step settings ───────────────────────────────────────────
    LessonStep(
      number: 'A',
      spoken: 'Appendix',
      title: 'Step-by-step settings',
      blocks: <LessonBlock>[
        LessonText(
          'The › symbol means "then tap". Button names can change a little '
          'between updates.',
          small: true,
        ),
        LessonHeading('Get your devices ready'),
        LessonTask(
          title: '1. Turn on Find My for your iPhone',
          why:
              'Do this first. Without it, nothing else in this guide '
              'works for your phone.',
          steps: <String>[
            'Open {{Settings}} › {{[your name]}} › {{Find My}}.',
            'Tap {{Find My iPhone}} and turn it on.',
            'Turn on {{Find My network}}, so the phone can be found while '
                'it\'s offline or switched off.',
            'Turn on {{Send Last Location}}.',
            'Check {{Settings}} › {{Privacy & Security}} › {{Location '
                'Services}} is on.',
          ],
        ),
        LessonTask(
          title: '2. Set up an AirTag',
          why:
              'Turn on Bluetooth first. An AirTag 2 needs the latest '
              'iPhone software.',
          steps: <String>[
            'Pull the plastic tab out of the AirTag. It chimes.',
            'Hold it next to your unlocked iPhone and tap {{Connect}}.',
            'Pick a name, or {{Custom Name}} and an emoji, then '
                '{{Continue}}.',
            'Agree to link it to your Apple Account, then {{Done}}.',
          ],
          after:
              'If the prompt doesn\'t appear: {{Find My}} › {{Items}} › '
              '{{Add}} › {{AirTag}}.',
        ),
        LessonTask(
          title: '3. Change an AirTag\'s name or emoji',
          steps: <String>[
            '{{Find My}} › {{Items}} › tap the tag, then tap the More '
                'button (•••).',
            'Tap {{Change Name and Emoji}}, choose {{Custom Name}}, type '
                'the name and pick an emoji.',
          ],
        ),
        LessonTask(
          title: '4. Share an AirTag with up to five people',
          why: 'Handy for family keys or a shared car.',
          steps: <String>[
            '{{Find My}} › {{Items}} › tap the tag, then tap the More '
                'button (•••).',
            'Tap {{Add Person}} below {{Share AirTag}}, choose the person '
                'and their Apple Account, and send.',
            'To stop: tap the person\'s name › {{Remove}}.',
          ],
        ),
        LessonHeading('Travel and lost items'),
        LessonTask(
          title: '5. Get an alert if you leave something behind',
          why: 'Leave this off for the tag in your checked bag.',
          steps: <String>[
            '{{Find My}} › {{Items}} › tap the tag (or {{Devices}} › a '
                'device), then tap the More button (•••).',
            'Tap {{When Left Behind}}, then turn on {{Notify When Left '
                'Behind}}.',
            'Add places where it\'s fine to leave it, like home: pick a '
                'suggestion or tap {{New Location}}, then {{Done}}.',
          ],
        ),
        LessonTask(
          title: '6. Share a lost item\'s location with an airline',
          steps: <String>[
            'File the airline\'s lost-baggage report first.',
            '{{Find My}} › {{Items}} › tap the tag › {{Share Item '
                'Location}}.',
            'Paste the link into the airline\'s form, or send it to the '
                'agent.',
            'You can see who opened the link, and stop sharing from the '
                'same screen.',
            'Keep at least one of your Apple devices online, or the link '
                'stops updating.',
            'The link can show your phone number or email to the people '
                'you send it to.',
          ],
        ),
        LessonTask(
          title: '7. Mark an AirTag as lost (Show Contact Info)',
          steps: <String>[
            '{{Find My}} › {{Items}} › tap the tag, then tap the More '
                'button (•••).',
            'Below {{Lost AirTag}}, tap {{Show Contact Info}}.',
            'Follow the prompts to enter a phone number and a short '
                'message.',
            'Turn it off in the same place once you have the item back.',
          ],
        ),
        LessonTask(
          title: '8. Use the on-screen arrow (Precision Finding)',
          why: 'Needs a newer iPhone. The budget models don\'t have it.',
          steps: <String>[
            '{{Find My}} › {{Items}} › tap the tag › {{Find}}.',
            'Move slowly and follow the arrow and distance. Tap {{Play '
                'Sound}} if you\'re close.',
            'A newer Apple Watch can do this too, from the Find My app.',
          ],
        ),
        LessonHeading('People'),
        LessonTask(
          title: '9. Share your location with someone',
          steps: <String>[
            '{{Find My}} › {{Me}} › turn on {{Share My Location}}.',
            '{{People}} › {{Add}} › {{Share My Location}} › choose the '
                'person.',
            'Choose how long. {{Custom}} lets you pick your own end time.',
            'For a family group: {{Settings}} › {{Family}} › {{Location '
                'Sharing}}.',
          ],
        ),
        LessonTask(
          title: '10. Use Check In when you head home',
          steps: <String>[
            'In Messages, open the conversation with the person › {{+}} › '
                '{{Check In}}.',
            'Tap {{Edit}} and choose {{When I arrive}} (pick the '
                'destination) or {{After a timer}}.',
            'Tap Send. It ends by itself when you arrive.',
          ],
        ),
        LessonTask(
          title: '11. Pause your location for one person (iOS 27)',
          steps: <String>[
            '{{Find My}} › {{People}} › tap the person\'s name.',
            'Tap {{More}}, then {{Hide Location}}.',
          ],
        ),
        LessonHeading('Safety and upkeep'),
        LessonTask(
          title: '12. If you get "AirTag Found Moving With You"',
          steps: <String>[
            'Tap the alert › {{Continue}}.',
            'Tap {{Play Sound}}, or {{Find Nearby}} if your iPhone offers '
                'it.',
            'Hold the top of your iPhone to the white side of the tag and '
                'screenshot what appears.',
            'If you feel unsafe, go somewhere public and contact police. '
                'Otherwise tap {{Instructions to Disable}} and remove the '
                'battery.',
          ],
        ),
        LessonTask(
          title: '13. Change an AirTag\'s battery',
          steps: <String>[
            'Press the steel cover and turn it counterclockwise until it '
                'stops, then lift it off.',
            'Put in a new coin battery (CR2032), + side up. Buy packs '
                'marked "Compatible with Apple AirTag".',
            'Line up the three tabs, press and turn clockwise until it '
                'stops.',
          ],
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked against Apple\'s pages in September 2026.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Apple Platform Security Guide, Find My: '
              'support.apple.com/guide/security/sec6cbc80fd0',
          'Apple 102648, Find My network and Send Last Location',
          'Apple 102515, Location Services and privacy (GPS, Wi-Fi and '
              'cellular positioning)',
          'Apple 126203, AirTag (2nd generation) technical '
              'specifications; Apple 111847, AirTag (1st generation)',
          'Apple 109512, Precision Finding and Ultra Wideband '
              'availability by device and country',
          'Apple 120373, Find My on Apple Watch (watchOS 27)',
          'Apple 105104, share your location; Apple 105107, Family '
              'Sharing location',
          'Apple 104978, if your device or item is lost',
          'Apple 102414, Notify When Left Behind',
          'Apple 119874, unwanted tracking alerts',
          'Apple 101602, set up AirTag (32-item limit, iOS 26.2.1 for '
              'AirTag 2)',
          'Apple 102600, replace the AirTag battery',
          'Apple Newsroom, 2024-05-13: cross-platform unwanted tracking '
              'alerts',
          'Apple Newsroom, 2024-11-13: Share Item Location',
          'Apple Newsroom, 2026-01-26: AirTag (2nd generation)',
          'apple.com/airtag and apple.com/icloud/find-my (network size, '
              '"over a billion" devices)',
          'Apple Personal Safety User Guide: Check In, Find My and '
              'location sharing',
          'Google Android Help 13658562: unknown tracker alerts and Scan '
              'now',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to know '
              'what Find My does before they need it. Apple, AirTag, '
              'iPhone, Apple Watch and Find My are trademarks of Apple '
              'Inc. This guide is independent and isn\'t affiliated with '
              'or endorsed by Apple.',
        ),
      ],
    ),
  ],
);
