// How GPS Works, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   how-gps-works-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kHowGpsWorksLesson = GuidedLesson(
  toolId: 'how-gps-works-explained',
  route: '/tools/how-gps-works-explained',
  title: 'How GPS Works, Explained',
  guideTitle: 'How GPS Works, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How your phone finds itself by listening to satellites, and what to '
      'do when the blue dot gets it wrong.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/how-gps-works/cover.svg',
    width: 616,
    height: 400,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone finds itself by listening. Satellites high above the '
          'Earth send out the time. Your phone hears several of them and '
          'works out where it is. It never sends anything back.',
        ),
        LessonText(
          'This guide answers three questions. What is GPS? Why does it '
          'matter to you? And what can you do when your blue dot is wrong?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**GPS** stands for Global Positioning System. It\'s the '
              'American set of satellites. Your phone also listens to '
              'satellites run by Europe, China and others. The chip in '
              'your phone that listens is called the **receiver**.',
        ),
        LessonCallout.note(
          title: 'What this guide leaves out',
          body:
              'Indoors, your phone leans on Wi-Fi and cell towers '
              'instead. That story has its own guide: __How Your Phone '
              'Knows Where It Is, Explained__.',
        ),
        LessonToolLink('where-your-phone-is-explained'),
      ],
    ),
    // ── 2. Satellites that send the time ───────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Satellites that send the time',
      blocks: <LessonBlock>[
        LessonLede(
          'About 30 GPS satellites circle the Earth, far higher than the '
          'Space Station. Each one carries a clock that almost never '
          'drifts.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-01.svg',
          width: 616,
          height: 214,
          caption:
              '**Figure 1. What a satellite sends.** Every GPS '
              'satellite sends the same two things, over and over: '
              'the time, and where it is. That\'s all GPS sends.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-02.svg',
          width: 616,
          height: 372,
          caption:
              '**Figure 2. GPS only goes one way.** The satellites '
              'talk and your phone listens. If an app shares where '
              'you are, that happens later, over Wi-Fi or cell data. '
              'You control it in your phone\'s settings.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-03.svg',
          width: 616,
          height: 236,
          caption:
              '**Figure 3. No bars, still a dot.** Your phone only '
              'listens, so GPS works with no cell plan and no '
              'internet.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-04.svg',
          width: 616,
          height: 470,
          caption:
              '**Figure 4. Everyone, everywhere.** The satellites '
              'send to the whole Earth at once, so any phone can '
              'listen, for free. Not to scale.',
        ),
      ],
    ),
    // ── 3. Four satellites, one spot ───────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Four satellites, one spot',
      blocks: <LessonBlock>[
        LessonLede(
          'A radio signal is fast, but it isn\'t instant. It takes a tiny '
          'moment to reach you. Your phone measures that moment. A longer '
          'wait means that satellite is farther away.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-05.svg',
          width: 616,
          height: 250,
          caption:
              '**Figure 5. Farther away, longer wait.** The wait '
              'tells your phone how far away each satellite is. Not '
              'to scale.',
        ),
        LessonText(
          'The timing has to be exact. In a billionth of a second, the '
          'signal travels about 30 cm (1 foot).',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-06.svg',
          width: 616,
          height: 280,
          caption:
              '**Figure 6. A tiny slip, a big miss.** A clock that is '
              'off by a hair puts your dot far from where you stand. '
              'Not to scale.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-07.svg',
          width: 616,
          height: 556,
          caption:
              '**Figure 7. Why it takes four.** Each satellite tells '
              'your phone how far away it is. Three distances meet at '
              'one spot. The fourth satellite corrects your phone\'s '
              'clock, which isn\'t as good as the ones in space. '
              'Drawn flat, not to scale.',
        ),
        LessonText(
          'Most of the time your phone can hear far more than four. More '
          'satellites give a better answer.',
        ),
        LessonCallout.note(
          title: 'A fun fact',
          body:
              'Einstein is part of every map app. Clocks in orbit tick '
              'at a slightly different speed than clocks on the ground. '
              'GPS corrects for that every day. Without the fix, your '
              'dot would slowly wander off.',
        ),
      ],
    ),
    // ── 4. Where GPS works, and where it doesn't ───────────────────────────
    LessonStep(
      number: '4',
      title: 'Where GPS works, and where it doesn\'t',
      blocks: <LessonBlock>[
        LessonLede(
          'GPS needs to see the sky. Anything overhead gets in the way.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-08.svg',
          width: 616,
          height: 372,
          caption:
              '**Figure 8. Open sky is best.** Tall buildings bounce '
              'the signal around. Leaves weaken it. A roof blocks '
              'most of it.',
        ),
        LessonText('On a city street, your phone may see only a strip of sky.'),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-09.svg',
          width: 616,
          height: 230,
          caption:
              '**Figure 9. A strip of sky.** Looking straight up from '
              'a city street, tall buildings hide most of the '
              'satellites.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-10.svg',
          width: 616,
          height: 560,
          caption:
              '**Figure 10. Why the dot jumps across the street.** A '
              'bounced signal travels farther, so your phone thinks '
              'that satellite is farther away than it is. Not to '
              'scale.',
        ),
        LessonText(
          'Indoors, GPS mostly gives up. Your phone switches to Wi-Fi and '
          'cell towers instead.',
        ),
        LessonHeading('Why it can be slow to start'),
        LessonText(
          'After your phone has been off, or after a long flight, it has '
          'to find the satellites again. That can take a minute.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-11.svg',
          width: 616,
          height: 452,
          caption:
              '**Figure 11. A head start.** With a data connection, '
              'your phone is told where to look, so it finds you in '
              'seconds.',
        ),
      ],
    ),
    // ── 5. When the dot is wrong on purpose ────────────────────────────────
    LessonStep(
      number: '5',
      title: 'When the dot is wrong on purpose',
      blocks: <LessonBlock>[
        LessonLede(
          'Some people use gadgets that drown out GPS. That\'s called '
          'jamming, and it\'s illegal in the US. Your dot freezes or '
          'disappears.',
        ),
        LessonText(
          'A rarer trick sends fake satellite signals. That\'s called '
          'spoofing. It can move your dot to a place you\'ve never been.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-12.svg',
          width: 616,
          height: 420,
          caption:
              '**Figure 12. Two ways to fool GPS.** Jamming drowns '
              'out the real signal. Spoofing fakes it.',
        ),
        LessonText(
          'You can\'t stop either one. If your dot looks wrong, trust your '
          'eyes and the road signs. Your phone falls back on Wi-Fi and '
          'cell towers where it can.',
        ),
      ],
    ),
    // ── 6. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'GPS tracks me.',
          fact:
              'The satellites only send. They can\'t hear your phone at '
              'all. An app gets your exact location only if you let it.',
        ),
        LessonMyth(
          myth: 'GPS needs cell data.',
          fact:
              'Your position comes from the satellites alone. Data only '
              'helps it start faster and loads the map.',
        ),
        LessonMyth(
          myth: 'GPS works indoors.',
          fact:
              'Mostly not. A roof blocks the signal. Indoors, your phone '
              'uses Wi-Fi and cell towers instead.',
        ),
        LessonMyth(
          myth: 'My phone knows exactly where I am.',
          fact:
              'Outdoors, it\'s usually within about 5 m (16 feet). Near '
              'tall buildings or under trees, it can be off by much more.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-13.svg',
          width: 616,
          height: 210,
          caption:
              '**Figure 13. The circle around the dot.** A small '
              'circle means a close fix. Tall buildings make it '
              'bigger. Not to scale.',
        ),
      ],
    ),
    // ── 7. Tips for a better fix ───────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Tips for a better fix',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/how-gps-works/fig-14.svg',
          width: 616,
          height: 420,
          caption:
              '**Figure 14. Two easy wins.** Keep the phone where it '
              'can see the sky, and save the map before you lose '
              'signal.',
        ),
        LessonSteps(<String>[
          '**Step outside, or stand by a window.** GPS finds you fastest '
              'under open sky.',
          '**Keep your phone where it can see the sky.** In a car, a '
              'dash mount beats a cup holder or a pocket.',
          '**Download maps before you travel.** Then saved areas work '
              'with no signal.',
          '**Give it a moment in a city.** If the dot jumps around, wait '
              'a few seconds or walk to a wider street.',
          '**Check which apps can see your location.** Turn it off for '
              'any app that doesn\'t need it.',
        ]),
        LessonCallout.note(
          title: 'Privacy lives in your settings',
          body:
              'GPS itself tracks no one. Which apps get your location is '
              'up to you. On iPhone, look in Settings, then Privacy & '
              'Security. On Android, look in Settings, then Location.',
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText('Checked on 28 September 2026.'),
        LessonSourceList(<String>[
          'GPS.gov: Space Segment (figures dated 3 July 2023); GPS '
              'Accuracy; Frequently Asked Questions; New Civil Signals; GPS '
              'Legislation (10 U.S.C. § 2281)',
          'US Space Force, Mission Delta 31, briefing to the Civil GPS '
              'Service Interface Committee, as of 13 April 2026, hosted on '
              'gps.gov',
          'US Coast Guard Navigation Center, GPS Frequently Asked '
              'Questions',
          'NIST, "Putting Einstein to the Test"',
          'van Diggelen and Enge, ION GNSS+ 2015 (the source of '
              'GPS.gov\'s 4.9 m (16 feet) phone figure)',
          'United Nations Office for Outer Space Affairs, Global '
              'Navigation Satellite Systems',
          'Google Maps Help 6291838, download areas and use offline maps',
          'FCC, Jammer Enforcement (fcc.gov/general/jammer-enforcement)',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to know '
              'what their phone is doing when it shows a dot on a map. '
              'It is independent, and isn\'t affiliated with or endorsed '
              'by any government agency, satellite operator or phone '
              'maker.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
