// Mesh, Extenders and Wired Access Points, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   mesh-extenders-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kMeshExtendersLesson = GuidedLesson(
  toolId: 'mesh-extenders-explained',
  route: '/tools/mesh-extenders-explained',
  title: 'Mesh, Extenders and Wired Access Points, Explained',
  guideTitle: 'Mesh, Extenders and Wired Access Points, Explained',
  tagline: 'A plain-English guide',
  promise:
      'Three ways to fix a dead zone. Know which one fits your home before '
      'you spend money, and where to put it.',
  byline: <String>['Keith Parsons · CWNE #3', 'WLAN Pros · September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/mesh-extenders/cover.svg',
    width: 700,
    height: 190,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Every box you add to fix a dead zone needs its own link back to '
          'your main box. That link decides how fast the far room will be.',
        ),
        LessonText(
          'Three kinds of gear are sold for the same problem: extenders, '
          'mesh kits and wired access points. The name on the box matters '
          'less than one question. How does the new box talk to the main '
          'one?',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-01.svg',
          width: 720,
          height: 130,
          caption:
              '**Figure 1. Every added box needs a link back.** The '
              'added box can only pass on what reaches it from the '
              'main box. The highlighted link back sets the speed in '
              'the far room.',
        ),
        LessonCallout.note(
          title: 'The one big idea',
          body:
              'A box that uses one radio to talk to your main box and to '
              'you has to take turns. Give the link back its own radio, '
              'or better, a cable.',
        ),
        LessonCallout.note(
          title: 'Three words used in this guide',
          body:
              '**Main box:** the box your internet comes into. **Access '
              'point:** a box whose job is to make Wi-Fi. **Link back:** '
              'how an extra box reaches the main box, through the air or '
              'over a cable.',
        ),
      ],
    ),
    // ── 2. Three ways to fill a dead zone ──────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Three ways to fill a dead zone',
      blocks: <LessonBlock>[
        LessonLede(
          'All three put a second source of Wi-Fi closer to the far room. '
          'They differ in how they link back to the main box.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-02.svg',
          width: 720,
          height: 300,
          caption:
              '**Figure 2. Same far room, three kinds of link back.** '
              'Dotted lines go through the air. A solid line is a '
              'cable. Green is the hop to you. Blue is a radio used '
              'only for the link back.',
        ),
        LessonBullets(<String>[
          '**Extender.** One small box, often plugged into a wall '
              'socket. Most use one radio for everything. Cheapest, and '
              'fussiest about where you put it.',
          '**Mesh kit.** Two or more units that act as one network, with '
              'one name and one app. Some have a spare radio for the link '
              'back.',
          '**Wired access point.** Makes Wi-Fi in the far room and links '
              'back over a cable. Fastest. The cable is the work.',
        ]),
      ],
    ),
    // ── 3. One radio, two jobs ─────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'One radio, two jobs',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi devices on the same channel share it, so they mostly take '
          'turns.',
        ),
        LessonText(
          'An extender with one radio has two jobs. First it hears a piece '
          'of your video from the main box. Then it repeats that piece to '
          'your laptop. It can\'t do both at once.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-03.svg',
          width: 720,
          height: 330,
          caption:
              '**Figure 3. One radio shares its time.** Top: with one '
              'radio, the hop to the main box and the hop to you take '
              'turns. Bottom: with a separate radio or a cable, both '
              'hops work at the same time.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“Plenty of travel routers carry a single radio and repeat '
              'instead, so the same radio alternates between talking to '
              'the public network and talking to you. It works, and it '
              'costs you throughput.”',
          attribution:
              'From Keith\'s LinkedIn post on travel routers, 3 '
              'September 2026. The same trade applies to a '
              'one-radio extender at home.',
        ),
      ],
    ),
    // ── 4. Why it can cut your speed in half ───────────────────────────────
    LessonStep(
      number: '4',
      title: 'Why it can cut your speed in half',
      blocks: <LessonBlock>[
        LessonLede(
          'Every piece of your video crosses the air twice. The two trips '
          'share the same time. So two equally good hops give you about '
          'half the speed.',
        ),
        LessonText(
          'It gets worse when one hop is weak. Say the extender sits right '
          'next to your laptop, but far from the main box. Your bars look '
          'full. But the slow link back eats most of the time.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-04.svg',
          width: 720,
          height: 150,
          caption:
              '**Figure 4. Where the time goes.** Top: the slow link '
              'back takes nearly all the time, and the fast hop to '
              'the laptop gets a sliver. Bottom: two equal hops split '
              'the time evenly.',
        ),
        LessonCallout.note(
          title: 'Where these numbers come from',
          body:
              'They come from a model in the Wireless Classroom in the '
              'WLAN Pros Toolbox: one long, open hallway, with typical '
              'settings. Your walls and your gear will change every '
              'number. The pattern stays the same.',
        ),
        LessonToolLink('repeater-mesh'),
      ],
    ),
    // ── 5. Where to put it ─────────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Where to put it',
      blocks: <LessonBlock>[
        LessonLede(
          'The natural move is to plug the new box in where the Wi-Fi is '
          'bad. That\'s the one spot where it can barely hear the main box.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-05.svg',
          width: 720,
          height: 290,
          caption:
              '**Figure 5. Same extender, two spots.** A: in the dead '
              'zone, the link back is weak, and the laptop ends up '
              'slower than with no extender at all. B: partway down '
              'the hall, both hops are strong, and the laptop gets '
              'far more.',
        ),
        LessonText(
          'Put it partway, where the main box is still strong. In a real '
          'home, the walls decide where that spot is. Go by the signal, '
          'not the tape measure.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“Do not grab the cheapest range extender and plug it in '
              'halfway down the hall. A badly placed extender repeats a '
              'weak signal and adds a second weak hop on top of it, and '
              'you end up with more bars and less working Wi-Fi.”',
          attribution: 'From __Fix Your Own Wi-Fi__, chapter 5.',
        ),
      ],
    ),
    // ── 6. Five setups, one far room ───────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Five setups, one far room',
      blocks: <LessonBlock>[
        LessonLede(
          'Here\'s the same laptop in the same far room, reached five '
          'different ways. The numbers are speeds in megabits per second, '
          'from the same Classroom model.',
        ),
        LessonToolLink('repeater-mesh'),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-06.svg',
          width: 720,
          height: 310,
          caption:
              '**Figure 6. What the laptop gets, five ways.** Each '
              'bar is drawn to an even, ruler-style scale. Longer is '
              'faster.',
        ),
        LessonSteps(<String>[
          '**Straight to the main box.** Weak, but it works. This is the '
              'starting point.',
          '**Extender in the dead zone.** Full bars, and slower than '
              'doing nothing.',
          '**Extender partway.** Same box, moved. Now it helps.',
          '**Mesh unit partway, with its own radio for the link back.** '
              'About three times the starting speed.',
          '**Wired access point.** The link back is a cable. About eight '
              'times the starting speed.',
        ]),
      ],
    ),
    // ── 7. Four ways to build the link back ────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Four ways to build the link back',
      blocks: <LessonBlock>[
        LessonLede(
          'If anything here is worth money or an afternoon, it\'s the link '
          'back. Here are four ways, best first.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-07.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 7. Four links back, best first.** Network '
              'cable and TV cable may already be in your walls. The '
              'third stays in the air on a radio of its own. The '
              'fourth rides your electrical wiring.',
        ),
        LessonSteps(<String>[
          '**Network cable.** The best. Many mesh units have a port for '
              'it. Check before you buy.',
          '**TV cable.** A pair of adapters called MoCA can turn a TV '
              'cable outlet into a fast network link.',
          '**A separate radio for the link back.** Look for the words '
              '__dedicated backhaul__ on the box. "Tri-band" alone doesn\'t '
              'promise it.',
          '**Powerline adapters.** They send data through your home\'s '
              'wiring. Results vary, so test at home first.',
        ]),
      ],
    ),
    // ── 8. Wired access points ─────────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Wired access points',
      blocks: <LessonBlock>[
        LessonLede(
          'An access point has one job: make Wi-Fi. Fed by a cable, its '
          'whole radio is free to talk to the room it serves.',
        ),
        LessonText(
          'This is how offices, schools and hotels are built. It works the '
          'same way at home.',
        ),
        LessonBullets(<String>[
          '**Look for cable you already have.** A network jack in the '
              'far room may already reach your main box.',
          '**Keep one network name.** Give it the same name and password '
              'as your main box.',
          '**Put it where people sit.** Open, central and off the floor.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-08.svg',
          width: 720,
          height: 252,
          caption:
              '**Figure 8. One cable does both jobs.** Many access '
              'points take their power over the network cable, so '
              'this one needs no outlet on the ceiling. The power '
              'adapter plugs in next to the main box.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“you have stopped having a settings problem and started '
              'having a coverage problem. The answer to that is another '
              'Wi-Fi unit, properly placed, a mesh node or a second '
              'access point. It is not a bigger internet plan, which '
              'buys you nothing on this road at all.”',
          attribution:
              'From __Fix Your Own Wi-Fi__, chapter 5, "When '
              'moving the box is not enough."',
        ),
        LessonCallout.note(
          title: 'When the cable is the hard part',
          body:
              'Running a cable through walls is where this stops being a '
              'couch job. Get a quote from an electrician or a network '
              'installer for one run to the far room.',
        ),
      ],
    ),
    // ── 9. Which one should you buy? ───────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Which one should you buy?',
      blocks: <LessonBlock>[
        LessonLede(
          'Two checks come first. Make sure the slow part is the Wi-Fi, '
          'not your internet line. Then move the main box up and into the '
          'open, and test again.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-09.svg',
          width: 720,
          height: 360,
          caption:
              '**Figure 9. Work down the questions.** Every "yes" is '
              'a better link back than the answer below it. A cable, '
              'even a TV cable, beats any radio link.',
        ),
        LessonText(
          '__How Your Devices Access the Internet, Explained__ shows how '
          'to tell a Wi-Fi problem from an internet problem.',
        ),
        LessonToolLink('devices-to-internet-explained'),
        LessonCallout.note(
          title: 'Mixing brands',
          body:
              'Plan on buying every mesh unit from the same maker. If '
              'you want to mix, look for __Wi-Fi CERTIFIED EasyMesh__ on '
              'every unit.',
        ),
      ],
    ),
    // ── 10. Five things people get wrong ───────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Five things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'An extender adds speed.',
          fact:
              'An extender adds reach. With one radio, it spends part of '
              'every second talking to the main box. That time comes out '
              'of your time.',
        ),
        LessonMyth(
          myth: 'Put the new box in the dead zone.',
          fact:
              'Put it partway, where the main box is still strong. In '
              'the dead zone, its own link back is the weakest link in '
              'the house.',
        ),
        LessonMyth(
          myth: 'More mesh units are always better.',
          fact:
              'Each unit that relays through the air adds another turn '
              'on the channel. One well-placed unit with a cable can '
              'beat three that relay.',
        ),
        LessonMyth(
          myth: 'Mesh and extenders are the same thing at different prices.',
          fact:
              'A mesh kit runs as one network with one app. But for '
              'speed, what matters is the link back, not the label.',
        ),
        LessonMyth(
          myth: 'A wired link back is only for experts.',
          fact:
              'A cable is the single biggest upgrade for a far room. In '
              'this guide\'s model, it made the far room about eight '
              'times faster.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-10.svg',
          width: 720,
          height: 188,
          caption:
              '**Figure 10. Every relay takes a turn.** Units that '
              'relay through the air take turns on the channel, one '
              'hop at a time. A cable takes the link back out of the '
              'air.',
        ),
      ],
    ),
    // ── 11. After you set it up ────────────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'After you set it up',
      blocks: <LessonBlock>[
        LessonSteps(<String>[
          '**Test in the chair where it used to be slow.** Compare with '
              'your reading from before.',
          '**Check the app\'s rating for each unit\'s link back.** If '
              'one reads weak, move it one step closer to the main box.',
          '**Test near each unit too,** so you know the whole house got '
              'better.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/mesh-extenders/fig-11.svg',
          width: 720,
          height: 214,
          caption:
              '**Figure 11. Same chair, same test.** Test in the '
              'chair that used to be slow, before and after. If the '
              'new unit helped, the chair shows it. Not to scale.',
        ),
      ],
    ),
    // ── →. Where this comes from ───────────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where this comes from',
      blocks: <LessonBlock>[
        LessonSourceList(<String>[
          'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, in '
              'preparation, 2026), chapter 5, "When moving the box is not '
              'enough" and "Fix four: get the box up and out" (quotes in '
              'steps 5 and 8; open, central, unobstructed)',
          'Keith Parsons, LinkedIn post on travel routers, 3 September '
              '2026 (step 3 quote)',
          'WLAN Pros Toolbox, Wireless Classroom, Repeaters and Mesh '
              'Backhaul (2026): for one radio relaying on one channel, 1/T = '
              '1/T1 + 1/T2; with a dedicated backhaul radio, the slower hop; '
              'with a wired backhaul, the last hop only. Derived from shared '
              'airtime. Illustrative settings: log-distance path loss '
              '(exponent 3.0), 20 dBm, 802.11ax, 80 MHz at 5 GHz, two '
              'streams, efficiency 0.6 (steps 4 to 6, 10)',
          'Google Nest Help, device placement page '
              '(support.google.com/googlenest/answer/7183150), read 27 '
              'September 2026 (step 5; "mesh test", step 11)',
          'Google Nest Help, "Hardwire Nest Wifi Pro, Nest Wifi, or '
              'Google Wifi with Ethernet" '
              '(support.google.com/googlenest/answer/7215624), read 27 '
              'September 2026: "wired backhaul" over Ethernet; some units '
              '"can\'t be hardwired" (step 7)',
          'Ofcom, consumer advice on improving home Wi-Fi, published 19 '
              'February 2024 '
              '(ofcom.org.uk/phones-and-broadband/coverage-and-speeds/improving-your-wifi-experience): '
              'powerline depends on your wiring; Ethernet often beats Wi-Fi; '
              'place the router centrally, off the floor (steps 7 and 8)',
          'Multimedia over Coax Alliance, "MoCA Home 2.5" '
              '(mocalliance.org/moca), read 27 September 2026: 2.5 Gbps over '
              'existing coax (step 7)',
          'Wi-Fi Alliance, "Wi-Fi EasyMesh" (wi-fi.org), read 27 '
              'September 2026: multiple APs forming "a unified network", '
              'with "EasyMesh APs from multiple vendors" (step 9)',
          'IEEE 802.3 (Ethernet): 1000BASE-T runs up to 100 m (328 feet) '
              'over twisted-pair cabling; Power over Ethernet (IEEE 802.3af, '
              'at and bt) carries power on the same cable (steps 7 and 8)',
        ]),
        LessonToolLink('repeater-mesh'),
        LessonHeading('Related guides'),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'How Your Devices Access the Internet, Explained',
            body:
                'Which hop is slow: your Wi-Fi, your internet feed, or '
                'the service.',
          ),
          LessonCardData(
            title: 'Home Internet, Explained',
            body:
                'Fiber, cable, DSL, 5G and satellite: the feed your main '
                'box sits on.',
          ),
        ]),
        LessonToolLink('devices-to-internet-explained'),
        LessonToolLink('home-internet-explained'),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Google, Ofcom, the MoCA Alliance and the Wi-Fi Alliance '
              'are cited from their own published pages; none of them '
              'had a part in this guide, and it is not an endorsement. '
              'The guide is independent and isn\'t affiliated with any '
              'maker or provider.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
