// Mobile Hotspots, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   mobile-hotspots-explained--SOURCE.html
//   myPKA commit 68a0cfdf 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kMobileHotspotsLesson = GuidedLesson(
  toolId: 'mobile-hotspots-explained',
  route: '/tools/mobile-hotspots-explained',
  title: 'Mobile Hotspots, Explained',
  guideTitle: 'Mobile Hotspots, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How a small box, or your phone, turns cell signal into Wi-Fi, and '
      'how to get the most from it.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/mobile-hotspots/cover.svg',
    width: 616,
    height: 360,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'A mobile hotspot takes the cell signal your phone uses and '
          'turns it into Wi-Fi. Your laptop and tablet join that Wi-Fi, '
          'just like at home. The hotspot can be a small box of its own, '
          'or your phone.',
        ),
        LessonText(
          'This guide answers three questions. What is a hotspot? What '
          'makes it fast or slow? And how do you use it well?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'A **cell tower** is the mast that sends and receives '
              'phone signal. **Wi-Fi** is the short-range radio your '
              'laptop uses. A **hotspot** joins the two. Here, '
              '**tethering** means sharing your phone\'s cell data.',
        ),
        LessonCallout.note(
          title: 'What this guide leaves out',
          body:
              '__Travel Routers, Explained__ covers sharing hotel Wi-Fi. '
              '__Phone Data Abroad, Explained__ covers data plans in '
              'other countries. __Weak Cell Signal at Home, Explained__ '
              'covers boosters. __Home Internet, Explained__ compares a '
              'hotspot with other ways to get internet at home.',
        ),
        LessonToolLink('travel-routers-explained'),
        LessonToolLink('phone-data-abroad-explained'),
        LessonToolLink('weak-cell-signal-explained'),
        LessonToolLink('home-internet-explained'),
      ],
    ),
    // ── 2. Cell signal in, Wi-Fi out ───────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Cell signal in, Wi-Fi out',
      blocks: <LessonBlock>[
        LessonLede(
          'A hotspot has two radios. One talks to a cell tower. The other '
          'makes Wi-Fi for your devices.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-01.svg',
          width: 616,
          height: 404,
          caption:
              '**Figure 1. Two radios in one box.** The cell radio '
              'brings the internet in. The Wi-Fi radio hands it out '
              'to your laptop, tablet and phone.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-02.svg',
          width: 616,
          height: 210,
          caption:
              '**Figure 2. One chain, three links.** The tower is far '
              'away. Your laptop is close. The hotspot sits in the '
              'middle and joins them.',
        ),
      ],
    ),
    // ── 3. Two kinds of hotspot ────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Two kinds of hotspot',
      blocks: <LessonBlock>[
        LessonLede(
          'A pocket hotspot is a small box that does only this job. Your '
          'phone can do the same job with a setting.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-03.svg',
          width: 616,
          height: 300,
          caption:
              '**Figure 3. Same job, two kinds.** A pocket hotspot '
              'needs its own cell service, on a SIM card or a '
              'built-in eSIM, and has its own battery. Your phone\'s '
              'hotspot shares the phone\'s.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-04.svg',
          width: 616,
          height: 300,
          caption:
              '**Figure 4. Turn it on, then join it.** On an iPhone '
              'the setting is called Personal Hotspot. On Android '
              'it\'s called Wi-Fi hotspot.',
        ),
      ],
    ),
    // ── 4. How it works, in pictures ───────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'How it works, in pictures',
      blocks: <LessonBlock>[
        LessonLede(
          'Every web page makes a round trip. It goes out through the '
          'hotspot and the tower, and comes back the same way.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-05.svg',
          width: 616,
          height: 270,
          caption:
              '**Figure 5. Out and back.** Your laptop asks. The '
              'hotspot passes it to the tower, and the tower sends it '
              'through the phone company\'s network to the website. '
              'The page comes back the same way.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-06.svg',
          width: 616,
          height: 214,
          caption:
              '**Figure 6. One short link, one long one.** Wi-Fi only '
              'has to cross the table. The cell link has to reach a '
              'tower that may be across town.',
        ),
      ],
    ),
    // ── 5. What decides the speed ──────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'What decides the speed',
      blocks: <LessonBlock>[
        LessonLede(
          'Two things decide how fast a hotspot feels. The first is the '
          'cell signal where you are.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-07.svg',
          width: 616,
          height: 220,
          caption:
              '**Figure 7. The narrow part wins.** When you sit near '
              'the hotspot, the narrow part is usually the cell link, '
              'not the Wi-Fi.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-08.svg',
          width: 616,
          height: 300,
          caption:
              '**Figure 8. Where you are matters.** Close to a tower '
              'with a clear view, the signal is strong. Far away, or '
              'behind walls, it\'s weak and slower.',
        ),
        LessonText(
          'Your laptop\'s Wi-Fi bars show only the short link to the '
          'hotspot. To judge the speed, look at the cell bars on the '
          'hotspot or the phone. Cell bars help, but they don\'t promise '
          'speed. A busy tower can be slow even with full bars.',
        ),
      ],
    ),
    // ── 6. A busy network ──────────────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'A busy network',
      blocks: <LessonBlock>[
        LessonLede(
          'The second thing is how many people share the tower. A busy '
          'place can feel slow, even with full bars.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-09.svg',
          width: 616,
          height: 300,
          caption:
              '**Figure 9. A tower is shared.** Everyone near a tower '
              'shares it. At a game or a busy airport, there is less '
              'to go around, so many people slow down.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-10.svg',
          width: 616,
          height: 200,
          caption:
              '**Figure 10. Some data waits its turn.** On some '
              'plans, when the network is busy, your data gets lower '
              'priority, so it can be slower. When it\'s quiet, '
              'there\'s no line.',
        ),
      ],
    ),
    // ── 7. Data and your plan ──────────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Data and your plan',
      blocks: <LessonBlock>[
        LessonLede(
          'A hotspot uses your cell data. A laptop can use a lot of it '
          'without asking.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-11.svg',
          width: 616,
          height: 268,
          caption:
              '**Figure 11. Check the hotspot line.** Some plans '
              'limit hotspot data or charge extra for it. Check your '
              'plan, or ask your carrier.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-12.svg',
          width: 616,
          height: 288,
          caption:
              '**Figure 12. Turn on data saver.** Turn it on for the '
              'hotspot\'s network, on the device that joins it. It\'s '
              'called Low Data Mode on an iPhone or iPad, and Metered '
              'connection on a Windows laptop. It holds back many '
              'updates and backups, but not everything.',
        ),
        LessonText(
          'Using a hotspot in another country? See __Phone Data Abroad, '
          'Explained__ first.',
        ),
        LessonToolLink('phone-data-abroad-explained'),
      ],
    ),
    // ── 8. Battery and heat ────────────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Battery and heat',
      blocks: <LessonBlock>[
        LessonLede(
          'Sharing data is hard work for a small radio. It uses battery, '
          'and it makes heat.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-13.svg',
          width: 616,
          height: 270,
          caption:
              '**Figure 13. Plug it in for long use.** On battery, a '
              'hotspot runs down fast. When it\'s plugged in, keep it '
              'cool and in the open. On Android, you can also set it '
              'to turn off when no one is using it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-14.svg',
          width: 616,
          height: 270,
          caption:
              '**Figure 14. Keep it cool.** When a phone gets too '
              'hot, charging slows and its cell signal can weaken. '
              'Keep it out of the sun and out of a hot car.',
        ),
      ],
    ),
    // ── 9. Where to put it ─────────────────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Where to put it',
      blocks: <LessonBlock>[
        LessonLede(
          'Put the hotspot where the cell signal is best. That is often '
          'near a window, out in the open.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-15.svg',
          width: 616,
          height: 360,
          caption:
              '**Figure 15. Near a window.** Walls and roofs weaken '
              'cell signal. A window often lets more of it in, so try '
              'a few.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-16.svg',
          width: 616,
          height: 212,
          caption:
              '**Figure 16. Not in a bag.** Give it air. A bag traps '
              'heat, and heat slows it down.',
        ),
        LessonText(
          'To find the best spot, watch the cell bars on the hotspot as '
          'you move it around. __Weak Cell Signal at Home, Explained__ has '
          'more ways to find it.',
        ),
        LessonToolLink('weak-cell-signal-explained'),
      ],
    ),
    // ── 10. Other ways to share ────────────────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Other ways to share',
      blocks: <LessonBlock>[
        LessonLede('Wi-Fi is the usual way to share. A phone has two more.'),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-17.svg',
          width: 616,
          height: 318,
          caption:
              '**Figure 17. Three ways to share.** Wi-Fi reaches '
              'several devices. A cable or Bluetooth reaches one.',
        ),
        LessonBullets(<String>[
          '**USB tethering:** plug a cable from your phone into one '
              'laptop. Some pairs need extra setup, and an Android phone '
              'can\'t do this with a Mac.',
          '**Bluetooth tethering:** pair your phone with one nearby '
              'device, then share over Bluetooth.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-18.svg',
          width: 616,
          height: 200,
          caption:
              '**Figure 18. Your hotspot has a name.** Anyone nearby '
              'can see it. On an iPhone, it is the phone\'s name: '
              'change it in Settings, General, About, Name. On '
              'Android, tap the hotspot name to change it.',
        ),
      ],
    ),
    // ── 11. Keep it private ────────────────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Keep it private',
      blocks: <LessonBlock>[
        LessonLede(
          'Your hotspot is your own small Wi-Fi network. Lock it, and turn '
          'it off when you\'re done.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-19.svg',
          width: 616,
          height: 290,
          caption:
              '**Figure 19. Use a strong password.** Some phones let '
              'you pick no password at all. Don\'t. Use at least '
              'eight characters, and longer is better.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-20.svg',
          width: 616,
          height: 270,
          caption:
              '**Figure 20. Turn it off when you\'re done.** A device '
              'that joined before may join again by itself and use '
              'your data. Turning the hotspot off stops that.',
        ),
      ],
    ),
    // ── 12. Hotspot or travel router? ──────────────────────────────────────
    LessonStep(
      number: '12',
      title: 'Hotspot or travel router?',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-21.svg',
          width: 616,
          height: 346,
          caption:
              '**Figure 21. Different jobs.** A hotspot is for places '
              'with no Wi-Fi. A travel router shares Wi-Fi that is '
              'already there, like the hotel\'s. __Travel Routers, '
              'Explained__ covers it.',
        ),
        LessonToolLink('travel-routers-explained'),
      ],
    ),
    // ── 13. Four good habits ───────────────────────────────────────────────
    LessonStep(
      number: '13',
      title: 'Four good habits',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/mobile-hotspots/fig-22.svg',
          width: 616,
          height: 210,
          caption:
              '**Figure 22. Four habits that help.** Each one makes a '
              'hotspot work better, and each has its own page earlier '
              'in this guide.',
        ),
      ],
    ),
    // ── 14. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '14',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'Full Wi-Fi bars on my laptop mean fast internet.',
          fact:
              'Those bars show only the short link to the hotspot. The '
              'speed comes from the cell signal.',
        ),
        LessonMyth(
          myth: 'Unlimited data means unlimited hotspot data.',
          fact:
              'Many plans treat hotspot data on its own. Some limit it '
              'or charge extra. Check your plan.',
        ),
        LessonMyth(
          myth: 'A hotspot and a travel router are the same thing.',
          fact:
              'A hotspot brings its own internet, by cell. A travel '
              'router shares internet that is already there.',
        ),
        LessonMyth(
          myth: 'It\'s fine to leave it on all day.',
          fact:
              'It drains the battery, and your devices may join it again '
              'and use data. Turn it off when you\'re done.',
        ),
      ],
    ),
    // ── 15. Tips ───────────────────────────────────────────────────────────
    LessonStep(
      number: '15',
      title: 'Tips',
      blocks: <LessonBlock>[
        LessonSteps(<String>[
          '**Put it near a window,** out in the open. Not in a bag or a '
              'hot car.',
          '**Watch the cell bars** on the hotspot, not the Wi-Fi bars on '
              'your laptop.',
          '**Plug it in** if you\'ll use it for a long time.',
          '**Use a strong password.** Never pick no password.',
          '**Turn on data saver** on the laptop or tablet that joins it.',
          '**Check your plan** before a big download, like a movie or a '
              'system update.',
          '**Turn it off when you\'re done.**',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked on 28 September 2026. Company pages are cited as '
          'sources only, not as recommendations.',
        ),
        LessonSourceList(<String>[
          'Apple Support 111785, "Connect to the Personal Hotspot of an '
              'iPhone or iPad": carrier support and fees; Wi-Fi, USB and '
              'Bluetooth; password of eight or more characters; the network '
              'uses the device\'s name; turn it off when not needed',
          'Google, Android Help 9059108, "Share a mobile connection by '
              'hotspot or tethering on Android": hotspot, USB and Bluetooth '
              'tethering; a "None" security choice; changing the name; no '
              'USB tethering to a Mac; carriers may limit or charge extra; '
              'auto-off',
          'Apple Support 118431, "If your iPhone or iPad gets too hot or '
              'too cold": charging slows or stops; "Cellular signal might '
              'weaken"',
          'Apple Support 102433, "Use Low Data Mode on your iPhone and '
              'iPad"; Microsoft Support, "Metered connections in Windows"',
          'Verizon, "Network Management Information": on certain plans, '
              'data may be put behind other traffic when busy',
          'IETF RFC 9913 (April 2026), 5G system description: radio '
              'network, core network, then the internet',
          'NETGEAR KB 000070348: a hotspot takes a SIM card or an eSIM',
          'Ofcom, Building Materials and Propagation (2014), §4.3, as '
              'cited in __Weak Cell Signal at Home, Explained__: '
              'metal-coated windows block signal too',
          'US FCC, "Wireless Connections and Bluetooth Security Tips," '
              'reviewed 26 November 2025 (Internet Archive copy, 28 '
              'September 2026): longer, stronger passwords',
          'US FTC, "Are Public Wi-Fi Networks Safe? What You Need To '
              'Know," February 2023',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to get '
              'online from a phone or a small hotspot. It is '
              'independent, and isn\'t affiliated with or endorsed by '
              'any phone, carrier or hotspot maker. It names no brand to '
              'buy.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
