// Satellite Texting, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   satellite-texting-explained--SOURCE.html
//   myPKA commit f36a095e 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kSatelliteTextingLesson = GuidedLesson(
  toolId: 'satellite-texting-explained',
  route: '/tools/satellite-texting-explained',
  title: 'Satellite Texting, Explained',
  guideTitle: 'Satellite Texting, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How your phone can send a text with no cell signal, and why it\'s a '
      'backup, not a promise.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/satellite-texting/cover.svg',
    width: 640,
    height: 366,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Many newer phones can send a text through a satellite. It works '
          'when there\'s no cell signal and no Wi-Fi. It works outdoors, '
          'it\'s slow, and it\'s for short messages.',
        ),
        LessonText(
          'This guide answers three questions. What is satellite texting? '
          'Why does it matter to you? And what should you do before you '
          'head somewhere with no signal?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'Your **carrier** is your phone company. **SOS** means a '
              'call for help. In this guide, **911** means the emergency '
              'number where you are.',
        ),
      ],
    ),
    // ── 2. How a text reaches a satellite ──────────────────────────────────
    LessonStep(
      number: '2',
      title: 'How a text reaches a satellite',
      blocks: <LessonBlock>[
        LessonLede(
          'A normal text goes to a cell tower close by. A satellite text '
          'goes up to a satellite first. Then it comes back down to Earth.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-01.svg',
          width: 640,
          height: 534,
          caption:
              '**Figure 1. One text, up and back down.** The green '
              'legs are the trip through the air: the slow, fragile '
              'part. Not to scale.',
        ),
        LessonText(
          'The satellite is far away, and your phone\'s antenna is tiny. '
          'So the signal that gets there is faint, like a whisper across a '
          'stadium.',
        ),
        LessonText(
          'To get through, the phone sends a few words at a time. That\'s '
          'why a text can take a while.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-02.svg',
          width: 640,
          height: 534,
          caption:
              '**Figure 2. A long way for a faint signal.** The '
              'message goes up in small pieces, one after another. '
              'Not to scale.',
        ),
      ],
    ),
    // ── 3. It needs to see the sky ─────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'It needs to see the sky',
      blocks: <LessonBlock>[
        LessonLede(
          'Satellite texting works outdoors, with a clear view of the sky. '
          'Anything overhead gets in the way.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-03.svg',
          width: 640,
          height: 518,
          caption:
              '**Figure 3. What\'s between you and the sky.** Open '
              'sky is best. Trees slow it down. Buildings and canyons '
              'can stop it.',
        ),
        LessonText(
          '**Trees slow it down.** Under leaves, a text can take over a '
          'minute.',
        ),
        LessonText('**Buildings block it.** Step outside before you try.'),
        LessonText(
          '**The horizon matters too.** The satellite may be low in the '
          'sky. A hill or a wall of trees on one side can hide it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-04.svg',
          width: 640,
          height: 604,
          caption:
              '**Figure 4. The sky from where you stand.** Many '
              'satellites move across the sky. When one drops behind '
              'a hill, your phone waits for the next one. Not to '
              'scale.',
        ),
        LessonText(
          '**Far north, it may not work at all.** Parts of Alaska aren\'t '
          'covered.',
        ),
      ],
    ),
    // ── 4. Holding the phone, and waiting ──────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Holding the phone, and waiting',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone tells you what to do. Follow the arrows on the '
          'screen.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-05.svg',
          width: 640,
          height: 548,
          caption:
              '**Figure 5. Hold it out in the open.** Left: what to '
              'do. Right: what loses the satellite.',
        ),
        LessonText(
          'Some phones ask you to turn until you face the satellite. '
          'Others find it on their own. Either way, keep the phone in your '
          'hand, not in a pocket or a pack.',
        ),
        LessonText(
          'Once you\'re connected, stay where you are. Walking under trees '
          'or indoors can lose the satellite.',
        ),
        LessonHeading('What you can send'),
        LessonText(
          'Short texts get through best. Photos, video and calls mostly '
          'wait until you\'re back in coverage. Some phones can also share '
          'your location.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-06.svg',
          width: 640,
          height: 338,
          caption:
              '**Figure 6. Text first.** Left: what can go by '
              'satellite. Right: what waits.',
        ),
      ],
    ),
    // ── 5. A backup, not a promise ─────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'A backup, not a promise',
      blocks: <LessonBlock>[
        LessonLede(
          'Satellite texting can reach help from places no cell tower '
          'covers. It can\'t reach help from everywhere, every time.',
        ),
        LessonCallout.stop(
          title: 'Don\'t make satellite texting your only way to get help',
          body:
              'It needs open sky, a phone that supports it, a charged '
              'battery and time. Under trees, indoors or in a canyon, it '
              'may not connect. Leave your route and your return time '
              'with someone at home.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-07.svg',
          width: 640,
          height: 460,
          caption:
              '**Figure 7. A backup, not a promise.** All four have '
              'to line up at once. Your plan with someone at home is '
              'the part that doesn\'t depend on the sky.',
        ),
        LessonText(
          '**It can be slow, or not work.** Carriers say satellite texts, '
          'even to 911, may be delayed or may not go through.',
        ),
        LessonText(
          '**Emergency alerts may not reach you.** Some satellite services '
          'don\'t pass along weather or safety alerts.',
        ),
        LessonText(
          '**Not every phone has it.** It depends on your phone, your '
          'carrier and the country you\'re in. Check with your carrier and '
          'your phone maker. This changes often.',
        ),
      ],
    ),
    // ── 6. Set it up before you go ─────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Set it up before you go',
      blocks: <LessonBlock>[
        LessonLede(
          'Almost everything has to be done while you still have a signal.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/satellite-texting/fig-08.svg',
          width: 640,
          height: 308,
          caption:
              '**Figure 8. Do it all before you lose signal.** The '
              'numbers match the steps below.',
        ),
        LessonSteps(<String>[
          '**Ask your carrier** whether your phone and plan support '
              'satellite texting where you\'re going.',
          '**Update your phone\'s software.**',
          '**Set up your emergency contacts and medical details.** On an '
              'iPhone, they\'re in the Health app.',
          '**Try the demo, outdoors.** The steps are below.',
          '**Charge the phone,** and bring a battery pack on longer '
              'trips.',
          '**Tell someone** where you\'re going and when you\'ll be back.',
        ]),
        LessonHeading('Try the demo on an iPhone'),
        LessonSteps(<String>[
          'Go outside, somewhere with open sky.',
          'Swipe down from the top right corner to open Control Center.',
          'Tap **Cellular**, then **Satellite**, then **Try Demo**. The '
              'demo doesn\'t call anyone.',
        ]),
        LessonHeading('Try the demo on a Pixel'),
        LessonSteps(<String>[
          'Open **Settings** > **Safety & emergency** > **Satellite '
              'SOS**.',
          'Follow the demo steps on the screen.',
        ]),
      ],
    ),
    // ── 7. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'Satellite texting is like having a cell signal.',
          fact:
              'It\'s slow, and it\'s mostly text. Under open sky, a '
              'message can take half a minute.',
        ),
        LessonMyth(
          myth: 'It works indoors or under trees.',
          fact:
              'It needs the sky. Trees slow it down. Buildings and '
              'canyons can block it.',
        ),
        LessonMyth(
          myth: 'Every phone has it.',
          fact:
              'It depends on your phone, your carrier and where you are. '
              'Ask before you go.',
        ),
        LessonMyth(
          myth: 'It\'s only for emergencies.',
          fact:
              'Emergency texts came first. Now some phones and carriers '
              'let you text family and friends too.',
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked 28 September 2026. Phones, countries and plans change '
          'every few months. Check your carrier and your phone maker '
          'before a trip.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Apple support article 101573, "Use Emergency SOS via '
              'satellite on your iPhone" (published 22 July 2026): phones, '
              'the 20 countries and regions, two free years, calling first, '
              'relay center, accidental sessions, where iPhones bought in '
              'some countries can\'t use it',
          'Apple support article 120930, "About Messages via satellite '
              'on your iPhone" (published 15 May 2026): US, Canada, Mexico '
              'and Japan; iOS 18; 30 seconds and over a minute; what you '
              'can\'t send; not for emergencies; carrier fees',
          'Apple support article 105097, "Connect to a satellite with '
              'your iPhone" (published 15 September 2025): satellites that '
              'move, "hundreds of miles away"; holding the phone; trees, '
              'hills, canyons; 62° latitude; the demo',
          'Google, Pixel Phone Help, "Get emergency help through '
              'satellite with your Pixel phone": Pixel 9 and later except '
              'the 9a, the country list, satellites "in fixed positions", '
              'facing and tilting the phone, the demo',
          'Verizon, "Satellite SOS and messaging FAQs": Skylo, the '
              'listed phones, where it works, basic text only, no extra fee, '
              'no Wireless Emergency Alerts',
          'T-Mobile, "T-Satellite support" and "T-Satellite with '
              'Starlink": coverage, partners abroad, "cell towers in space", '
              'no pointing, what it carries, \$10 a month or included, text '
              'to 911 and its limits',
        ]),
        LessonCallout.note(
          title: 'Other guides in this series',
          body:
              '__How GPS Works, Explained__ covers the satellites your '
              'phone listens to for maps. __Starlink, Explained__ covers '
              'satellite internet at home, which is a different thing. '
              '__Weak Cell Signal at Home, Explained__ covers what helps '
              'when the signal is poor but not gone.',
        ),
        LessonToolLink('how-gps-works-explained'),
        LessonToolLink('starlink-explained'),
        LessonToolLink('weak-cell-signal-explained'),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical. Company names '
              'appear only where their own documents are the source. The '
              'guide is independent and isn\'t affiliated with any phone '
              'maker, carrier or satellite company.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
