// Scales and Ratios, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   scales-and-ratios-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kScalesAndRatiosLesson = GuidedLesson(
  toolId: 'scales-and-ratios-explained',
  route: '/tools/scales-and-ratios-explained',
  title: 'Scales and Ratios, Explained',
  guideTitle: 'Scales and Ratios, Explained',
  tagline: 'A plain-English guide',
  promise:
      'The tiny and huge numbers behind Wi-Fi, turned into things you can '
      'hold, see and picture.',
  byline: <String>['Keith Parsons · CWNE #3', 'October 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/scales-and-ratios/cover.svg',
    width: 536,
    height: 212,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi runs on numbers that are too small or too big to picture. '
          'This guide turns a few of them into things you already know: a '
          'foot of wire, a stack of money, a ruler.',
        ),
        LessonText(
          'You don\'t need to do any math. Each page gives you one picture '
          'to keep.',
        ),
        LessonCallout.note(
          title: 'A few words',
          body:
              'A **nanosecond** is a billionth of a second. A '
              '**millisecond** is a thousandth of a second. A **watt** '
              'measures power, like on a light bulb. Wi-Fi uses a tiny '
              'slice of one.',
        ),
      ],
    ),
    // ── 2. A nanosecond you can hold ───────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'A nanosecond you can hold',
      blocks: <LessonBlock>[
        LessonLede(
          'Grace Hopper was a computer pioneer and a US Navy admiral. She '
          'used to hand out pieces of wire about 30 cm (1 foot) long.',
        ),
        LessonText(
          'Each piece showed how far light, or a radio wave, travels in '
          'one nanosecond. That\'s one billionth of a second. Fast, but '
          'not instant.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-01.svg',
          width: 784,
          height: 306,
          caption:
              '**Figure 1. A nanosecond, as a length.** Light travels '
              'about a foot in a billionth of a second. The drawing '
              'is not actual size.',
        ),
        LessonCallout.quote(
          speaker: 'Grace Hopper',
          body:
              '"I had to point out that between here and the satellite '
              'were a very large number of nanoseconds."',
          attribution: 'Lecture at MIT Lincoln Laboratory, 1985.',
        ),
        LessonText(
          'An admiral had asked her why satellite messages took so long. '
          'Her answer was distance. A satellite is a long way up, and '
          'every foot of the trip takes time.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-02.svg',
          width: 784,
          height: 538,
          caption:
              '**Figure 2. A long trip is a lot of nanoseconds.** Lay '
              'Hopper\'s wires end to end up to a satellite, and each '
              'one adds a nanosecond. Not to scale.',
        ),
      ],
    ),
    // ── 3. Wi-Fi keeps time in tiny steps ──────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Wi-Fi keeps time in tiny steps',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi devices take turns to talk. Each turn is timed in '
          'millionths of a second.',
        ),
        LessonText(
          'Your access point also sends out a short "here I am" message, '
          'called a beacon. It sends about ten of them every second.',
        ),
        LessonText(
          'That gap between beacons feels like nothing to you. For light, '
          'it\'s a long trip.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-03.svg',
          width: 784,
          height: 412,
          caption:
              '**Figure 3. In the time between two beacons, light '
              'could travel past a GPS satellite.** The lime gap on '
              'top and the lime bar below are the same moment. Drawn '
              'to a normal, ruler-style scale.',
        ),
      ],
    ),
    // ── 4. Near and far ────────────────────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Near and far',
      blocks: <LessonBlock>[
        LessonLede(
          'Your Wi-Fi signal crosses a room. A GPS signal falls from high '
          'in space. Both travel at the speed of light.',
        ),
        LessonText(
          'The access point on your ceiling is a few meters away. A '
          'Starlink satellite is about 480 km (300 miles) up. A GPS '
          'satellite is much farther again.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-04.svg',
          width: 760,
          height: 320,
          caption:
              '**Figure 4. Three distances, three zoom levels.** No '
              'single drawing can show all three to one scale. Each '
              'panel has its own scale bar.',
        ),
        LessonText(
          'That\'s why GPS signals arrive so weak. They have come a long '
          'way.',
        ),
      ],
    ),
    // ── 5. Power: the rule of 3s and 10s ───────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Power: the rule of 3s and 10s',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi engineers measure signal strength in decibels, or dB. You '
          'only need two facts.',
        ),
        LessonText(
          'Add 3 dB and the power about doubles. Add 10 dB and it\'s ten '
          'times bigger. Going down works the same way. Think of it as '
          'money:',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-05.svg',
          width: 784,
          height: 446,
          caption:
              '**Figure 5. Decibels as money, starting from \$100.** '
              'Add 3 dB and your money about doubles. Add 10 dB and '
              'it grows ten times.',
        ),
        LessonHeading('A billion to one'),
        LessonText(
          'Your phone sends its Wi-Fi signal with up to about a tenth of a '
          'watt. By the time it reaches the access point across the house, '
          'it can be a billion times weaker.',
        ),
        LessonText(
          'That sounds broken, but it\'s normal. A billion to one is like '
          'one second out of about 32 years. Wi-Fi radios are built to '
          'hear signals that faint.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-06.svg',
          width: 784,
          height: 370,
          caption:
              '**Figure 6. Weak on arrival is normal.** The signal '
              'thins out with every wall and every foot. The bar '
              'below shows how big a billion to one is.',
        ),
      ],
    ),
    // ── 6. Why distance costs so much ──────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Why distance costs so much',
      blocks: <LessonBlock>[
        LessonLede(
          'A signal spreads out as it travels, like paint from a spray '
          'can. The farther it goes, the thinner it gets.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-07.svg',
          width: 784,
          height: 306,
          caption:
              '**Figure 7. The same power, spread over more area.** '
              'Double the distance and the signal covers four times '
              'the area. Each spot gets a quarter as much.',
        ),
      ],
    ),
    // ── 7. How big is a radio wave? ────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'How big is a radio wave?',
      blocks: <LessonBlock>[
        LessonText(
          'Wi-Fi waves are small enough to hold. A 2.4 GHz wave is about '
          '12 cm (5 inches) long; the figure shows it at actual size. A 5 '
          'or 6 GHz wave is about 5 to 6 cm (2 inches) long.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-08.svg',
          width: 160,
          height: 102.2,
          caption:
              '**Figure 8. One wave from each Wi-Fi band.** The bands '
              'with smaller waves have more room for data, but they '
              'fade faster through walls. (actual size on the printed '
              'guide)',
        ),
      ],
    ),
    // ── 8. Bits and bytes ──────────────────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Bits and bytes',
      blocks: <LessonBlock>[
        LessonLede(
          'Internet speed is sold in megabits. File sizes are counted in '
          'megabytes. They are not the same thing.',
        ),
        LessonText(
          'A byte is eight bits. So to turn a speed in Mbps into megabytes '
          'each second, divide by 8.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-09.svg',
          width: 784,
          height: 334,
          caption:
              '**Figure 9. Eight bits fill one byte.** Pour a second '
              'of a 100 Mbps plan into byte jars and you fill about '
              '12 of them.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-10.svg',
          width: 760,
          height: 246,
          caption:
              '**Figure 10. Why a download takes longer than you '
              'think.** A 100 Mbps plan moves a movie in minutes, not '
              'seconds. Drawn to a normal, ruler-style scale.',
        ),
        LessonText(
          'Real downloads are slower still. Other devices share the '
          'connection, and every message carries a little extra.',
        ),
      ],
    ),
    // ── 9. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonLede('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'A nanosecond is too short to matter.',
          fact:
              'Light only goes about a foot in one. Wi-Fi times its '
              'turns in millionths of a second, so nanoseconds add up '
              'fast.',
        ),
        LessonMyth(
          myth: 'Adding 3 dB doubles the power exactly.',
          fact:
              'It\'s close to double. That\'s close enough for any Wi-Fi '
              'math you\'ll ever do.',
        ),
        LessonMyth(
          myth: 'A 100 Mbps plan downloads 100 megabytes a second.',
          fact:
              'Mbps means megabits. Divide by 8. At best, that\'s about '
              '12 megabytes a second.',
        ),
        LessonMyth(
          myth: 'A weak signal means something is broken.',
          fact:
              'A signal can arrive a billion times weaker than it left '
              'and still work. Wi-Fi is built for that.',
        ),
        LessonHeading('Pictures to keep'),
        LessonFigure(
          asset: 'assets/lesson-figures/scales-and-ratios/fig-11.svg',
          width: 784,
          height: 298,
          caption:
              '**Figure 11. Four pictures to keep.** The four ideas '
              'from this guide worth remembering.',
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText('Gathered 28 September 2026.'),
        LessonSourceList(<String>[
          'NIST SP 330, The International System of Units (SI): the '
              'speed of light and the metric prefixes',
          'Grace Hopper, lecture at MIT Lincoln Laboratory, 25 April '
              '1985, transcript published by Speakola',
          'Smithsonian National Museum of American History, object '
              'record for Hopper\'s nanosecond wires',
          'CWNP, "802.11 Beacon Intervals", quoting IEEE 802.11 (the '
              'beacon interval)',
          'GPS.gov, Space Segment (GPS satellite height); Starlink Space '
              'Safety, "Constellation altitudes" (about 480 km)',
          'HyperPhysics, Georgia State University, Inverse square law',
          'IEC, Prefixes for binary multiples; FCC, Broadband Speed Guide',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for anyone who wants Wi-Fi\'s numbers to mean '
              'something. Companion guides: __How GPS Works, '
              'Explained__; __Analog vs Digital, Explained__; '
              '__Starlink, Explained__. Keith Parsons, CWNE #3, Wireless '
              'LAN Professionals.',
        ),
        LessonToolLink('how-gps-works-explained'),
        LessonToolLink('analog-vs-digital-explained'),
        LessonToolLink('starlink-explained'),
      ],
    ),
  ],
);
