// Smart Home Radios, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   smart-home-radios-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kSmartHomeRadiosLesson = GuidedLesson(
  toolId: 'smart-home-radios-explained',
  route: '/tools/smart-home-radios-explained',
  title: 'Smart Home Radios, Explained',
  guideTitle: 'Smart Home Radios, Explained',
  tagline: 'A plain-English guide',
  promise:
      'Wi-Fi, Thread, Zigbee and Matter. Why your smart plug won\'t join, '
      'and what the Matter logo on the box means.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/smart-home-radios/cover.svg',
    width: 700,
    height: 200,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Smart home boxes use four names: Wi-Fi, Thread, Zigbee and '
          'Matter. Three of them are radios. Matter is not a radio. It\'s '
          'a shared language that devices speak over the radios.',
        ),
        LessonText(
          'Most setup trouble comes from one thing. Many smart plugs and '
          'bulbs can only use the older 2.4 GHz part of your Wi-Fi. Your '
          'phone would rather use the faster 5 GHz part.',
        ),
        LessonCallout.note(
          title: 'The one idea that explains this guide',
          body:
              'Matter is the language. Wi-Fi, Thread and a network cable '
              'are the ways a Matter device connects. Zigbee is an older '
              'system that reaches Matter through a bridge.',
        ),
      ],
    ),
    // ── 2. Three radios and a language ─────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Three radios and a language',
      blocks: <LessonBlock>[
        LessonLede(
          'Think of Matter as the words, and the radios as the phone lines '
          'that carry them.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-01.svg',
          width: 720,
          height: 250,
          caption:
              '**Figure 1. Three radios and a language.** Matter '
              'devices connect by Wi-Fi, Thread or a cable. Your '
              'phone usually uses Bluetooth once, to set them up. '
              'Zigbee speaks its own language and needs a bridge.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-02.svg',
          width: 760,
          height: 330,
          caption:
              '**Figure 2. The four radios in a smart home.** Wi-Fi '
              'and Thread carry Matter directly (the green row). '
              'Zigbee needs a bridge, and Bluetooth only helps at '
              'setup.',
        ),
      ],
    ),
    // ── 3. One band, shared ────────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'One band, shared',
      blocks: <LessonBlock>[
        LessonLede(
          'All four radios use the same slice of airwaves, the 2.4 GHz '
          'band. They share it by taking turns.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-03.svg',
          width: 700,
          height: 258,
          caption:
              '**Figure 3. One road, many lanes.** Wi-Fi uses a few '
              'wide lanes. Thread and Zigbee use many narrow ones. '
              'Each radio listens first, then talks when the lane is '
              'clear.',
        ),
        LessonText(
          'Most homes run all of these without anyone noticing. Trouble '
          'comes when one Wi-Fi lane is busy all evening, like during a '
          'long movie. Then the small radios underneath have to wait.',
        ),
        LessonHeading('Moving up helps everyone'),
        LessonText(
          'Thread and Zigbee can\'t leave 2.4 GHz. Your phone, laptop and '
          'TV can move up to 5 or 6 GHz. Every device that moves up leaves '
          'more room for the small ones.',
        ),
      ],
    ),
    // ── 4. Why your smart plug won't join ──────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Why your smart plug won\'t join',
      blocks: <LessonBlock>[
        LessonLede(
          'You plug it in, open the app, and your phone passes the plug '
          'your Wi-Fi name and password. Then the plug tries to join on '
          'its own. That\'s where it fails.',
        ),
        LessonText(
          'Many smart plugs, bulbs and cameras have only a 2.4 GHz radio. '
          'If your Wi-Fi only offers 5 GHz, the plug can\'t even see it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-04.svg',
          width: 720,
          height: 140,
          caption:
              '**Figure 4. Two bands, one name.** The plug needs 2.4 '
              'GHz to join. With one name on both bands, 2.4 GHz is '
              'there. Some setup apps also want your phone on 2.4 GHz '
              'for a minute.',
        ),
        LessonText(
          'Some newer plugs have a 5 GHz radio too. If the box says "2.4 '
          'GHz only," it doesn\'t.',
        ),
      ],
    ),
    // ── 5. Getting it to join ──────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Getting it to join',
      blocks: <LessonBlock>[
        LessonLede('Work down this list, gentlest first. Stop when it joins.'),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-05.svg',
          width: 760,
          height: 666,
          caption:
              '**Figure 5. Getting it to join, gentlest fix first.** '
              'Try each step in order, and stop as soon as it joins. '
              'Step 6 is in the next step.',
        ),
      ],
    ),
    // ── 6. Give your gadgets their own network ─────────────────────────────
    LessonStep(
      number: '6',
      title: 'Give your gadgets their own network',
      blocks: <LessonBlock>[
        LessonLede(
          'Many routers let you add a second network name that uses 2.4 '
          'GHz only. Put your plugs, bulbs, thermostats and doorbells on '
          'it. A smart plug will join any network that offers 2.4 GHz.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-06.svg',
          width: 760,
          height: 434,
          caption:
              '**Figure 6. One router, two network names.** Your '
              'gadgets get a simple 2.4 GHz network to live on. Make '
              'it a regular network, so your phone can still reach '
              'them.',
        ),
        LessonCallout.note(
          title: 'Not the guest network',
          body:
              'Make the gadget network a regular network, not a guest '
              'network. A guest network keeps gadgets apart from your '
              'phone, and setup fails.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '"Giving 2.4 GHz its own name gives those devices '
              'somewhere simple to live, and it is a real fix for a real '
              'problem."',
          attribution: 'Keith Parsons, __Fix Your Own Wi-Fi__, chapter 5',
        ),
      ],
    ),
    // ── 7. Thread: a mesh with a doorway ───────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Thread: a mesh with a doorway',
      blocks: <LessonBlock>[
        LessonLede(
          'Thread devices don\'t join your Wi-Fi. They build their own '
          'small web, where plugged-in devices pass messages along for '
          'each other.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-07.svg',
          width: 720,
          height: 280,
          caption:
              '**Figure 7. A Thread mesh.** Plugged-in devices relay '
              'for each other. If one goes offline, a message takes '
              'another path. The border router is the doorway to the '
              'rest of your home.',
        ),
        LessonText(
          'Battery sensors sleep most of the time. They wake up and talk '
          'through one plugged-in neighbor. That\'s how a door sensor can '
          'run for years on a small battery.',
        ),
        LessonHeading('The doorway is called a border router'),
        LessonText(
          'It joins the Thread web to your home network. You usually '
          'already own one, built into a smart speaker, a streaming box or '
          'a newer Wi-Fi router.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-08.svg',
          width: 760,
          height: 382,
          caption:
              '**Figure 8. Where the border router lives.** Here '
              'it\'s inside a smart speaker. Thread gadgets pass '
              'their messages to it, and it hands them to your Wi-Fi '
              'router.',
        ),
      ],
    ),
    // ── 8. One network, several doorways ───────────────────────────────────
    LessonStep(
      number: '8',
      title: 'One network, several doorways',
      blocks: <LessonBlock>[
        LessonLede(
          'Two border routers are better than one. If one loses power, the '
          'other keeps the doorway open.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-09.svg',
          width: 720,
          height: 230,
          caption:
              '**Figure 9. Before and after the update.** Left: older '
              'border routers each built their own network. Right: '
              'updated ones share one network, so either can be the '
              'doorway.',
        ),
        LessonText(
          'Older border routers from different brands didn\'t always '
          'share. A recent Thread update fixed that. Many border routers '
          'get it through normal software updates.',
        ),
        LessonText(
          'You don\'t need a border router from the same brand as your '
          'devices. They pass messages along without translating them.',
        ),
      ],
    ),
    // ── 9. Zigbee, and what Matter changes ─────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Zigbee, and what Matter changes',
      blocks: <LessonBlock>[
        LessonLede(
          'Zigbee came first. It\'s also a low-power web on 2.4 GHz, but '
          'it speaks its own language, through its own hub.',
        ),
        LessonText(
          'A Zigbee device can\'t talk to Matter directly. A bridge can '
          'translate. If your Zigbee hub is also a Matter bridge, your '
          'Zigbee gadgets can stay.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-10.svg',
          width: 760,
          height: 268,
          caption:
              '**Figure 10. A bridge lets Zigbee gadgets stay.** On '
              'its own, a Zigbee gadget can\'t reach a Matter app. A '
              'hub that is also a Matter bridge translates for it.',
        ),
        LessonHeading('What Matter changes'),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'Setup looks the same',
            body:
                'Scan the code on the box, keep your phone close, and '
                'the app does the rest.',
          ),
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-11.svg',
          width: 760,
          height: 186,
          caption:
              '**Figure 11. More than one app.** One person can use '
              'one company\'s app, and another person a different '
              'one. The same bulb answers both.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-12.svg',
          width: 720,
          height: 170,
          caption:
              '**Figure 12. Matter keeps growing.** New versions add '
              'new kinds of devices, like cameras. Your app adds them '
              'on its own schedule.',
        ),
        LessonCallout.note(
          title: 'The logo isn\'t a promise',
          body:
              'A Matter logo doesn\'t mean your app supports that kind '
              'of device yet. Check the app\'s list before you buy.',
        ),
      ],
    ),
    // ── 10. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'Matter is a new kind of wireless.',
          fact:
              'Matter is a language. It runs over Wi-Fi, Thread or a '
              'network cable.',
        ),
        LessonMyth(
          myth: 'Any smart plug joins any Wi-Fi.',
          fact:
              'Many only have a 2.4 GHz radio. They can\'t join a '
              'network that only offers 5 GHz.',
        ),
        LessonMyth(
          myth: 'Thread devices need their own internet.',
          fact:
              'They use the home network you already have, through a '
              'border router.',
        ),
        LessonMyth(
          myth: 'The Matter logo means it works with my app.',
          fact:
              'Each app adds device types on its own schedule. Check '
              'first.',
        ),
        LessonHeading('Before you buy a smart device'),
        LessonFigure(
          asset: 'assets/lesson-figures/smart-home-radios/fig-13.svg',
          width: 760,
          height: 236,
          caption:
              '**Figure 13. Four checks before you buy.** The box '
              'should answer the first two.',
        ),
      ],
    ),
    // ── →. Where this comes from ───────────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where this comes from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked in September 2026. Standards bodies first, then the '
          'platform makers\' own help pages.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Connectivity Standards Alliance, Matter FAQ, '
              'csa-iot.org/all-solutions/matter/matter-faq (networks, '
              'Bluetooth LE setup, QR codes, multi-admin, bridges, Zigbee, '
              'local control)',
          'CSA, "Matter Arrives", 4 October 2022 (Matter 1.0 over '
              'Ethernet, Wi-Fi and Thread)',
          'CSA, "Matter 1.5 Introduces Cameras, Closures, and Enhanced '
              'Energy Management Capabilities", 20 November 2025',
          'CSA, "Matter 1.5.1: Enhancing Camera Performance and '
              'Expanding Device Flexibility", 31 March 2026',
          'CSA, "Matter 1.6 Enables More Intuitive Setup, '
              'Multi-Ecosystem Experiences, and Context-Driven Control", 17 '
              'June 2026 (NFC setup; no new device categories)',
          'CSA, Zigbee, csa-iot.org/all-solutions/zigbee (mesh; 2.4 GHz '
              'and sub-GHz)',
          'Thread Group, "Thread Network Fundamentals", v3, May 2020 '
              '(802.15.4 at 250 kbps in 2.4 GHz; waiting for a clear '
              'channel; self-healing; roles; border routers)',
          'Thread Group, "What is a Thread Border Router", 2 November '
              '2022',
          'Thread Group, "Thread 1.4 Paves the Path for Smart Devices to '
              'Work Together", 4 September 2024',
          'Google Home Help, "How Nest Wifi, Nest Wifi Pro, and Google '
              'Wifi 2.4, 5 GHz, and 6 GHz bands work" and "Prepare your '
              'smart home for Matter"',
          'Apple Support 102078 (13 January 2026) and 102135 (7 May '
              '2026), on Thread border routers and Matter pairing',
          'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, in '
              'preparation, 2026), chapter 5, "when a separate network for '
              'the small stuff helps"',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want their '
              'smart devices to join the first time. Keith Parsons, CWNE '
              '#3, runs Wireless LAN Professionals. This guide is '
              'independent and recommends no brand of hub.',
        ),
      ],
    ),
  ],
);
