// Tap, Touch and Near, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   tap-touch-near-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kTapTouchNearLesson = GuidedLesson(
  toolId: 'tap-touch-near-explained',
  route: '/tools/tap-touch-near-explained',
  title: 'Tap, Touch and Near, Explained',
  guideTitle: 'Tap, Touch and Near, Explained',
  tagline: 'A plain-English guide',
  promise:
      'What happens when you tap to pay, whether your wallet needs a '
      'shield, and how your phone finds your keys.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/tap-touch-near/cover.svg',
    width: 640,
    height: 346,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone has two radios for things up close. One works when '
          'you tap to pay. The other helps you find your keys.',
        ),
        LessonText(
          'Tapping to pay is safe. Each payment uses a code that works '
          'only once. For your bank cards, you don\'t need a special '
          'wallet.',
        ),
        LessonText(
          'This guide answers three questions. What are these radios? Why '
          'do they matter to you? And what should you watch out for?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**NFC** is the radio for a tap. **Ultra Wideband**, or '
              'UWB, is the radio that measures how far away something '
              'is. The **reader** is the box at the store or gate that '
              'you tap.',
        ),
      ],
    ),
    // ── 2. A tap has to be a tap ───────────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'A tap has to be a tap',
      blocks: <LessonBlock>[
        LessonLede(
          'A tap card has no battery. It borrows a tiny bit of power from '
          'the reader, just long enough to answer.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-01.svg',
          width: 640,
          height: 218,
          caption:
              '**Figure 1. The card runs on the reader\'s power.** '
              'The green arrow is the power going in. Only then can '
              'the chip answer.',
        ),
        LessonText(
          'That power fades fast. Move the card a hand\'s width away and '
          'it can\'t wake up at all. That\'s on purpose. A payment should '
          'happen only when you mean it to.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-02.svg',
          width: 640,
          height: 262,
          caption:
              '**Figure 2. How close is close.** Only a card inside '
              'the green tap zone wakes up. Roughly to scale.',
        ),
        LessonText(
          'You use this every day: paying at a store, getting through a '
          'transit gate, opening a hotel door, or tapping a badge at work.',
        ),
      ],
    ),
    // ── 3. What a tap sends ────────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'What a tap sends',
      blocks: <LessonBlock>[
        LessonLede(
          'When you pay with your phone or watch, the store never gets '
          'your card number. Your phone sends a stand-in number instead.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-03.svg',
          width: 640,
          height: 388,
          caption:
              '**Figure 3. The store gets a stand-in, not your card '
              'number.** Follow the green tags from your phone to '
              'your bank. Simplified.',
        ),
        LessonText(
          'With a phone, a card or a watch, every tap also sends a new '
          'code. The code works for that one purchase only. If someone '
          'copies it, the bank turns it down.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-04.svg',
          width: 640,
          height: 440,
          caption:
              '**Figure 4. A code that works once.** Each real tap '
              'sends a new code. A copy played back later is turned '
              'down, because the bank has already seen that code. '
              'Simplified.',
        ),
        LessonText(
          'The old magnetic stripe is different. It sends the same data '
          'every time you swipe. That\'s the part thieves copy. So tap or '
          'insert your card instead of swiping.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-05.svg',
          width: 640,
          height: 420,
          caption:
              '**Figure 5. Swipe versus tap.** A swipe sends the same '
              'data every time, so a copy works again. A tap or chip '
              'sends a new code.',
        ),
      ],
    ),
    // ── 4. Does your wallet need a shield? ─────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Does your wallet need a shield?',
      blocks: <LessonBlock>[
        LessonLede(
          'For bank cards, no. A thief would have to hold a reader right '
          'against your card. Even then, the code they get works only once.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-06.svg',
          width: 640,
          height: 364,
          caption:
              '**Figure 6. Why a hidden reader gets nothing useful.** '
              'Read left to right: even a thief close enough to read '
              'your card gets a code the bank won\'t take again.',
        ),
        LessonText(
          'If you like your blocking wallet, keep using it. It does no '
          'harm. You just have to take the card out to tap.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-07.svg',
          width: 640,
          height: 330,
          caption:
              '**Figure 7. Three cards, built three ways.** A bank '
              'card is built for a tap. A passport book has shielding '
              'in its cover. A passport card is made to be read from '
              'farther away, so it comes with its own sleeve.',
        ),
        LessonText(
          'The one exception is a US passport card, and a few other border '
          'cards like it. They\'re built to be read at a distance at a '
          'border crossing. Keep yours in the sleeve it came in.',
        ),
      ],
    ),
    // ── 5. Where the real risk is ──────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Where the real risk is',
      blocks: <LessonBlock>[
        LessonLede(
          'The real risks aren\'t about radios at all. They\'re older '
          'tricks.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-08.svg',
          width: 640,
          height: 344,
          caption:
              '**Figure 8. The real risks, and what to do.** None of '
              'them is about the tap radio.',
        ),
        LessonText(
          '**A card skimmer.** Thieves hide a fake reader in the card slot '
          'at a gas pump or a cash machine. It copies the magnetic stripe. '
          'Tap or insert your chip instead of swiping.',
        ),
        LessonText(
          '**A lost phone or wallet.** If your phone goes missing, mark it '
          'lost right away. On iPhone, use Find My. On Android, use Find '
          'Hub. That turns off the cards and keys stored in it. If a card '
          'goes missing, call your bank.',
        ),
        LessonCallout.stop(
          title: 'Never share a code your bank texts you',
          body:
              'Scammers call pretending to be your bank. They ask for '
              'the code that just arrived on your phone. Your bank will '
              'never ask for it. Hang up and call your bank on a number '
              'you already know.',
        ),
        LessonText(
          'One more free habit: turn on purchase alerts in your bank\'s '
          'app. Then a charge you didn\'t make shows up on your phone the '
          'same day.',
        ),
      ],
    ),
    // ── 6. Finding your keys ───────────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Finding your keys',
      blocks: <LessonBlock>[
        LessonLede(
          'Ultra Wideband measures distance by timing. One device sends a '
          'quick ping, the other answers, and the phone times the trip.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-09.svg',
          width: 640,
          height: 440,
          caption:
              '**Figure 9. Your phone points the way.** It times a '
              'quick ping and reply with the tracker, then shows an '
              'arrow. Not to scale.',
        ),
        LessonText(
          'That timing is exact. It can tell where something is to within '
          'a few centimeters (about an inch).',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-10.svg',
          width: 640,
          height: 468,
          caption:
              '**Figure 10. Two ways to judge distance.** Most '
              'Bluetooth gear guesses by how loud the signal sounds. '
              'Ultra Wideband times it, which is far more exact. Not '
              'to scale.',
        ),
        LessonText(
          'Some newer cars use it too. Your phone can be the car key. The '
          'car checks that the phone is close before it unlocks. That '
          'stops thieves who try to pass a key\'s signal along from far '
          'away.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/tap-touch-near/fig-11.svg',
          width: 640,
          height: 420,
          caption:
              '**Figure 11. The car checks the timing.** A signal '
              'passed along from far away takes too long, so the car '
              'stays locked. Not to scale.',
        ),
        LessonCallout.note(
          title: 'Looking for your tracker?',
          body:
              '__Find My, Explained__ covers the arrow that leads you to '
              'a lost item. __Bluetooth, Explained__ covers earbuds, '
              'speakers and your car stereo.',
        ),
        LessonToolLink('find-my-explained'),
        LessonToolLink('bluetooth-explained'),
      ],
    ),
    // ── 7. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'Someone can read my card from across the room.',
          fact:
              'A bank card only answers a reader held right up to it. '
              'And the store has to start the payment.',
        ),
        LessonMyth(
          myth: 'My bank cards need a blocking wallet.',
          fact:
              'They don\'t. Each tap uses a code that works only once. A '
              'sleeve does matter for a US passport card.',
        ),
        LessonMyth(
          myth: 'Tapping a card is less safe than swiping it.',
          fact:
              'A phone or watch sends a stand-in number. A card does '
              'send its number, but with a one-time code, so a copied '
              'tap can\'t be used again.',
        ),
        LessonMyth(
          myth: 'Ultra Wideband is just Bluetooth.',
          fact:
              'They\'re different radios. Ultra Wideband times its '
              'signal to find exactly where something is.',
        ),
        LessonHeading('Habits worth keeping'),
        LessonSteps(<String>[
          '**Tap or insert, don\'t swipe.** Especially at a gas pump.',
          '**Pay with your phone or watch when you can.** The store '
              'never gets your card number.',
          '**On transit, tap in and out with the same card or phone.** '
              'Keep your other tap cards away from the gate.',
          '**Never give anyone a code your bank texts you.** Hang up and '
              'call your bank yourself.',
          '**If your phone goes missing, mark it lost.** That switches '
              'off its cards and keys.',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText('Checked on 28 September 2026.', small: true),
        LessonSourceList(<String>[
          'NFC Forum, nfc-forum.org home page ("just a few centimeters '
              'apart", 13.56 MHz) and NFC Technology page (card, reader and '
              'peer-to-peer roles)',
          'Visa, Contactless Payments FAQ, usa.visa.com (1 to 2 inches, '
              'what a card sends, one-time code, merchant must start the '
              'payment, "very unlikely and limited in scope")',
          'EMVCo, The What, Why and How of EMV Payment Tokenisation (a '
              'token replaces the card number)',
          'Apple 101554, Apple Pay security and privacy (27 April 2026); '
              'Apple 105123, Express Mode (18 November 2025); Apple 118271, '
              'car keys (18 September 2025)',
          'Google Wallet Help 7643925 (virtual card, screen lock) and '
              '12060041 (digital car key); Google Pixel Phone Help 3470787 '
              '(NFC switch)',
          'FTC consumer alerts: "Watch out for card skimming at the gas '
              'pump" (7 August 2018); "What\'s a verification code and why '
              'would someone ask me for it?" (7 March 2024)',
          'Federal Register, 25 October 2005, Electronic Passport final '
              'rule (anti-skimming cover, about ten centimeters); Federal '
              'Register, 31 December 2007, Card Format Passport final rule '
              '(one number only, protective sleeve)',
          'Transport for London, Card clash, tfl.gov.uk',
          'FiRa Consortium: How UWB Works (500 MHz, 2 ns pulses); '
              'Technical FAQ (few centimeters, 30 cm, 100 m, signal '
              'strength); UWB Terminology (25 September 2023); Why '
              'Automakers Are Embracing UWB (4 April 2025)',
          'Car Connectivity Consortium, Cars That Use Digital Keys in '
              '2026 (NFC, Bluetooth and UWB; relay attacks)',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to know '
              'what their phone does when they tap, and whether their '
              'wallet needs a shield. Apple, iPhone, Google, Android, '
              'Visa and Bluetooth are trademarks of their owners. This '
              'guide is independent and isn\'t affiliated with or '
              'endorsed by any of them.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
