// Travel Routers, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   travel-routers-explained--SOURCE.html
//   myPKA commit 3393a775 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kTravelRoutersLesson = GuidedLesson(
  toolId: 'travel-routers-explained',
  route: '/tools/travel-routers-explained',
  title: 'Travel Routers, Explained',
  guideTitle: 'Travel Routers, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How one small box joins the hotel Wi-Fi for you, and gives all your '
      'devices a network they already know.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/travel-routers/cover.svg',
    width: 616,
    height: 360,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'A travel router is a small box you pack in your bag. It joins '
          'the hotel Wi-Fi for you. Then it makes your own Wi-Fi in the '
          'room. Your phone, laptop and tablet join that, just like at '
          'home.',
        ),
        LessonText(
          'This guide answers three questions. What is a travel router? '
          'Why does it help you? And how do you set one up?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'A **router** is the box that shares one internet '
              'connection with many devices. A **travel router** is a '
              'pocket-sized one. A **sign-in page** is the web page a '
              'hotel shows before it lets you online.',
        ),
        LessonCallout.note(
          title: 'What this guide leaves out',
          body:
              'Hotel sign-in pages have their own guide: __Captive '
              'Portals, Explained__. This guide covers only what changes '
              'when a travel router is in the room.',
        ),
        LessonToolLink('captive-portals-explained'),
      ],
    ),
    // ── 2. A small box with two jobs ───────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'A small box with two jobs',
      blocks: <LessonBlock>[
        LessonLede(
          'A travel router talks to the hotel, and it talks to you. It '
          'does both at once.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-01.svg',
          width: 616,
          height: 300,
          caption:
              '**Figure 1. Two jobs, one box.** It joins the hotel '
              'Wi-Fi, just like a phone would. Then it makes a Wi-Fi '
              'network that belongs to you.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-02.svg',
          width: 616,
          height: 306,
          caption:
              '**Figure 2. Your Wi-Fi is a few steps away.** The '
              'hotel\'s Wi-Fi often comes from down the hall. Your '
              'own Wi-Fi comes from the desk, right next to you.',
        ),
      ],
    ),
    // ── 3. Two radios in one box ───────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Two radios in one box',
      blocks: <LessonBlock>[
        LessonLede(
          'A better travel router has two radios, one for each job. One '
          'faces the hotel. The other faces you.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-03.svg',
          width: 616,
          height: 460,
          caption:
              '**Figure 3. One radio for each job.** The top radio '
              'joins the hotel. The bottom radio runs your own Wi-Fi. '
              'In the middle, the box sends everything out as if it '
              'were one device.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body: '“A travel router is two radios wearing one name.”',
          attribution:
              'From Keith\'s LinkedIn post on travel routers, 3 '
              'September 2026.',
        ),
      ],
    ),
    // ── 4. Your devices remember one network ───────────────────────────────
    LessonStep(
      number: '4',
      title: 'Your devices remember one network',
      blocks: <LessonBlock>[
        LessonLede(
          'Your phone joins a network it already knows by itself. With a '
          'travel router, you have one network to know, in every hotel.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-04.svg',
          width: 616,
          height: 352,
          caption:
              '**Figure 4. Sign in once, not on every device.** Only '
              'the travel router meets each new hotel. Your devices '
              'see the same network every trip, so they join on their '
              'own.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-05.svg',
          width: 616,
          height: 240,
          caption:
              '**Figure 5. Help for gadgets with no browser.** A TV '
              'stick or a game console can struggle with a sign-in '
              'page. On your own Wi-Fi, it never sees one.',
        ),
      ],
    ),
    // ── 5. The device limit ────────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'The device limit',
      blocks: <LessonBlock>[
        LessonLede(
          'Some hotels let each guest sign in only a few devices. A family '
          'can hit that limit before the bags are open.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-06.svg',
          width: 616,
          height: 344,
          caption:
              '**Figure 6. The hotel counts one.** Usually, every '
              'device behind the travel router shares that one spot. '
              'The limit shown is an example. If a hotel still blocks '
              'it, ask the front desk.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-07.svg',
          width: 616,
          height: 246,
          caption:
              '**Figure 7. One on the list, many in the room.** The '
              'hotel sees one device. Everything you carry sits '
              'behind it.',
        ),
      ],
    ),
    // ── 6. A network of your own ───────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'A network of your own',
      blocks: <LessonBlock>[
        LessonLede(
          'Hotel Wi-Fi is shared with every guest in the building. A '
          'travel router puts a wall between your devices and that crowd.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-08.svg',
          width: 616,
          height: 344,
          caption:
              '**Figure 8. Your devices stay on your side.** On hotel '
              'Wi-Fi, your devices may share a network with '
              'strangers. Many hotels keep guests apart, but you '
              'can\'t tell which. Behind the travel router, your '
              'devices sit on your own network.',
        ),
        LessonCallout.note(
          title: 'Leave it in router mode',
          body:
              'Some travel routers also offer an access point or bridge '
              'mode. Those modes take the wall down. Router mode keeps '
              'it up.',
        ),
        LessonCallout.note(
          title: 'It is still the hotel\'s internet',
          body:
              'The travel router keeps other guests away from your '
              'devices. It does not hide what you do online from the '
              'hotel. For that, see the VPN note in step 12.',
        ),
      ],
    ),
    // ── 7. Set it up at home ───────────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Set it up at home',
      blocks: <LessonBlock>[
        LessonLede(
          'Do the setup at home, before the trip, where you have time and '
          'good internet.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-09.svg',
          width: 616,
          height: 240,
          caption:
              '**Figure 9. Three steps, done once.** Give your '
              'network a name and a password, then join each device '
              'to it. After that, they join by themselves.',
        ),
        LessonSteps(<String>[
          '**Plug it in and join its Wi-Fi.** The name and password are '
              'on its label.',
          '**Open its settings.** The box or the manual tells you how. '
              'Many use an app.',
          '**Change the name and password to your own.** Set a password '
              'for the settings page too.',
          '**Join every device you travel with.** Phones, laptops, '
              'tablets, the TV stick.',
          '**Update its software** while you have good internet.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-10.svg',
          width: 616,
          height: 180,
          caption:
              '**Figure 10. Three things to pack.** The travel '
              'router, its power cord, and a short network cable in '
              'case the room has a wall jack.',
        ),
      ],
    ),
    // ── 8. At the hotel: join, then sign in ────────────────────────────────
    LessonStep(
      number: '8',
      title: 'At the hotel: join, then sign in',
      blocks: <LessonBlock>[
        LessonLede(
          'In the room, you tell the travel router which hotel network to '
          'join. You do it from your phone.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-11.svg',
          width: 616,
          height: 240,
          caption:
              '**Figure 11. Pick the hotel network.** On your phone, '
              'open the travel router\'s settings. Choose the '
              'hotel\'s network from the list, and the router joins '
              'it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-12.svg',
          width: 616,
          height: 286,
          caption:
              '**Figure 12. One sign-in covers everyone.** Open a web '
              'page on a phone joined to your travel router. The '
              'hotel\'s page shows up. Accept it once, and every '
              'device is online.',
        ),
        LessonText(
          'No page? On the router, turn off any VPN or ad blocker for a '
          'moment. Then open a web page in your browser. __Captive '
          'Portals, Explained__ has more help.',
        ),
        LessonToolLink('captive-portals-explained'),
      ],
    ),
    // ── 9. A wired jack in the room ────────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'A wired jack in the room',
      blocks: <LessonBlock>[
        LessonLede(
          'Some rooms still have a network jack in the wall or on the '
          'desk. If yours does, use it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-13.svg',
          width: 616,
          height: 344,
          caption:
              '**Figure 13. A cable is steadier.** The cable carries '
              'the hotel side. The travel router\'s Wi-Fi then works '
              'only for you and your devices.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-14.svg',
          width: 616,
          height: 230,
          caption:
              '**Figure 14. Use the internet port.** The cable from '
              'the wall goes into the port meant for the internet. '
              'The jack may show the same sign-in page as the Wi-Fi.',
        ),
      ],
    ),
    // ── 10. When it doesn't help ───────────────────────────────────────────
    LessonStep(
      number: '10',
      title: 'When it doesn\'t help',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-15.svg',
          width: 616,
          height: 200,
          caption:
              '**Figure 15. Slow in, slow out.** The travel router '
              'shares what the hotel gives. It can make things '
              'steadier, but not faster.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“A travel router does not make a bad network good. It '
              'changes which device has to cope with the bad network, '
              'and it changes what everything else can see.”',
          attribution:
              'From Keith\'s LinkedIn post on travel routers, 3 '
              'September 2026.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-16.svg',
          width: 616,
          height: 290,
          caption:
              '**Figure 16. Check for two radios.** A one-radio model '
              'takes turns talking to the hotel and to you, so it '
              'runs slower.',
        ),
      ],
    ),
    // ── 11. Two surprises ──────────────────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Two surprises',
      blocks: <LessonBlock>[
        LessonLede(
          'Your devices like your travel router so much that they stick to '
          'it. Most days, that\'s what you want.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-17.svg',
          width: 616,
          height: 318,
          caption:
              '**Figure 17. Known beats nearby.** Your devices '
              'usually pick the network they know. To put one on the '
              'hotel Wi-Fi, turn the travel router off, or tell that '
              'device to forget your network.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-18.svg',
          width: 616,
          height: 250,
          caption:
              '**Figure 18. The wall works both ways.** Other guests '
              'can\'t reach your devices. Your devices also may not '
              'find things on the hotel network, like a room TV you '
              'cast video to, because they are on a different network.',
        ),
      ],
    ),
    // ── 12. A VPN on the router ────────────────────────────────────────────
    LessonStep(
      number: '12',
      title: 'A VPN on the router',
      blocks: <LessonBlock>[
        LessonLede(
          'A VPN (virtual private network) on the travel router scrambles '
          'what your devices send, so the hotel can\'t read it, and you '
          'trust the VPN company instead.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-19.svg',
          width: 616,
          height: 180,
          caption:
              '**Figure 19. One tunnel for every device.** Set up on '
              'the router, the VPN covers everything behind it.',
        ),
      ],
    ),
    // ── 13. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '13',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'A travel router makes hotel Wi-Fi faster.',
          fact:
              'It shares the same hotel internet. It can feel better '
              'because it\'s steady and close to you, but it can\'t add '
              'speed.',
        ),
        LessonMyth(
          myth: 'A travel router brings its own internet.',
          fact:
              'The kind in this guide has none of its own. It shares the '
              'hotel\'s, by Wi-Fi or by cable.',
        ),
        LessonMyth(
          myth: 'Behind a travel router, the hotel can\'t see what I do.',
          fact:
              'It keeps other guests away from your devices. The hotel '
              'still carries your traffic. A VPN is what hides it.',
        ),
        LessonMyth(
          myth: 'You have to be a tech expert.',
          fact:
              'You set it up once, at home. At each hotel, you pick a '
              'network and accept a sign-in page.',
        ),
      ],
    ),
    // ── 14. Tips ───────────────────────────────────────────────────────────
    LessonStep(
      number: '14',
      title: 'Tips',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/travel-routers/fig-20.svg',
          width: 616,
          height: 430,
          caption:
              '**Figure 20. Two easy wins.** Set it up before you '
              'leave, and keep it where your devices can hear it.',
        ),
        LessonSteps(<String>[
          '**Set it up at home.** Do it before the trip, not late at '
              'night in a hotel.',
          '**Pack the cable and the power cord.** A short network cable '
              'is worth the space.',
          '**Put it in the open, near where you sit.** Not in a bag or a '
              'drawer.',
          '**Sign in from a device on your travel router.** Then the '
              'sign-in covers everyone.',
          '**Turn it off when you want a device on another network.**',
          '**Buy a model with two radios.** Check the box or the '
              'maker\'s page.',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked on 28 September 2026. Vendor pages are cited as sources '
          'only, not as recommendations.',
        ),
        LessonSourceList(<String>[
          'GL.iNet Router Docs 4, "Repeater" '
              '(docs.gl-inet.com/router/en/4/interface_guide/internet_repeater/): '
              'the router creates its own subnet and acts as a firewall '
              'between you and the public network',
          'GL.iNet Router Docs 4, "Connect to public hotspot with '
              'Captive Portal" '
              '(docs.gl-inet.com/router/en/4/faq/connect_to_a_hotspot_with_captive_portal/): '
              'turn off VPN and DNS rebinding protection before the sign-in '
              'page; MAC clone for device-tied sign-ins',
          'GL.iNet Router Docs 4, "Ethernet" '
              '(docs.gl-inet.com/router/en/4/interface_guide/internet_ethernet/): '
              'connect the router\'s internet port to an Ethernet jack',
          'GL.iNet blog, "Bypass Captive Portals and Device Limits," 17 '
              'October 2024: some hotels limit devices; only the router '
              'signs in; a VPN on the router covers every connected device',
          'GL.iNet Router Docs 4, "Network Mode" '
              '(docs.gl-inet.com/router/en/4/interface_guide/network_mode/): '
              'access point mode turns off NAT and DHCP; router mode keeps '
              'NAT, DHCP and the firewall',
          'Google for Developers, Cast "Discovery Troubleshooting": the '
              'sender and the Cast device must be on the same Wi-Fi network',
          'Apple Support 102169, "How Apple devices decide which known '
              'wireless networks to auto-join"',
          'US Federal Trade Commission, "In the market for a VPN app?," '
              'February 2018',
          'IETF RFC 3022, "Traditional IP Network Address Translator," '
              'January 2001: many devices sharing one address',
          'Keith Parsons, LinkedIn post on travel routers, 3 September '
              '2026',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want their '
              'devices online in a hotel with less fuss. It is '
              'independent, and isn\'t affiliated with or endorsed by '
              'any router maker or hotel company. It names no brand to '
              'buy.',
        ),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
