// Weak Cell Signal at Home, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   weak-cell-signal-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kWeakCellSignalLesson = GuidedLesson(
  toolId: 'weak-cell-signal-explained',
  route: '/tools/weak-cell-signal-explained',
  title: 'Weak Cell Signal at Home, Explained',
  guideTitle: 'Weak Cell Signal at Home, Explained',
  tagline: 'A plain-English guide',
  promise:
      'Why your phone has bars at the curb and drops calls in the kitchen, '
      'and the free fix to try first.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/weak-cell-signal/cover.svg',
    width: 700,
    height: 270,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Most weak signal indoors isn\'t your phone. It isn\'t the tower '
          'either. It\'s the building. A signal that\'s fine at the curb '
          'can lose most of its strength getting through a wall or a '
          'window.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: '1. Wi-Fi Calling',
            body:
                'Free, and already in your phone. Calls travel over your '
                'home internet, so walls don\'t matter. Try it first.',
          ),
          LessonCardData(
            title: '2. A booster',
            body:
                'An outside antenna, an amplifier and an inside antenna. '
                'It only helps if there\'s some signal outside.',
          ),
          LessonCardData(
            title: '3. A network extender',
            body:
                'A tiny cell tower from your carrier that runs over your '
                'home internet. Not every carrier still sells one.',
          ),
        ]),
        LessonCallout.note(
          title: 'The one idea behind this guide',
          body:
              'A booster doesn\'t make signal. It makes whatever it '
              'hears outside louder, noise and all. If there\'s nothing '
              'usable outside, there\'s nothing to boost.',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**Carrier** means your mobile phone company. **Bars** are '
              'your phone\'s rough guess at signal strength. **dB** is '
              'how engineers count signal loss. Losing 10 dB leaves one '
              'tenth of the signal. Losing 20 dB leaves one hundredth.',
        ),
      ],
    ),
    // ── 2. What a wall costs a signal ──────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'What a wall costs a signal',
      blocks: <LessonBlock>[
        LessonLede(
          'The signal from the tower crosses a long stretch of open air. '
          'Then it has to get through your house. Every layer takes a '
          'share.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-01.svg',
          width: 760,
          height: 248,
          caption:
              '**Figure 1. Some materials barely matter. Some block a '
              'lot.** Wood, drywall and plain glass take little. '
              'Concrete takes much more. These are computed for one '
              'layer, head-on.',
        ),
        LessonText(
          'Metal takes the most of all. It bounces radio waves back, the '
          'way a mirror bounces light.',
        ),
      ],
    ),
    // ── 3. What a lab measured ─────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'What a lab measured',
      blocks: <LessonBlock>[
        LessonLede(
          'A lab in the UK tested real building materials. Its results '
          'tell the same story.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-02.svg',
          width: 760,
          height: 164,
          caption:
              '**Figure 2. Measured in a lab.** Same scale as Figure '
              '1. Longer bars mean more signal lost.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note, from __Fix Your Own Wi-Fi__',
          body:
              '"What sits between you and the box matters just as much. '
              'A thick wall, a brick chimney, a mirrored door, a metal '
              'filing cabinet, a refrigerator, a fish tank full of '
              'water. Any of those can take a real bite out of the '
              'signal, and how big a bite depends on what it is actually '
              'made of and how squarely it sits in the way."',
          attribution:
              'He wrote it about Wi-Fi. The tower\'s signal '
              'crosses the same materials.',
        ),
      ],
    ),
    // ── 4. Energy-efficient homes block more ───────────────────────────────
    LessonStep(
      number: '4',
      title: 'Energy-efficient homes block more',
      blocks: <LessonBlock>[
        LessonLede('The features that keep heat in also keep radio out.'),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-03.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 3. A thin layer of metal sends the signal '
              'back outside.** It might be foil in the wall or a '
              'coating on the glass. What reaches the kitchen comes '
              'in through the gaps.',
        ),
        LessonBullets(<String>[
          '**Low-E windows** carry a see-through coating that reflects '
              'heat. The coating is a thin layer of metal, thinner than you '
              'can see. It reflects radio waves too.',
          '**Foil-backed insulation and drywall** work the same way. So '
              'do metal siding and metal roofs.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-04.svg',
          width: 760,
          height: 312,
          caption:
              '**Figure 4. A sealed house lets signal in only through '
              'its gaps.** Lime is the signal that gets in. Gray is '
              'the signal the coatings send back. Not to scale.',
        ),
        LessonText(
          'But a well-sealed house can still cut the signal to a tenth.',
        ),
      ],
    ),
    // ── 5. Why 5G struggles indoors ────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Why 5G struggles indoors',
      blocks: <LessonBlock>[
        LessonLede(
          'Carriers use many radio bands. Low bands travel far and get '
          'through walls well. Higher bands carry much more data, '
          'including most fast 5G. But walls take more out of them.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-05.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 5. Higher bands lose more through the wall.** '
              'The energy-efficient building (green) loses much more '
              'at the higher band on the right. The older building '
              'barely changes.',
        ),
        LessonText(
          'Your phone moves to whatever band it can hear. Outdoors that\'s '
          'often fast 5G. Indoors it\'s often a slower low band. So "5G '
          'outside, one bar in the kitchen" is normal. A new phone won\'t '
          'change it, because the walls are the same.',
        ),
      ],
    ),
    // ── 6. Find where the signal is ────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Find where the signal is',
      blocks: <LessonBlock>[
        LessonLede(
          'Ten minutes with your own phone tells you which fix fits. Judge '
          'by whether a call holds up, not by the bars.',
        ),
        LessonSteps(<String>[
          '**Room by room.** Make a short call in each room you care '
              'about. Note where it breaks up.',
          '**At the windows.** Try a window on each side of the house. '
              'The best side probably faces the tower.',
          '**Up and down.** Signal is often better upstairs and worse in '
              'a basement.',
          '**Outside.** Walk around the house and the yard. This step '
              'decides whether a booster can help.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-06.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 6. The outdoor test decides it.** A booster '
              'needs signal outside to bring in. Wi-Fi Calling and a '
              'network extender don\'t.',
        ),
      ],
    ),
    // ── 7. Wi-Fi Calling: the free fix ─────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Wi-Fi Calling: the free fix',
      blocks: <LessonBlock>[
        LessonLede(
          'If you have home internet and Wi-Fi in the room, turn on Wi-Fi '
          'Calling before you spend anything.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-07.svg',
          width: 760,
          height: 280,
          caption:
              '**Figure 7. Wi-Fi Calling goes around the walls.** The '
              'lime path is your call: over your Wi-Fi and your home '
              'internet to your carrier.',
        ),
        LessonText(
          'Wi-Fi Calling is your own carrier\'s calling service, reaching '
          'your phone over your home internet instead of the tower. Same '
          'number, same phone app, same texts.',
        ),
        LessonText(
          'It\'s a switch in your phone\'s settings. Each person turns it '
          'on for their own phone. Your carrier asks for an emergency '
          'address, so keep it up to date.',
        ),
        LessonHeading('Where it falls short'),
        LessonBullets(<String>[
          '**Power or internet outage.** It stops when your internet '
              'stops. Plan how you\'d call for help.',
          '**Visitors.** A guest\'s phone uses it only if they join your '
              'Wi-Fi and turn it on.',
          '**Weak Wi-Fi.** If Wi-Fi is poor in that room, calls will be '
              'too. That\'s a Wi-Fi fix.',
        ]),
        LessonCallout.note(
          title: 'The full story has its own guide',
          body:
              'Settings for iPhone and Android, emergency calls and '
              'calling home from abroad are in __Wi-Fi Calling, '
              'Explained__.',
        ),
        LessonToolLink('wifi-calling-explained'),
      ],
    ),
    // ── 8. How a signal booster works ──────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'How a signal booster works',
      blocks: <LessonBlock>[
        LessonLede(
          'A home booster has three parts joined by cable: an outside '
          'antenna, an amplifier, and an inside antenna. It works both '
          'ways, so your phone\'s reply goes back out the same path.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-08.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 8. Catch it outside, repeat it inside.** The '
              'outside antenna faces the tower. The amplifier makes '
              'the signal stronger. The inside antenna fills one part '
              'of the house.',
        ),
        LessonHeading('Why it needs signal outside'),
        LessonText(
          'An amplifier makes everything louder, including the background '
          'noise that\'s always there. If the outside signal is buried in '
          'noise, you just get louder noise. The UK regulator puts it '
          'simply: boosters "work best when there is a good outdoor '
          'signal."',
        ),
      ],
    ),
    // ── 9. Keep the two antennas apart ─────────────────────────────────────
    LessonStep(
      number: '9',
      title: 'Keep the two antennas apart',
      blocks: <LessonBlock>[
        LessonLede(
          'The inside antenna talks. The outside antenna listens. If the '
          'outside one hears the inside one, the booster feeds on itself, '
          'like a microphone that howls near its speaker.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-09.svg',
          width: 760,
          height: 170,
          caption:
              '**Figure 9. Distance and walls keep them apart.** The '
              'gap between the two antennas has to block more than '
              'the booster adds.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-10.svg',
          width: 720,
          height: 176,
          caption:
              '**Figure 10. Open air alone isn\'t enough.** The bar '
              'on the left is how much an all-carrier home booster '
              'may add. The others show how much distance takes away. '
              'Walls and the roof make up the rest.',
        ),
        LessonText(
          'If they\'re too close, the booster turns itself down. Then the '
          'good-signal area shrinks, sometimes to one room. Mount the '
          'outside antenna high, aimed at the tower. Put the inside '
          'antenna far away, with the roof or walls between.',
          small: true,
        ),
      ],
    ),
    // ── 10. The rules for boosters ─────────────────────────────────────────
    LessonStep(
      number: '10',
      title: 'The rules for boosters',
      blocks: <LessonBlock>[
        LessonLede(
          'A bad booster can interfere with everyone\'s service, so there '
          'are rules.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-11.svg',
          width: 760,
          height: 196,
          caption:
              '**Figure 11. Register first, then switch it on.** Your '
              'carrier has to know about a booster before it goes on '
              'the air.',
        ),
        LessonSteps(<String>[
          '**In the US, buy one labeled as a consumer booster.**',
          '**Register it with your carrier, free, before you turn it '
              'on.** Your carrier\'s website shows how.',
          '**Check it carries your carrier\'s bands.** Ask your carrier '
              'which bands serve your area, and compare with the box.',
          '**Use only the parts it came with,** and turn it off if your '
              'carrier asks.',
        ]),
        LessonText(
          '**Outside the US,** rules vary. The UK allows some approved '
          'models. Australia allows one only with your carrier\'s written '
          'OK. Check with your carrier and your country\'s regulator first.',
        ),
        LessonCallout.stop(
          title: 'Emergency calls through a booster',
          body:
              'The required label warns that your location may be '
              'missing or wrong when you call 911 through a booster. '
              'Tell the dispatcher where you are.',
        ),
        LessonCallout.caution(
          title: 'RVs and boats',
          body:
              'A home booster is only for a fixed spot inside a '
              'building. Boosters for cars, boats and RVs are a '
              'different kind.',
        ),
      ],
    ),
    // ── 11. Network extenders ──────────────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Network extenders',
      blocks: <LessonBlock>[
        LessonLede(
          'A network extender is a tiny cell tower from your own carrier. '
          'It sits in your house and connects over your home internet. '
          'Your phone thinks it\'s a tower.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-12.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 12. Three ways into the same carrier.** Two '
              'ride your internet and ignore the walls. The booster '
              'rides the tower\'s own signal and needs some of it '
              'outside.',
        ),
        LessonText(
          'Like Wi-Fi Calling, it needs no signal outside. Unlike Wi-Fi '
          'Calling, it can also work for a visitor\'s phone on the same '
          'carrier. It needs power and internet, and it stops in an outage.',
        ),
        LessonText(
          'Not every carrier still sells one. Ask yours. Some lend them to '
          'customers who qualify.',
        ),
      ],
    ),
    // ── 12. The three fixes side by side ───────────────────────────────────
    LessonStep(
      number: '12',
      title: 'The three fixes side by side',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/weak-cell-signal/fig-13.svg',
          width: 760,
          height: 480,
          caption:
              '**Figure 13. Each fix wins in different places.** Read '
              'down a column to see one fix. A lime check means it '
              'works in your favor.',
        ),
        LessonCallout.note(
          title: 'The order that saves money',
          body:
              'Wi-Fi Calling first. Then check for signal outside. Only '
              'then choose a booster or a network extender.',
        ),
      ],
    ),
    // ── 13. Four things people get wrong ───────────────────────────────────
    LessonStep(
      number: '13',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'A booster creates signal where there is none.',
          fact:
              'It only makes louder what its outside antenna hears. No '
              'signal outside, nothing to boost.',
        ),
        LessonMyth(
          myth: 'It\'s my phone.',
          fact:
              'Usually it\'s the building. Coated windows and '
              'foil-backed walls block far more than plain glass.',
        ),
        LessonMyth(
          myth: '5G will fix my indoor coverage.',
          fact:
              'The fast 5G bands lose more through walls. Indoors your '
              'phone often uses a slower band.',
        ),
        LessonMyth(
          myth: 'Put the booster\'s antenna where the signal is weakest.',
          fact:
              'The outside antenna goes where the signal is strongest. '
              'The inside one goes where you need it.',
        ),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked in September 2026. Carrier products and pages change, '
          'so read your carrier\'s current page before you buy.',
          small: true,
        ),
        LessonSourceList(<String>[
          '47 CFR § 20.21, Signal boosters (eCFR, up to date as of 24 '
              'September 2026; section last amended 2018): conditions (a)(1) '
              'to (7), label text (f), registration (h), network protection '
              'standard (e), gain limits (e)(8)(i)(C), anti-oscillation '
              '(e)(5), power down (e)(6)',
          'FCC, Consumer Signal Boosters '
              '(fcc.gov/wireless/bureau-divisions/mobility-division/signal-boosters/consumer-signal-boosters), '
              'page updated 14 March 2016; read from the Internet Archive '
              'copy of 25 March 2026 because fcc.gov refused automated '
              'requests',
          'ITU-R P.2040-4 (09/2025), Effects of building materials and '
              'structures on radiowave propagation above about 100 MHz: '
              '§2.2.2.1 multilayer method and Table 3 material constants '
              '(Figure 1, computed head-on)',
          'Ofcom, Building Materials and Propagation, Final Report '
              '2604/BMEM/R/3/2.0 (Aegis Systems, Signal Science and BRE, 14 '
              'September 2014): Table D-1 lab losses; §8 whole-house '
              'results; §4.3 thin metal films',
          '3GPP TR 38.901 V17.0.0 (ETSI TR 138 901, 2022-04): Table '
              '7.4.3-1 material penetration losses and Table 7.4.3-2 O2I '
              'building penetration loss model (Figure 5)',
          'Free-space path loss between isotropic antennas at 1880 MHz: '
              '20 log₁₀(d in m) + 20 log₁₀(f in MHz) − 27.55 dB (Figure 10)',
          'Ofcom, Statement: Mobile phone repeaters (statement 4 '
              'November 2021; Wireless Telegraphy (Mobile Repeater) '
              '(Exemption) Regulations 2022 in force 16 June 2022; '
              'consultation 4 October 2023), read from the Internet Archive '
              'copy of 14 August 2025',
          'ACMA, Using mobile phone boosters and repeaters '
              '(acma.gov.au/using-mobile-phone-boosters-and-repeaters), read '
              'from the Internet Archive copy of 19 April 2026',
          'Verizon, Consumer signal booster registration page and FAQ '
              '(verizon.com/solutions-and-services/accessories/register-signal-booster)',
          'T-Mobile Support, Register a signal booster; 4G LTE CellSpot '
              'setup & help',
          'AT&T Signal Booster FAQ (attsignalbooster.com/faq.html)',
          'Verizon LTE Network Extender product page and LTE Network '
              'Extender FAQs; Verizon "No longer supported" device list',
          'AT&T Cell Booster product page '
              '(att.com/buy/accessories/Specialty-Items/att-cell-booster.html); '
              'AT&T Cell Booster FAQ, KM1459978, updated 26 August 2026',
          'Keith Parsons, __Fix Your Own Wi-Fi__, Chapter 5 (the '
              'quotation in step 3)',
        ]),
        LessonCallout.note(
          title: 'Other guides in this series',
          body:
              '__Wi-Fi Calling, Explained__ · __Home Internet, '
              'Explained__ · __How Your Devices Access the Internet, '
              'Explained__ · __Starlink, Explained__ · __Find My, '
              'Explained__',
        ),
        LessonToolLink('wifi-calling-explained'),
        LessonToolLink('home-internet-explained'),
        LessonToolLink('devices-to-internet-explained'),
        LessonToolLink('starlink-explained'),
        LessonToolLink('find-my-explained'),
        LessonText(
          'No booster brand is named or recommended in this guide. WLAN '
          'Pros has no relationship with any booster maker or carrier.',
          small: true,
        ),
      ],
    ),
  ],
);
