// Wi-Fi and Your Health, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   wifi-and-health-explained--SOURCE.html
//   myPKA commit 2def3efa 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kWifiAndHealthLesson = GuidedLesson(
  toolId: 'wifi-and-health-explained',
  route: '/tools/wifi-and-health-explained',
  title: 'Wi-Fi and Your Health, Explained',
  guideTitle: 'Wi-Fi and Your Health, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How much power Wi-Fi sends, how fast it fades, and what health '
      'agencies say about it.',
  byline: <String>[
    'Keith Parsons · CWNE #3',
    'Wireless LAN Professionals · October 2026',
  ],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/wifi-and-health/cover.svg',
    width: 760,
    height: 260,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'A Wi-Fi router sends about a tenth of a watt. That\'s tiny. The '
          'signal also fades fast as it spreads out. In real homes and '
          'schools, it measures far below the safety limits.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'The power',
            body:
                'A router sends about a tenth of a watt. A microwave '
                'oven uses thousands of times more, and keeps it inside '
                'a metal box.',
          ),
          LessonCardData(
            title: 'The distance',
            body:
                'Radio power thins out as it spreads. Step twice as far '
                'away and you get a quarter as much.',
          ),
          LessonCardData(
            title: 'The agencies',
            body:
                'Health agencies have looked hard. They have found no '
                'consistent evidence that Wi-Fi within the limits harms '
                'people.',
          ),
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'This guide explains the power numbers in plain words. It '
              'isn\'t medical advice. If you have a question about your '
              'own health, ask your doctor.',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'A **watt** measures power. **Radiation** just means '
              'energy that travels outward. Light and radio waves count, '
              'and so do X-rays. But they are different kinds, as the '
              'next step shows.',
        ),
      ],
    ),
    // ── 2. Radio waves are not X-rays ──────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'Radio waves are not X-rays',
      blocks: <LessonBlock>[
        LessonLede(
          'The word radiation covers everything from radio to X-rays. What '
          'matters is which kind.',
        ),
        LessonText(
          'Scientists split it into two groups. X-rays carry enough energy '
          'to knock bits off atoms. That\'s called **ionizing** radiation. '
          'Radio waves and light don\'t have that much energy. They\'re '
          'called **non-ionizing**. Wi-Fi is on the non-ionizing side.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-01.svg',
          width: 760,
          height: 420,
          caption:
              '**Figure 1. The range of energy, from radio to '
              'X-rays.** Energy rises from left to right. Wi-Fi sits '
              'in the microwave band. The dividing line falls in the '
              'ultraviolet, and too much of that burns skin. Not to '
              'scale.',
        ),
        LessonText(
          'What radio waves can do, if the power is high enough, is heat '
          'things. That\'s how a microwave oven cooks. The safety limits '
          'are built around heating (step 6).',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body: '“Wi-Fi is low-power, non-ionizing radio energy.”',
          attribution: 'Keith Parsons, LinkedIn post, 2026',
        ),
      ],
    ),
    // ── 3. A tenth of a watt ───────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'A tenth of a watt',
      blocks: <LessonBlock>[
        LessonLede(
          'A typical Wi-Fi router sends about a tenth of a watt. Your '
          'phone or laptop sends about the same over Wi-Fi.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-02.svg',
          width: 760,
          height: 395.75,
          caption:
              '**Figure 2. The same four powers, drawn two ways.** '
              '(a) On an ordinary ruler the oven fills the width. The '
              'router, phone and Wi-Fi cap are too thin to see. (b) '
              'Each step to the right is ten times the one before. On '
              'this scale the oven looks close. On a ruler it\'s '
              'thousands of times the router. Every bar ends at its '
              'value.',
        ),
        LessonText(
          '__Scales and Ratios, Explained__ shows how these power numbers '
          'work.',
        ),
        LessonToolLink('scales-and-ratios-explained'),
        LessonLede(
          'A kitchen microwave oven uses about 1,200 watts. That\'s '
          'thousands of times more than a router. And the oven\'s metal '
          'box keeps the energy inside.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-03.svg',
          width: 760,
          height: 500,
          caption:
              '**Figure 3. Thousands of times the power, kept in a '
              'box.** Left, the oven\'s energy bounces around inside '
              'its metal box. Right, a router\'s tenth of a watt '
              'spreads out into the room. Not to scale.',
        ),
      ],
    ),
    // ── 4. Why distance matters so much ────────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Why distance matters so much',
      blocks: <LessonBlock>[
        LessonLede(
          'A router\'s signal spreads out as it travels. The same power '
          'has to cover a bigger and bigger area.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-04.svg',
          width: 760,
          height: 384,
          caption:
              '**Figure 4. The same power, spread over more area.** '
              'Twice as far away, the power covers four squares. So '
              'each square gets a quarter. Not to scale.',
        ),
        LessonText(
          'Scientists call this the inverse-square law. Step twice as far '
          'away, and you get a quarter of the power. Step four times as '
          'far, and you get a sixteenth.',
        ),
        LessonLede(
          'Walls and furniture soak up some of the signal too. So in a '
          'real home, it fades even faster.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-05.svg',
          width: 760,
          height: 330,
          caption:
              '**Figure 5. Walls soak up signal too.** Top, open air. '
              'Bottom, the same distance through a wall: less reaches '
              'the far side. Not to scale.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          body:
              '“Walls, floors, furniture, and distance all chew up the '
              'radio signal between you and the box on the wall, and the '
              'further away you sit, the more gets chewed up.”',
          attribution:
              'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, '
              'in preparation, 2026), chapter 5',
        ),
      ],
    ),
    // ── 5. How far below the limit? ────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'How far below the limit?',
      blocks: <LessonBlock>[
        LessonLede(
          'Now compare a router with the safety limit for the public.',
        ),
        LessonText(
          'Picture a router sending nonstop, with nothing in the way. At 1 '
          'm (3 feet), it reaches about a thousandth of the limit.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-06.svg',
          width: 760,
          height: 224,
          caption:
              '**Figure 6. How much of the public limit a router '
              'reaches.** A router sending nonstop, with no walls in '
              'the way. Distances to scale.',
        ),
        LessonText(
          'Real routers send in short bursts, only when there\'s data to '
          'move. So real levels are lower still.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-07.svg',
          width: 760,
          height: 244,
          caption:
              '**Figure 7. A real router sends in short bursts.** '
              'Top, the math in this step. Bottom, a real router, '
              'sending only when there\'s data to move. Not to scale.',
        ),
        LessonText(
          'Even the strongest router the rules allow stays well under the '
          'limit at arm\'s length.',
        ),
      ],
    ),
    // ── 6. How the limits are set ──────────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'How the limits are set',
      blocks: <LessonBlock>[
        LessonLede(
          'The limits start with the level of radio energy that warms the '
          'body. Then they add a big safety margin.',
        ),
        LessonText(
          'Scientists found the level that warms the whole body by about 1 '
          '°C (2 °F).',
        ),
        LessonText(
          'For workers who know about the exposure, the limit is a tenth '
          'of that level. For everyone else, it\'s a fiftieth.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-08.svg',
          width: 760,
          height: 184,
          caption:
              '**Figure 8. The safety margin.** The public limit is a '
              'fiftieth of the level that warms the body. Each bar is '
              'drawn to scale.',
        ),
        LessonText(
          'The limit also assumes you\'re in the signal all day, every '
          'day, with no end.',
        ),
        LessonText(
          'Phones held to your head are a different question from Wi-Fi. '
          'They get their own test, and this guide doesn\'t cover them.',
        ),
      ],
    ),
    // ── 7. What was measured, and what agencies say ────────────────────────
    LessonStep(
      number: '7',
      title: 'What was measured, and what agencies say',
      blocks: <LessonBlock>[
        LessonLede(
          'Math shows the most a router could reach. Australia\'s '
          'radiation agency went into schools to measure what was there.',
        ),
        LessonText(
          'They measured Wi-Fi in 23 schools. In a typical classroom, '
          'Wi-Fi was about a millionth of the limit. That\'s far below the '
          'math in step 5.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-09.svg',
          width: 760,
          height: 507.75,
          caption:
              '**Figure 9. Figured and measured, against the public '
              'limit.** (a) On an ordinary ruler, only the limit '
              'shows. (b) Each step to the right is ten times the one '
              'before. Classroom values are rounded, so they are '
              'shown as "about."',
        ),
        LessonText(
          'The UK\'s health agency tested schools too. It found Wi-Fi '
          'exposure was small compared with the limits.',
        ),
        LessonHeading('What the agencies say'),
        LessonCallout.quote(
          speaker: 'UK Health Security Agency',
          body:
              '“There is no consistent evidence that exposure to radio '
              'signals from Wi-Fi devices adversely affects the health '
              'of the general population.”',
          attribution:
              'UKHSA, Wi-Fi radio waves and health, updated 19 '
              'February 2025',
        ),
        LessonCallout.quote(
          speaker: 'World Health Organization',
          body:
              '“To date, and after much research performed, no adverse '
              'health effect has been causally linked with exposure to '
              'wireless technologies.”',
          attribution:
              'WHO, Radiation: 5G mobile networks and health, 27 '
              'February 2020',
        ),
        LessonText(
          'In plain words: after a lot of research, they have not found '
          'that Wi-Fi within the limits harms people. They keep watching '
          'new studies.',
        ),
      ],
    ),
    // ── 8. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonLede(
          'Each of these comes up often. Each one has a simple answer.',
        ),
        LessonMyth(
          myth: 'A router puts out about as much power as a microwave oven.',
          fact:
              'The typical oven uses 1,200 W. A router uses thousands of '
              'times less. And the oven\'s metal box keeps the energy '
              'inside.',
        ),
        LessonMyth(
          myth: 'Turning Wi-Fi off at night makes a big difference.',
          fact:
              'Across a room, a router reaches a tiny sliver of the '
              'limit. Health agencies say no extra steps are needed. '
              'Turning it off is still your choice (step 9).',
        ),
        LessonMyth(
          myth: 'Newer Wi-Fi raised the power.',
          fact:
              'Power rules are set for each band of radio frequencies, '
              'not for each version of Wi-Fi. A new version doesn\'t get '
              'a bigger allowance.',
        ),
        LessonMyth(
          myth: 'Nobody has studied it.',
          fact:
              'Health agencies have studied it a lot. Some even measured '
              'Wi-Fi in schools (step 7).',
        ),
      ],
    ),
    // ── 9. If you want less exposure anyway ────────────────────────────────
    LessonStep(
      number: '9',
      title: 'If you want less exposure anyway',
      blocks: <LessonBlock>[
        LessonLede(
          'Health agencies say no extra steps are needed. Some people want '
          'to take steps anyway. For Wi-Fi, distance does almost all the '
          'work.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-and-health/fig-10.svg',
          width: 760,
          height: 400,
          caption:
              '**Figure 10. A shelf across the room.** The same '
              'router, moved from beside the sofa to a shelf on the '
              'far wall.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'Keep a little distance from the router.',
            body: 'Four times farther away means a sixteenth of the power.',
          ),
          LessonCardData(
            title:
                'Put the router where nobody sits right beside it for '
                'hours.',
            body: 'A shelf across the room does more than any gadget.',
          ),
          LessonCardData(
            title: 'Turning Wi-Fi off at night is your choice.',
            body: 'It isn\'t needed. If you do it, know what stops working.',
          ),
        ]),
        LessonCallout.caution(
          title: 'Turning Wi-Fi off at night stops what depends on it',
          body:
              'Security cameras and video doorbells stop. So does '
              'anything else that uses your Wi-Fi. They start again when '
              'it comes back on. __Cameras, Doorbells and Baby Monitors, '
              'Explained__ covers what each kind still does offline.',
        ),
        LessonToolLink('cameras-doorbells-explained'),
        LessonCallout.note(
          title: 'Other guides in this series',
          body:
              '__Scales and Ratios, Explained__ covers power and why '
              'distance costs so much signal. __Mesh, Extenders and '
              'Wired Access Points, Explained__ covers where to put '
              'Wi-Fi gear in a home.',
        ),
        LessonToolLink('scales-and-ratios-explained'),
        LessonToolLink('mesh-extenders-explained'),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked 28 September 2026. Agency pages are quoted as they read '
          'that day, with the date each one carries.',
          small: true,
        ),
        LessonSourceList(<String>[
          'UK Health Security Agency, "Wi-Fi radio waves and health," '
              'updated 19 February 2025: typical Wi-Fi power of 0.1 W, '
              'school measurements, no consistent evidence, no further '
              'action needed',
          'WHO, "Radiation: 5G mobile networks and health," questions '
              'and answers, 27 February 2020: heating as the main effect; no '
              'adverse health effect causally linked',
          'US Code of Federal Regulations, 47 CFR 1.1310 (FCC public '
              'exposure limit of 1.0 mW/cm² at Wi-Fi frequencies, 30-minute '
              'average, for continuous exposure); 47 CFR 15.247 and 15.407 '
              '(Wi-Fi power caps set by band; 1 W and 6 dBi at 2.4 GHz)',
          'ICNIRP, "Guidelines for Limiting Exposure to Electromagnetic '
              'Fields (100 kHz to 300 GHz)," __Health Physics__, 2020: 4 '
              'W/kg and a rise of about 1 °C; reduction factors of 10 for '
              'workers and 50 for the public',
          '3GPP TS 38.101-1 (ETSI TS 138 101-1 V17.5.0, 2022), Table '
              '6.2.1-1: default phone power of 23 dBm (0.2 W)',
          'US Department of Energy, "DOE Microwave Oven Active Mode Test '
              'Procedure Investigations," September 2010: "a typical 1,200 '
              'watt (W)-rated microwave oven"',
          'FDA, "Microwave Ovens," content current as of 12 October '
              '2023: microwaves reflect off the oven\'s metal interior',
          'CDC, "Non-ionizing Radiation," 15 June 2026: not enough '
              'energy to remove electrons; the dividing line in the '
              'ultraviolet; effects of too much UV',
          'K. Karipidis and others, "Exposure to Radiofrequency '
              'Electromagnetic Fields From Wi-Fi in Australian Schools," '
              '__Radiation Protection Dosimetry__ 175 (2017) 432: 23 '
              'schools; typical classroom Wi-Fi of the order of 10−4% of the '
              'guidelines',
          'Figure 4 and 6 math: 0.1 W spread evenly, sending nonstop, '
              'against 10 W/m². At 1 m, 0.1 ÷ (4 × π × 1²) = 0.008 W/m², '
              'about 1/1,257 of the limit. The strongest 2.4 GHz case (1 W '
              'at 6 dBi) is about 1/32 at 1 m.',
          'Keith Parsons, __Fix Your Own Wi-Fi__ (WLAN Pros, in '
              'preparation, 2026), chapter 5; Keith Parsons, LinkedIn, 2026',
        ]),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
