// Wi-Fi on Planes, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   wifi-on-planes-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kWifiOnPlanesLesson = GuidedLesson(
  toolId: 'wifi-on-planes-explained',
  route: '/tools/wifi-on-planes-explained',
  title: 'Wi-Fi on Planes, Explained',
  guideTitle: 'Wi-Fi on Planes, Explained',
  tagline: 'A plain-English guide',
  promise:
      'What airplane mode turns off, why plane Wi-Fi feels slow, and how '
      'to get online in your seat.',
  byline: <String>['Keith Parsons · CWNE #3', 'September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/wifi-on-planes/cover.svg',
    width: 760,
    height: 322,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Airplane mode turns off your phone\'s radios. Cellular is the '
          'one that matters in the air, so keep it off. If the airline '
          'allows it, you can turn Wi-Fi and Bluetooth back on.',
        ),
        LessonText(
          'The plane\'s Wi-Fi works, but it feels slow. Everyone on board '
          'shares one link to the ground. Often that link goes through a '
          'satellite far out in space.',
        ),
        LessonText(
          'This guide answers three questions. What does airplane mode '
          'turn off? Why is plane Wi-Fi slow? And how do you get online in '
          'your seat?',
        ),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              '**Cellular** is your phone\'s link to your carrier\'s '
              'towers, for calls, texts and mobile data. **Airplane '
              'mode** is the switch that turns your radios off. Some '
              'phones call it **Flight mode**.',
        ),
      ],
    ),
    // ── 2. What airplane mode turns off ────────────────────────────────────
    LessonStep(
      number: '2',
      title: 'What airplane mode turns off',
      blocks: <LessonBlock>[
        LessonLede(
          'One switch turns off cellular, and usually Wi-Fi and Bluetooth '
          'too.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-01.svg',
          width: 760,
          height: 500,
          caption:
              '**Figure 1. One switch, three radios.** Keep cellular '
              'off in the air. Turn Wi-Fi and Bluetooth back on only '
              'if the airline allows it.',
        ),
        LessonHeading('Check the top of your screen'),
        LessonText(
          'Here\'s the surprise. Your phone remembers what you did last '
          'time. If you turned Wi-Fi on during your last flight, it may '
          'stay on next time.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-02.svg',
          width: 760,
          height: 216,
          caption:
              '**Figure 2. Your phone remembers your last flight.** '
              'Left, last time: you turned Wi-Fi back on. Right, this '
              'time: airplane mode leaves it on.',
        ),
        LessonText(
          'So take a quick look at the top of your screen. The Wi-Fi or '
          'Bluetooth symbol means that radio is on. You should see no '
          'signal bars and no carrier name.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-03.svg',
          width: 760,
          height: 232,
          caption:
              '**Figure 3. What to look for.** Signal bars, or 5G or '
              'LTE next to the carrier name, mean cellular is still '
              'on.',
        ),
      ],
    ),
    // ── 3. Why the rule exists ─────────────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'Why the rule exists',
      blocks: <LessonBlock>[
        LessonLede(
          'Most people think phones upset the plane\'s instruments. In the '
          'US, the main rule is about the cell towers on the ground.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-04.svg',
          width: 760,
          height: 470,
          caption:
              '**Figure 4. A phone in the air sees too many towers.** '
              'On the ground, hills and buildings limit how many '
              'towers your phone reaches. Up high, nothing is in the '
              'way. Not to scale.',
        ),
        LessonText(
          'A phone up high can reach many cell towers at once. That would '
          'jam up the network for people on the ground. So US rules ban '
          'using cellular in the air.',
        ),
        LessonText(
          'Wi-Fi and Bluetooth are a different story. Each airline decides '
          'which gadgets are fine to use. That\'s why the rules can change '
          'from one airline to the next.',
        ),
        LessonText('When the crew gives an instruction, follow it.'),
      ],
    ),
    // ── 4. How the internet reaches a plane ────────────────────────────────
    LessonStep(
      number: '4',
      title: 'How the internet reaches a plane',
      blocks: <LessonBlock>[
        LessonLede(
          'Inside the cabin, the Wi-Fi is ordinary Wi-Fi. The hard part is '
          'the next step, from the plane down to the ground.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-05.svg',
          width: 760,
          height: 530,
          caption:
              '**Figure 5. Three ways down to the ground.** Towers '
              'work over land. Satellites also work over oceans. The '
              'far-away satellite adds the most delay. Not to scale.',
        ),
        LessonText(
          'Over land, some planes talk to special towers that point up at '
          'the sky.',
        ),
        LessonText(
          'Over oceans, planes use satellites. Some satellites fly low and '
          'close. Others sit very far away, about 36,000 km (22,000 miles) '
          'up.',
        ),
        LessonLede(
          'The far ones are the slow ones. Your message has to travel all '
          'the way up and back down, and so does the reply.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-06.svg',
          width: 760,
          height: 640,
          caption:
              '**Figure 6. The long way round.** Your message and its '
              'reply each go up to the satellite and back down. '
              'Follow the numbers 1 to 4. Not to scale.',
        ),
        LessonText(
          'A far-away satellite adds a delay you can\'t fix from your '
          'seat. On one of Keith\'s flights across the Atlantic, every '
          'test message took more than half a second to come back.',
        ),
      ],
    ),
    // ── 5. Why it feels slow ───────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Why it feels slow',
      blocks: <LessonBlock>[
        LessonLede(
          'Every phone, laptop and tablet on board shares one link to the '
          'ground. At home a few people share your internet. On a plane, '
          'it\'s everyone.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-07.svg',
          width: 760,
          height: 540,
          caption:
              '**Figure 7. Everyone on board shares the link.** The '
              'same link, cut into a few wide lanes at home and many '
              'thin slices on a plane. Not to scale.',
        ),
        LessonHeading('What works, and what doesn\'t'),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-08.svg',
          width: 760,
          height: 598,
          caption:
              '**Figure 8. Small jobs fit in your slice. Big ones '
              'don\'t.** Each bar is how much of the link a job '
              'needs; the dashed line is your share. Not to scale.',
        ),
      ],
    ),
    // ── 6. Getting online in your seat ─────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'Getting online in your seat',
      blocks: <LessonBlock>[
        LessonLede(
          'Plane Wi-Fi usually has no password. You join it, and a sign-in '
          'page pops up. It asks you to pay, log in or accept the terms.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-09.svg',
          width: 760,
          height: 416,
          caption:
              '**Figure 9. How the sign-in page appears.** Your phone '
              'checks whether it\'s online. The plane\'s network '
              'answers with its sign-in page instead.',
        ),
        LessonText(
          'Some airlines give free Wi-Fi to members of their '
          'frequent-flyer club. Free still means signing in, so wait for '
          'the page and log in.',
        ),
        LessonHeading('When the sign-in page won\'t appear'),
        LessonText(
          'Open your web browser and go to any web page. The sign-in page '
          'usually shows up. If the airline gives a web address, type that '
          'instead.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-10.svg',
          width: 760,
          height: 440,
          caption:
              '**Figure 10. Open a browser; don\'t tap Cancel.** '
              'Left: going to any web page brings up the sign-in '
              'page. Right: on an iPhone, Cancel disconnects you.',
        ),
        LessonText(
          'On an iPhone, don\'t tap Cancel on the sign-in screen. That '
          'disconnects you, and you have to join again.',
        ),
      ],
    ),
    // ── 7. Four things people get wrong ────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Four things people get wrong',
      blocks: <LessonBlock>[
        LessonMyth(
          myth: 'Airplane mode always turns off Wi-Fi and Bluetooth.',
          fact:
              'It always turns off cellular. If you turned Wi-Fi or '
              'Bluetooth on last time, your phone may leave them on.',
        ),
        LessonMyth(
          myth: 'Airplane mode is only about the plane\'s instruments.',
          fact:
              'In the US, the main rule protects cell towers on the '
              'ground. Each airline decides about gadgets.',
        ),
        LessonMyth(
          myth: 'Plane Wi-Fi comes from towers on the ground.',
          fact:
              'Some does, over land. Over oceans it comes from a '
              'satellite.',
        ),
        LessonMyth(
          myth: 'Free Wi-Fi means no sign-in.',
          fact:
              'Free usually means a free membership and a login. If the '
              'page doesn\'t pop up, open your browser.',
        ),
      ],
    ),
    // ── 8. Tips for your next flight ───────────────────────────────────────
    LessonStep(
      number: '8',
      title: 'Tips for your next flight',
      blocks: <LessonBlock>[
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-on-planes/fig-11.svg',
          width: 760,
          height: 330,
          caption:
              '**Figure 11. Do the heavy lifting on the ground.** '
              'Left, on a fast connection before you board. Right, on '
              'the shared link in the air.',
        ),
        LessonSteps(<String>[
          '**Download before you board.** Movies, shows, music and maps. '
              'Don\'t count on streaming in the air.',
          '**Pair your earbuds on the ground.** It\'s easier before the '
              'doors close.',
          '**Finish big updates at home.** Let backups and app updates '
              'run while you\'re on a fast connection.',
          '**Check the top of your screen.** After airplane mode, make '
              'sure cellular is off.',
          '**Message instead of calling.** Apps like iMessage and '
              'WhatsApp get through. Plain texts need Wi-Fi Calling. Calls '
              'often aren\'t allowed.',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked on 28 September 2026. Airline Wi-Fi offers and phone '
          'menus change often.',
          small: true,
        ),
        LessonSourceList(<String>[
          'Apple, iPhone User Guide (iOS 27), __Choose iPhone settings '
              'for travel__ (airplane mode turns off Wi-Fi, Bluetooth and '
              'cellular at first; "it may still be on the next time")',
          'Apple 102554, __Use captive Wi-Fi networks__ (23 April 2026); '
              'Apple Platform Deployment, __Troubleshoot Wi-Fi connectivity '
              'on iPhone and iPad__ (captive.apple.com, DNS); Apple 102433, '
              '__Use Low Data Mode__ (15 September 2025)',
          'Google Pixel Phone Help 12639358 (airplane mode remembers) '
              'and 2819583 (airplane mode settings); Pixel Phone Help '
              '6183600 (sign in to a public network); Android Help 9654714 '
              '(treat as metered); Samsung Australia, Flight mode',
          '47 CFR § 22.925, FCC prohibition on airborne operation of '
              'cellular telephones (eCFR, read 28 September 2026)',
          'FCC 13-157, Notice of Proposed Rulemaking, 12 December 2013 '
              '(why the rule was adopted); FCC FAQ on in-flight mobile '
              'services (2013); FCC 20-170, order terminating the '
              'proceeding, adopted 24 November 2020',
          '14 CFR § 91.21, Portable electronic devices; FAA Advisory '
              'Circular 91.21-1D (27 October 2017), section 9; FAA press '
              'release, 31 October 2013 (Bluetooth, Wi-Fi, low visibility, '
              'stowing, crew instructions)',
          'Gogo, ATG network (coverage: contiguous US, parts of Canada '
              'and Alaska); ESA, types of orbits (35,786 km); SpaceX, '
              'Starlink latency (radio trip under 10 ms) and Starlink\'s '
              'orbital height, as used in __Starlink, Explained__',
          'Keith Parsons, packet capture from his iPhone on a '
              'transatlantic flight, 20 September 2026 (31 ping replies from '
              '1.1.1.1: fastest 614 ms, median 659 ms; captive.apple.com '
              'requests redirected to the airline\'s sign-in page)',
        ]),
        LessonCallout.note(
          title: 'About the author',
          body:
              'Keith Parsons, CWNE #3, has designed, installed and '
              'troubleshot Wi-Fi for over 25 years. He runs Wireless LAN '
              'Professionals and the WLPC conferences.',
        ),
      ],
    ),
  ],
);
