// Wi-Fi Calling, Explained: Guided Lesson content, generated by
// tool/guide_to_lesson.py from the guide's approved source,
//   wifi-calling-explained--SOURCE.html
//   myPKA commit 8c18e40d 2026-09-28
// The text is the guide's own, word for word. See the tool's header for
// what a lesson leaves out and the one change it makes (a printed page
// number becomes a step number). Regenerate rather than hand-edit.

import '../../../../widgets/lesson/guided_lesson.dart';

const GuidedLesson kWifiCallingLesson = GuidedLesson(
  toolId: 'wifi-calling-explained',
  route: '/tools/wifi-calling-explained',
  title: 'Wi-Fi Calling, Explained',
  guideTitle: 'Wi-Fi Calling, Explained',
  tagline: 'A plain-English guide',
  promise:
      'How your phone makes a normal call over Wi-Fi, when that helps, '
      'what it means for emergency calls, and what to set up before your '
      'next trip.',
  byline: <String>['Keith Parsons · CWNE #3', 'Checked 27 September 2026'],
  cover: LessonFigure(
    asset: 'assets/lesson-figures/wifi-calling/cover.svg',
    width: 700,
    height: 250,
  ),
  steps: <LessonStep>[
    // ── 1. The short answer ────────────────────────────────────────────────
    LessonStep(
      number: '1',
      title: 'The short answer',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi Calling lets your phone make a normal call over Wi-Fi '
          'when the cell signal is weak. Same phone app. Same phone '
          'number. Your phone company still carries the call.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-01.svg',
          width: 644,
          height: 226,
          caption:
              '**Figure 1. Same phone, same number, same app.** Only '
              'the road in the middle changes. The person you call '
              'sees your normal number either way.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'Not an app',
            body: 'It\'s built into your phone. You just switch it on.',
          ),
          LessonCardData(
            title: 'Your carrier decides',
            body:
                'Your phone company decides if you get it and where it '
                'works.',
          ),
        ]),
        LessonCallout.note(
          title: 'A word on the words',
          body:
              'Your **carrier** is your mobile phone company. '
              '**Cellular** means the cell tower network. A **tunnel** '
              'is a locked, private path across the internet.',
        ),
      ],
    ),
    // ── 2. Two roads to the same phone company ─────────────────────────────
    LessonStep(
      number: '2',
      title: 'Two roads to the same phone company',
      blocks: <LessonBlock>[
        LessonLede(
          'A normal call goes from your phone to a cell tower. A Wi-Fi '
          'call goes across the Wi-Fi and the internet instead. Both end '
          'up at your carrier.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-02.svg',
          width: 760,
          height: 300,
          caption:
              '**Figure 2. Two roads, one phone company.** The person '
              'you call can\'t tell the difference. The only change '
              'is who carries the first part of the trip.',
        ),
        LessonCallout.note(
          title: 'The locked tunnel',
          body:
              'Your phone seals the call in a private tunnel to your '
              'carrier. The hotel or coffee shop can see that a tunnel '
              'is there. It can\'t see who you called or hear what you '
              'said.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-03.svg',
          width: 644,
          height: 212,
          caption:
              '**Figure 3. The hotel sees a tunnel, not your call.** '
              'The call stays locked inside the tunnel all the way to '
              'your carrier.',
        ),
      ],
    ),
    // ── 3. When your phone uses Wi-Fi ──────────────────────────────────────
    LessonStep(
      number: '3',
      title: 'When your phone uses Wi-Fi',
      blocks: <LessonBlock>[
        LessonLede(
          'Turning Wi-Fi Calling on doesn\'t send every call over Wi-Fi. '
          'At home, your phone mostly uses it when the cell signal is weak '
          'or missing.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-04.svg',
          width: 760,
          height: 230,
          caption:
              '**Figure 4. A backup road.** Weak or no cell signal: '
              'the call goes over Wi-Fi. Good cell signal: it usually '
              'stays on the cell network.',
        ),
        LessonHeading('How to tell'),
        LessonText(
          'On an iPhone, open Control Center and look for "Wi-Fi" next to '
          'your carrier\'s name. On Android, the call screen usually says '
          '"Wi-Fi call" or "Internet call".',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-05.svg',
          width: 644,
          height: 256,
          caption:
              '**Figure 5. Look for the word Wi-Fi.** Screens '
              'simplified; wording varies by phone.',
        ),
      ],
    ),
    // ── 4. Walking out the door mid-call ───────────────────────────────────
    LessonStep(
      number: '4',
      title: 'Walking out the door mid-call',
      blocks: <LessonBlock>[
        LessonLede(
          'A Wi-Fi call can carry on when you walk outside. It needs good '
          'cell coverage waiting for it.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-06.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 6. Handing the call over.** Walk into good '
              'coverage and the call can move to the cell network. '
              'Walk into weak coverage and the call drops, because '
              'there\'s nothing to hand it to.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          title: 'The drop that isn\'t your carrier\'s fault',
          body:
              'Walking from room to room inside a house is a different '
              'thing. Moving between two Wi-Fi access points, or two '
              'mesh units, is a Wi-Fi hand-over, and the carrier never '
              'sees it. If that hand-over is slow, the tunnel stalls and '
              'the call breaks up or drops, and most people blame the '
              'carrier. It is usually the Wi-Fi.',
          attribution: 'Keith Parsons, 2026-09-27',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-07.svg',
          width: 644,
          height: 204,
          caption:
              '**Figure 7. Moving between two Wi-Fi points.** Inside '
              'a house with two Wi-Fi points, the phone hands the '
              'call from one to the other as you walk.',
        ),
      ],
    ),
    // ── 5. Emergency calls ─────────────────────────────────────────────────
    LessonStep(
      number: '5',
      title: 'Emergency calls',
      blocks: <LessonBlock>[
        LessonLede(
          'In an emergency, your phone tries the cell network first. It '
          'only uses Wi-Fi Calling when there\'s no cell network at all.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-08.svg',
          width: 760,
          height: 270,
          caption:
              '**Figure 8. How an emergency call finds you.** Over '
              'Wi-Fi, your carrier tries to find your location. If '
              'that fails, it may use the address you entered when '
              'you switched the feature on.',
        ),
        LessonCallout.stop(
          title: 'Three things to do before you rely on Wi-Fi Calling',
          body: '',
          steps: <String>[
            'When you move house, update the emergency address in your '
                'Wi-Fi Calling settings the same day.',
            'If you ever call for help over Wi-Fi, **say where you are**. '
                'Don\'t assume the dispatcher can see it.',
            'Abroad, the address your carrier holds is still your home '
                'address. Dial the local emergency number, and use a local '
                'cell network if you can.',
          ],
        ),
      ],
    ),
    // ── 6. iPad, Mac and Apple Watch ───────────────────────────────────────
    LessonStep(
      number: '6',
      title: 'iPad, Mac and Apple Watch',
      blocks: <LessonBlock>[
        LessonLede(
          'Your iPad, Mac or Apple Watch can make calls too. There are two '
          'ways it can work.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-09.svg',
          width: 760,
          height: 290,
          caption:
              '**Figure 9. Who places the call?** In the first, your '
              'iPhone makes the call and the other device is just a '
              'speaker and microphone. In the second, the device '
              'calls through your carrier on its own. Only some '
              'carriers offer the second.',
        ),
        LessonCallout.quote(
          speaker: 'Keith\'s note',
          title: 'The emergency trap',
          body:
              'Your carrier holds one registered emergency address for '
              'your line, usually your home. A Mac or a Wi-Fi-only iPad '
              'has no cell radio, so an emergency call from it goes over '
              'Wi-Fi Calling. Apple says your device\'s location may be '
              'used, and that the registered address helps emergency '
              'services find you. If the location doesn\'t get through, '
              'the dispatcher may see your home address while you are in '
              'a hotel across the country.',
          attribution: 'Keith Parsons, 2026-09-27',
        ),
        LessonCallout.stop(title: 'Say where you are.', body: ''),
      ],
    ),
    // ── 7. Calling home from abroad ────────────────────────────────────────
    LessonStep(
      number: '7',
      title: 'Calling home from abroad',
      blocks: <LessonBlock>[
        LessonLede(
          'Wi-Fi Calling can save money on a trip. Calling home is often '
          'free. Abroad, many phones try Wi-Fi first. Calling a local '
          'number usually costs extra.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-10.svg',
          width: 760,
          height: 170,
          caption:
              '**Figure 10. Three things that can happen.** Calling '
              'home is usually free. Calling a local number is '
              'charged or blocked. And in some countries, your '
              'carrier switches the feature off.',
        ),
        LessonCallout.note(
          title: 'Check before you go',
          body:
              'The rules change from carrier to carrier and country to '
              'country. Read your own carrier\'s Wi-Fi Calling page '
              'before you travel.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-11.svg',
          width: 644,
          height: 228,
          caption:
              '**Figure 11. Set it up at home, and check your '
              'carrier.**',
        ),
        LessonCallout.caution(
          title: 'Set it up before you leave',
          body:
              'Turn it on and enter your address while you\'re at home. '
              'Some phones can\'t switch it on once you\'re abroad.',
        ),
      ],
    ),
    // ── 8. Wi-Fi Calling vs WhatsApp and FaceTime ──────────────────────────
    LessonStep(
      number: '8',
      title: 'Wi-Fi Calling vs WhatsApp and FaceTime',
      blocks: <LessonBlock>[
        LessonLede(
          'Both use Wi-Fi. Only one is a real phone call on your phone '
          'company\'s system.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-12.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 12. Two kinds of Wi-Fi call.** Wi-Fi Calling '
              'reaches almost any phone number and shows your own '
              'number. An app call only reaches people who have the '
              'same app.',
        ),
        LessonCallout.note(
          title: 'A good travel habit',
          body:
              'Use an app call for people who have the app. Use Wi-Fi '
              'Calling for everyone else: the bank, the airline, the '
              'doctor\'s office. Keep the phone app for emergencies.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-13.svg',
          width: 644,
          height: 204,
          caption:
              '**Figure 13. Pick the call by who you\'re calling.** '
              'An app call for people with the app, Wi-Fi Calling for '
              'everyone else, and the phone app in an emergency.',
        ),
      ],
    ),
    // ── 9. What your Wi-Fi owes a phone call ───────────────────────────────
    LessonStep(
      number: '9',
      title: 'What your Wi-Fi owes a phone call',
      blocks: <LessonBlock>[
        LessonLede(
          'A phone call needs a steady connection more than a fast one. '
          'Every part of the trip adds a little delay, and they all share '
          'one budget.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-14.svg',
          width: 760,
          height: 250,
          caption:
              '**Figure 14. Delay adds up, and voice gets the fast '
              'lane.** Your Wi-Fi, your internet line and the rest of '
              'the trip all add delay. Wi-Fi can put voice in its own '
              'fast lane, ahead of downloads.',
        ),
        LessonHeading('Three things to check on your router'),
        LessonSteps(<String>[
          'Leave the setting called **WMM** switched on. It gives voice '
              'the fast lane.',
          'Keep the router\'s software up to date.',
          'If calls won\'t connect at all, check your carrier\'s page. '
              'Some routers block the tunnel.',
        ]),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-15.svg',
          width: 644,
          height: 220,
          caption:
              '**Figure 15. Leave WMM on.** It is usually on already, '
              'and the name varies by router. Screen simplified.',
        ),
      ],
    ),
    // ── 10. Five things people get wrong ───────────────────────────────────
    LessonStep(
      number: '10',
      title: 'Five things people get wrong',
      blocks: <LessonBlock>[
        LessonText('Each myth is followed by what\'s true.'),
        LessonMyth(
          myth: 'It\'s on by default.',
          fact:
              'You have to switch it on, usually with an emergency '
              'address.',
        ),
        LessonMyth(
          myth: 'Once it\'s on, all my calls go over Wi-Fi.',
          fact:
              'At home, your phone mostly uses it when the cell signal '
              'is weak.',
        ),
        LessonMyth(
          myth: 'I\'ll turn it on when I land.',
          fact: 'Some phones can\'t switch it on abroad. Set it up at home.',
        ),
        LessonMyth(
          myth: 'Hotel Wi-Fi works right away.',
          fact: 'Not until you finish the hotel\'s sign-in page.',
        ),
        LessonMyth(
          myth: 'I need a VPN to keep my calls private.',
          fact:
              'The call is already sealed in a locked tunnel to your '
              'carrier.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-16.svg',
          width: 644,
          height: 154,
          caption:
              '**Figure 16. The five facts in pictures.** Each '
              'picture matches a myth above, in the same order.',
        ),
      ],
    ),
    // ── 11. Turn it on, and a checklist ────────────────────────────────────
    LessonStep(
      number: '11',
      title: 'Turn it on, and a checklist',
      blocks: <LessonBlock>[
        LessonLede(
          'It takes about a minute. Look for Wi-Fi Calling in your '
          'phone\'s settings.',
        ),
        LessonFigure(
          asset: 'assets/lesson-figures/wifi-calling/fig-17.svg',
          width: 644,
          height: 296,
          caption:
              '**Figure 17. The iPhone path.** Settings, then '
              'Cellular, then Wi-Fi Calling. Screens simplified.',
        ),
        LessonCards(<LessonCardData>[
          LessonCardData(
            title: 'iPhone',
            body:
                'Settings, then Cellular, then Wi-Fi Calling. Switch it '
                'on and confirm your address.',
          ),
          LessonCardData(
            title: 'Android',
            body:
                'Look in Settings under Network or Connections, or in '
                'the Phone app\'s settings. Switch on Wi-Fi Calling.',
          ),
        ]),
        LessonText(
          'No switch at all? Your phone or your plan doesn\'t support it.',
        ),
        LessonHeading('Before a trip'),
        LessonSteps(<String>[
          'Switch Wi-Fi Calling on at home, and make sure it works.',
          'Check your carrier\'s page for the country you\'re visiting.',
          'Learn the local emergency number where you\'re going.',
          'At the hotel, finish the Wi-Fi sign-in page before you expect '
              'calls to connect.',
        ]),
      ],
    ),
    // ── →. Where these facts come from ─────────────────────────────────────
    LessonStep(
      number: '→',
      spoken: 'Sources',
      title: 'Where these facts come from',
      blocks: <LessonBlock>[
        LessonText(
          'Checked against each company\'s own pages on 27 September 2026. '
          'Carrier rules and country lists change often, so read your '
          'carrier\'s current page before you travel.',
          small: true,
        ),
        LessonSourceList(<String>[
          '3GPP TS 33.402 (ETSI TS 133 402): IKEv2 and IPsec between the '
              'phone and the ePDG',
          'Apple 108066, make a call with Wi-Fi Calling; Apple iPhone '
              'User Guide, make calls using Wi-Fi',
          'Apple 102405, calls on iPad and Mac from iPhone; Apple '
              'FaceTime User Guide for Mac, set up phone calls',
          'Apple, Wi-Fi Calling & Privacy '
              '(apple.com/legal/privacy/data/en/wi-fi-calling)',
          'Apple 102766, recommended Wi-Fi router settings (WMM)',
          'Google Phone app Help 2811843, Wi-Fi calling; Google Fi Help '
              '16710124, web calls',
          'Samsung UK, activate Wi-Fi Calling on a Galaxy; Samsung US '
              'ANS10001614, Call & text on other devices',
          'AT&T KM1063258 and Wi-Fi Calling legal terms; KM1401809, '
              'international; KM1114459, LAN and VPN configuration',
          'Verizon Wi-Fi Calling FAQs; Verizon international and Wi-Fi '
              'Calling terms',
          'T-Mobile, Wi-Fi Calling from T-Mobile; Wi-Fi calling '
              'troubleshooting; international roaming',
          'WhatsApp Help Center, emergency calls',
          'ITU-T G.114, one-way transmission time',
          'Wi-Fi Alliance, Wi-Fi CERTIFIED WMM',
        ]),
        LessonCallout.note(
          title: 'About this guide',
          body:
              'Written for people who aren\'t technical and want to know '
              'what Wi-Fi Calling does before they need it. Product and '
              'company names are trademarks of their owners. This guide '
              'is independent and isn\'t affiliated with or endorsed by '
              'any carrier or device maker.',
        ),
      ],
    ),
  ],
);
