// DTMF audio playback — thin wrapper around just_audio.
//
// Batch 4c. The synthesis (raw PCM → WAV bytes) is pure Dart in lib/data/dtmf.dart
// and unit-tested there; this service ONLY plays the bytes. just_audio (MIT)
// gives full macOS coverage (sharedDarwinSource: iOS + macOS) plus Android and
// web, which is why it was chosen over a mobile-only engine.
//
// just_audio plays from a URI/asset/stream, not raw bytes, so we feed it the WAV
// bytes via a tiny custom StreamAudioSource (an in-memory byte source). No temp
// file, no asset bundle — the tone is generated on the fly and streamed.
//
// Two playback modes the screen uses:
//   * tap a key  -> playTone(key): one 200 ms tone, fire-and-forget.
//   * Play/Stop  -> startContinuous(key) / stop(): loop the tone until stopped.
//
// GL-008: no subprocess, no network, no cleartext HTTP — local audio only.

// `StreamAudioSource` is just_audio's documented public API for serving audio
// from in-memory bytes (the canonical "play generated/decrypted bytes" pattern
// in the package README), but the maintainer marks it `@experimental`. We use
// it deliberately and accept the API-stability risk: it is pinned to a caret
// range, and the alternative (a temp WAV file per tone) is heavier and adds a
// filesystem touch we do not want for a fire-and-forget keypad tone. Suppress
// the file-wide experimental warning rather than littering per-line ignores.
// ignore_for_file: experimental_member_use

import 'dart:async';
import 'dart:typed_data';

import 'package:just_audio/just_audio.dart';

import '../../data/dtmf.dart';

/// An in-memory [StreamAudioSource] that serves a fixed WAV byte buffer, so
/// just_audio can decode generated tones without a temp file or bundled asset.
class _BytesAudioSource extends StreamAudioSource {
  _BytesAudioSource(this._bytes) : super(tag: 'dtmf');

  final Uint8List _bytes;

  @override
  Future<StreamAudioResponse> request([int? start, int? end]) async {
    final int s = start ?? 0;
    final int e = end ?? _bytes.length;
    return StreamAudioResponse(
      sourceLength: _bytes.length,
      contentLength: e - s,
      offset: s,
      stream: Stream<List<int>>.value(_bytes.sublist(s, e)),
      contentType: 'audio/wav',
    );
  }
}

/// Plays DTMF tones generated by [Dtmf]. One [AudioPlayer] is reused across
/// taps; [dispose] releases it. Safe to call play methods rapidly — a new tap
/// stops the prior tone first.
class DtmfPlayer {
  DtmfPlayer({AudioPlayer? player}) : _player = player ?? AudioPlayer();

  final AudioPlayer _player;

  bool _disposed = false;

  /// Whether a continuous tone is currently looping.
  bool get isPlaying => _player.playing && _player.loopMode == LoopMode.one;

  /// Play a single short tone for [key] (the keypad-tap behavior). Stops any
  /// in-flight tone first so rapid taps don't overlap.
  Future<void> playTone(
    DtmfKey key, {
    int durationMs = Dtmf.defaultDurationMs,
  }) async {
    if (_disposed) return;
    final Uint8List wav = Dtmf.wavForKey(key, durationMs: durationMs);
    await _player.stop();
    await _player.setLoopMode(LoopMode.off);
    await _player.setAudioSource(_BytesAudioSource(wav));
    await _player.play();
  }

  /// Start a continuously looping tone for [key] (the Play/Stop-toggle "on"
  /// state). A longer per-loop buffer (500 ms) makes a smoother sustained tone.
  Future<void> startContinuous(DtmfKey key) async {
    if (_disposed) return;
    final Uint8List wav = Dtmf.wavForKey(key, durationMs: 500);
    await _player.stop();
    await _player.setAudioSource(_BytesAudioSource(wav));
    await _player.setLoopMode(LoopMode.one);
    await _player.play();
  }

  /// Stop any playback (single tone or continuous loop).
  Future<void> stop() async {
    if (_disposed) return;
    await _player.setLoopMode(LoopMode.off);
    await _player.stop();
  }

  /// Release the underlying player. Call from the screen's dispose().
  Future<void> dispose() async {
    if (_disposed) return;
    _disposed = true;
    await _player.dispose();
  }
}
