// DTMF audio playback — thin wrapper around just_audio.
//
// Batch 4c. The synthesis (raw PCM → WAV bytes) is pure Dart in lib/data/dtmf.dart
// and unit-tested there; this service ONLY plays the bytes. just_audio (MIT)
// gives full macOS coverage (sharedDarwinSource: iOS + macOS) plus Android and
// web, which is why it was chosen over a mobile-only engine.
//
// just_audio plays from a URI/asset/stream, not raw bytes, so we feed it the WAV
// bytes via a tiny custom StreamAudioSource (an in-memory byte source). No temp
// file, no asset bundle — the tone is generated on the fly and streamed.
//
// WINDOWS: the community Windows backend (just_audio_windows, Media Foundation)
// does NOT support StreamAudioSource — only file/asset/URL sources. So on
// Windows ONLY, the same generated WAV bytes are written to a temp file (via
// WavTempFile) and played with AudioSource.uri(file). iOS/macOS/Android/web keep
// the proven in-memory StreamAudioSource path untouched. The branch is the
// single `_useTempFilePlayback` check in `_sourceFor`.
//
// Two playback modes the screen uses:
//   * tap a key  -> playTone(key): one 200 ms tone, fire-and-forget.
//   * Play/Stop  -> startContinuous(key) / stop(): loop the tone until stopped.
//
// GL-008: no subprocess, no network, no cleartext HTTP — local audio only.

// `StreamAudioSource` is just_audio's documented public API for serving audio
// from in-memory bytes (the canonical "play generated/decrypted bytes" pattern
// in the package README), but the maintainer marks it `@experimental`. We use
// it deliberately and accept the API-stability risk: it is pinned to a caret
// range, and the alternative (a temp WAV file per tone) is heavier and adds a
// filesystem touch we do not want for a fire-and-forget keypad tone. Suppress
// the file-wide experimental warning rather than littering per-line ignores.
// ignore_for_file: experimental_member_use

import 'dart:async';
// Guard dart:io for web exactly like the network layer does: Platform is only
// read on a native target, never on web (kIsWeb short-circuits first).
import 'dart:io'
    if (dart.library.html) '../network/wifi_info_service_web_stub.dart'
    as platform_io;
import 'dart:typed_data';

import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:just_audio/just_audio.dart';

import '../../data/dtmf.dart';
import '../../data/signaling_tones.dart';
import 'wav_temp_file.dart';

/// An in-memory [StreamAudioSource] that serves a fixed WAV byte buffer, so
/// just_audio can decode generated tones without a temp file or bundled asset.
class _BytesAudioSource extends StreamAudioSource {
  _BytesAudioSource(this._bytes) : super(tag: 'dtmf');

  final Uint8List _bytes;

  @override
  Future<StreamAudioResponse> request([int? start, int? end]) async {
    final int s = start ?? 0;
    final int e = end ?? _bytes.length;
    return StreamAudioResponse(
      sourceLength: _bytes.length,
      contentLength: e - s,
      offset: s,
      stream: Stream<List<int>>.value(_bytes.sublist(s, e)),
      contentType: 'audio/wav',
    );
  }
}

/// Plays DTMF tones generated by [Dtmf]. One [AudioPlayer] is reused across
/// taps; [dispose] releases it. Safe to call play methods rapidly — a new tap
/// stops the prior tone first.
class DtmfPlayer {
  DtmfPlayer({AudioPlayer? player}) : _player = player ?? AudioPlayer();

  /// Whether DTMF/tone PLAYBACK is supported on the current platform.
  ///
  /// just_audio has first-party implementations for iOS, macOS, Android, and
  /// web, and the community `just_audio_windows` (Media Foundation) federated
  /// implementation now covers Windows. Windows cannot use the in-memory
  /// StreamAudioSource path — it plays from a temp WAV file instead (see
  /// [_sourceFor] / [_useTempFilePlayback]) — but playback IS supported, so the
  /// tone tools no longer gate off on Windows. The pure-Dart tone SYNTHESIS
  /// (lib/data/dtmf.dart + signaling_tones.dart) is platform-independent.
  static bool get playbackSupportedOnThisPlatform => true;

  /// Whether this platform must route playback through a temp WAV file rather
  /// than the in-memory [StreamAudioSource]. True ONLY on Windows, whose
  /// just_audio backend has no StreamAudioSource support. kIsWeb short-circuits
  /// first so [platform_io.Platform] is never read on web.
  static bool get _useTempFilePlayback {
    if (kIsWeb) return false;
    return platform_io.Platform.isWindows;
  }

  final AudioPlayer _player;

  /// The Windows temp-file sink (lazily used only when [_useTempFilePlayback]).
  final WavTempFile _tempWav = WavTempFile('dtmf');

  bool _disposed = false;

  /// Build the right [AudioSource] for [wav]: the in-memory byte source on
  /// iOS/macOS/Android/web, or a temp file on Windows. Centralizes the single
  /// platform branch so every play path below stays identical.
  Future<AudioSource> _sourceFor(Uint8List wav) async {
    if (_useTempFilePlayback) {
      return AudioSource.uri(await _tempWav.write(wav));
    }
    return _BytesAudioSource(wav);
  }

  /// Whether a continuous tone is currently looping.
  bool get isPlaying => _player.playing && _player.loopMode == LoopMode.one;

  /// Play a single short tone for [key] (the keypad-tap behavior). Stops any
  /// in-flight tone first so rapid taps don't overlap.
  Future<void> playTone(
    DtmfKey key, {
    int durationMs = Dtmf.defaultDurationMs,
  }) async {
    if (_disposed) return;
    final Uint8List wav = Dtmf.wavForKey(key, durationMs: durationMs);
    await _player.stop();
    await _player.setLoopMode(LoopMode.off);
    await _player.setAudioSource(await _sourceFor(wav));
    await _player.play();
  }

  /// Start a continuously looping tone for [key] (the Play/Stop-toggle "on"
  /// state). A longer per-loop buffer (500 ms) makes a smoother sustained tone.
  Future<void> startContinuous(DtmfKey key) async {
    if (_disposed) return;
    final Uint8List wav = Dtmf.wavForKey(key, durationMs: 500);
    await _player.stop();
    await _player.setAudioSource(await _sourceFor(wav));
    await _player.setLoopMode(LoopMode.one);
    await _player.play();
  }

  /// Play a SEQUENCE of DTMF keys in order (BF6-1: the "pre-load a string of
  /// digits, then play" mode). Each key plays for [toneMs], followed by a
  /// [gapMs] silence so adjacent tones are distinguishable (real DTMF dialers
  /// insert an inter-digit gap). The returned future completes when the whole
  /// sequence has played (or is cancelled).
  ///
  /// Cancellation: [shouldContinue] is checked before each tone; returning false
  /// (e.g. the user pressed Stop, or left the screen) ends the sequence early.
  /// This keeps the player from holding the audio session after a Stop.
  Future<void> playSequence(
    List<DtmfKey> keys, {
    int toneMs = Dtmf.defaultDurationMs,
    int gapMs = 80,
    bool Function()? shouldContinue,
  }) async {
    if (_disposed) return;
    await _player.setLoopMode(LoopMode.off);
    for (final DtmfKey key in keys) {
      if (_disposed) return;
      if (shouldContinue != null && !shouldContinue()) return;
      final Uint8List wav = Dtmf.wavForKey(key, durationMs: toneMs);
      await _player.stop();
      await _player.setAudioSource(await _sourceFor(wav));
      await _player.play();
      // Wait out the tone, then the inter-digit gap, honoring cancellation.
      await Future<void>.delayed(Duration(milliseconds: toneMs + gapMs));
    }
    if (!_disposed) await _player.stop();
  }

  /// Play a single historical signaling signal (Blue Box MF / KP / ST / 2600,
  /// or a US Red Box coin pattern). The whole signal — including its multi-burst
  /// timing and inter-burst gaps for a dime / quarter — is baked into one WAV by
  /// [SignalingTones.synthesize], so this is a single fire-and-forget play, the
  /// same plumbing as [playTone]. Stops any in-flight tone first.
  Future<void> playSignalingTone(SignalingTone tone) async {
    if (_disposed) return;
    final Uint8List wav = SignalingTones.wavForTone(tone);
    await _player.stop();
    await _player.setLoopMode(LoopMode.off);
    await _player.setAudioSource(await _sourceFor(wav));
    await _player.play();
  }

  /// Stop any playback (single tone, continuous loop, or sequence).
  Future<void> stop() async {
    if (_disposed) return;
    await _player.setLoopMode(LoopMode.off);
    await _player.stop();
  }

  /// Release the underlying player. Call from the screen's dispose().
  Future<void> dispose() async {
    if (_disposed) return;
    _disposed = true;
    await _player.dispose();
    await _tempWav.cleanup();
  }
}
